### ISSUE TITLE
Automatically create authorization groups in keycloak

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1001]
In the keycloak controller, it would be nice if it along with the admin user also created the groups commonly used for authorization:

* admin
* manage
* send_*
* recv_*
* manage_*
...

**Comment by kornys** [comment]
Please dont forget on send_#, recv_#

**Comment by lulf** [comment]
@kornys 
@rgodfrey 

Remind me why do we need both send_* and send_# ?

**Comment by kornys** [comment]
send_# is for brokered address space, where widlcard chaar is '#'. https://activemq.apache.org/artemis/docs/latest/wildcard-syntax.html

**Comment by grs** [comment]
What is the long term solution here?

**Comment by lulf** [comment]
The issue is mentioned briefly in #939. Is this something we can make consistent short term by changing the broker configs?

**Comment by kornys** [comment]
It would be fine when we use 

```xml
<wildcard-addresses>
    <routing-enabled>true</routing-enabled>
    <delimiter>.</delimiter>
    <any-words>*</any-words>
    <single-word>#</single-word>
  </wildcard-addresses>
```

Anyway this change will require update authz systemtests

**Comment by grs** [comment]
The only issue there is that the wildcard scheme you might want for addressing and that you might want for authz could be different. For the former, MQTT style makes sense in my view. However I think '*' is much more obvious/intuitive when dealing with permissions.

**Comment by lulf** [comment]
Wouldn't changing to any-words * mean that we can use MQTT style addressing _and_ * in permissions?

**Comment by grs** [comment]
MQTT uses # (mult-level) and + (single level).

**Comment by lulf** [comment]
Ah, right :/ This is the mqtt config we use (which I thought was similar to what @kornys pasted): https://github.com/EnMasseProject/enmasse/blob/master/artemis/config_templates/standard/sharded-topic/broker.xml#L103

**Comment by grs** [comment]
@rgodfrey might one option be for the broker authz plugin to simply translate from * to # (or whatever else is configured)?

**Comment by kornys** [comment]
Anyway for brokered we should remove delimeter of addresses like in standard address space.

**Comment by kornys** [comment]
@lulf it is implemented by user api I guess, right?

**Comment by lulf** [comment]
Yes I would say so.
