### ISSUE TITLE
Querying specific existing address with REST API return "not found"

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse#1004]
Hi,
querying the address REST API I'm able to get the addresses from the addresses space named "default" : 

https://168.63.96.232/apis/enmasse.io/v1/addresses/default
{"apiVersion":"enmasse.io/v1","kind":"AddressList","items":[{"metadata":{"name":"mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b","addressSpace":"default","uuid":"7f13ef30-88ed-3312-98a3-c2e2fc468f3b"},"spec":{"type":"topic","plan":"sharded-topic","address":"mytopic"},"status":{"isReady":true,"phase":"Active"}}]}

but trying to the specific info about the address "mytopic" getting from : 

https://168.63.96.232/apis/enmasse.io/v1/addresses/default/mytopic

I got : 

{"error":"NotFound","description":"Address mytopic not found"}

I did that based on the current doc : 

https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/address-model/resource-definitions.adoc#address

Am I doing in the right way ?

**Comment by lulf** [comment]
No, you are doing it the wrong way :rofl: 

There are 3 ways to achieve what you wish:

* Set the 'name' field in the metadata explicitly. If it is a valid kubernetes resource identifier, you will be able to query the REST API using that identifier.
* Use the resource identifier returned in the response when you create the address, which in your output is 'mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b'
* On master, use /v1/addresses/default?address=mytopic which will query based on the address field 

The reason for this change is that we want to enforce valid kubernetes identifiers in the resource name. If you do not specify a name (or it is invalid), the API will generate a valid one based on the address field.

**Comment by ppatierno** [comment]
Ok I miss that "name" and "address" are two different things :-) Thanks !

PS : the doc should be improved !!! :P
