### ISSUE TITLE
Make resync interval in controllers configurable

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1009]
The resync interval in the controllers should be configurable. Right now, its hardcoded to 10 + (0-5) seconds in the address controller. I'm thinking we should expose 1 env in the address controller, standard controller and agent:

RESYNC_INTERVAL

@grs wdyt? I'm not sure if the agent has the variable part, but I assume the first variable makes sense?

**Comment by grs** [comment]
Resync what?

**Comment by lulf** [comment]
The address configmaps. In the java controllers, the configmaps are periodically refreshed and watches reset.

**Comment by grs** [comment]
@lulf, the agent issues a standard GET then watches the list until the watch is ended, then it reissues the GET and watches again etc. There are no times hardcoded around this.

**Comment by lulf** [comment]
@grs After giving it some more thought, I'm not sure having a MIN and MAX gives us much, since its such a long period, and its only used once in each controller, and since they will start up at different times there is no gain in randomizing.
