### ISSUE TITLE
Events sent to address of type queue not delivered after a while

### ISSUE THREAD

**Issue by chapitos** [EnMasseProject/enmasse#1017]
Currently using Enmasse 0.17.0 we have already had a couple of occurrences of a problem where an anycast address of type queue starts storing messages (in memory queue). The outcome is that we do not receive messages on the consumer side. Connection between Qpid and consumer is there (no detach). 
The workaround which we currently use is to find out to which broker (Artemis) our utility was sending messages to and restart that POD in Kubernetes cluster. 

Attached are two set of logs of two separate occurrences of the problem.
[enmasse-logs2.zip](https://github.com/EnMasseProject/enmasse/files/1789417/enmasse-logs2.zip)
[enmasse_logs.zip](https://github.com/EnMasseProject/enmasse/files/1789418/enmasse_logs.zip)

**Comment by lulf** [comment]
@chapitos Can't figure out much from the log, but I will try to do some stress-testing with many queues and see if I can reproduce the issue.

**Comment by chapitos** [comment]
@lulf thanks for looking into it. We have are facing this issue pretty regularly (last time yesterday evening). If it can help we can do an online session if you want to take a look at the system while it is happening. Please let me know.

**Comment by lulf** [comment]
@chapitos That would be very helpful.
