### ISSUE TITLE
update resource-definition - add comments which features are enabled/disabled ...

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#1024]
look at resource-definition and add comments or explanations what methods or attributes are not support, are disabled or are not working please.

https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/address-model/resource-definitions.adoc

**Comment by tkratky** [comment]
it looks like GET request to /apis/enmasse.io/v1/addresses path is not documented at all

**Comment by tkratky** [comment]
maybe there should be also mentioned that since specific version (I don't remember the number) restapi path changed from /v1 to /apis/enmasse.io/v1/

**Comment by tkratky** [comment]
authenticationService: None/Standard is not documented or is documented on wrong place

**Comment by jenmalloy** [comment]
No longer applicable, so closing
