### ISSUE TITLE
System-tests: create new test fo REST API - PUT | /v1/addresses/myspace/:name

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#1027]
tracker https://github.com/EnMasseProject/enmasse/issues/936

Create or modify test to use replace sigle address with REST API

**replace single address is never tested in system-tests, currently doesn't work, correct behavior will be explained as part of #1024 **

**Comment by lulf** [comment]
This is not really relevant anymore i think as all addresses are now created deleted individually
