### ISSUE TITLE
qdrouter crashes with exit code 139 on many unauthorized connection attempts

### ISSUE THREAD

**Issue by DanielMaier-BSI** [EnMasseProject/enmasse#1053]
Hi,

I am not sure if this is related to enmasse or directly to qdrouter. We have a setup where enmasse is connected to keycloak. When we have a client that connects to qdrouter with wrong credentials we get (of course) many log entries like this
```
2018-03-13 13:47:35.376257 +0000 SERVER (info) Connection from 172.17.0.24:34576 (to 0.0.0.0:5671) failed: amqp:unauthorized-access Failed to authenticate client [mech=PLAIN]
```
and after a while (10 - 15 minutes) qdrouter crashes with exit code 139 and gets restarted again and again. Client tries to reconnect every 500 msec. Without this client with wrong credentials this error does not occur.

Thanks
Daniel

**Comment by DanielMaier-BSI** [comment]
Tested again and can confirm that it works now. Thanks a lot.

**Comment by grs** [comment]
Thanks for confirming Daniel!
