### ISSUE TITLE
pooled-queue "Quota exceeded" despite of credit is sufficient

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#1060]
test testQuotaLimitsPooled started failing after yesterdays changes in master.
https://github.com/EnMasseProject/enmasse/blob/3ed44b390c1deb0d3b1d8ed7edb77cdb55b9bf14/systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java#L109

Tests creates standard address space with credits {broker: {min: 0, max:2}, router: {min:1, max: 1}, and aggregate: {min:0, max:2}} and then tries to create 12 queues with resources which are in sum 1.9 and address space has 2 credits for broker which is sufficient. Standard controller contains statusMessage "Quota exceeded" for queues with plan pooled-queue. 

Automated test:
```sh
make MULTITENANT=true SYSTEMTEST_ARGS='common.plans.PlansTest#testQuotaLimitsPooled' systemtests
```

**Comment by grs** [comment]
First failing build, showing the commits: https://maas-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/enmasse-master-common/88/

**Comment by lulf** [comment]
@grs @kornys I'm working on this as part of #1058
