### ISSUE TITLE
Fix unstable test enmasse.discovery.DiscoveryTest.testDiscovery

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#109]
enmasse.discovery.DiscoveryTest > testDiscovery FAILED
    java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at enmasse.discovery.DiscoveryTest.testDiscovery(DiscoveryTest.java:68)

Also see https://travis-ci.org/EnMasseProject/enmasse/builds/262561839#L5275

**Comment by lulf** [comment]
Also: https://travis-ci.org/EnMasseProject/enmasse/builds/267557525

**Comment by lulf** [comment]
Closing, as the test has not failed since last commit I believe.

**Comment by grs** [comment]
I just saw a failure on a travis build of a branch[1] I am working on that has not touched anything in admin:

> enmasse.discovery.DiscoveryTest > testDiscovery FAILED
> 
>     java.util.concurrent.TimeoutException
> 
> 1 test completed, 1 failed
> 
> :admin:common-lib:discovery:test FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> 
> Execution failed for task ':admin:common-lib:discovery:test'.

Re-running the build, the failure did not occur. So I suspect the issue may still be there (but perhaps less common).

[1] https://github.com/EnMasseProject/enmasse/pull/234

**Comment by lulf** [comment]
Saw this in https://travis-ci.org/EnMasseProject/enmasse/builds/278540739 as well, reopening.

**Comment by lulf** [comment]
Not failing anymore
