### ISSUE TITLE
Provisioning failed for queue/topic when using glusterfs

### ISSUE THREAD

**Issue by jcordes73** [EnMasseProject/enmasse#1105]
When creating a queue or topic, dynamic provisioning with glusterfs fails, because of the length of the resulting endpoint name:

Failed to provision volume with StorageClass "glusterfs-storage": glusterfs: create volume err: failed to create endpoint/service error creating endpoint: Endpoints "glusterfs-dynamic-mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b-mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b-0" is invalid: metadata.labels: Invalid value: "mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b-mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b-0": must be no more than 63 characters

Wouldn't it be enough to shorten it to mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b-0 or even just to the name of the queue/topic?

**Comment by lulf** [comment]
@jcordes73 I'm not sure why it appends the name twice, I suspect this is the doing of the statefulset controller in kubernetes. As a workaround you can set the '.metadata.name' field if you create it via the REST API, though I agree we should figure out how to avoid this.
