### ISSUE TITLE
Inactive autolinks and missing producers/consumers in Artemis - restarts don't help

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1143]
We have just gotten in a situation, where brokered addresses are all marked isReady=false because of missing autolinks and seemingly can't be made to get ready again (by restarting enmasse components).

In the broker, queues are there but producers and consumers for the addresses are missing.

Logs: 
[logs.zip](https://github.com/EnMasseProject/enmasse/files/1906883/logs.zip)

**Comment by calohmn** [comment]
Admin pod restart doesn't change things ([logs_3_admin_restart.zip](https://github.com/EnMasseProject/enmasse/files/1907181/logs_3_admin_restart.zip)).

The Connections tab contains one entry:
![connectionstab](https://user-images.githubusercontent.com/891931/38733128-1390689a-3f21-11e8-9687-6effc60d572f.png)

**Comment by lulf** [comment]
Ok, so this connection that is there doesn't look like the connector service, since the local address iss :5673 which is the incoming port. It would be interesting if you could list the connector services. I think it might be possible to do in the broker console if you use the 'broker' object and find and an attribute or operation called 'getConnectorServices'.

**Comment by calohmn** [comment]
The `ConnectorServices` attribute contains "amqp-connector router-connector".
So I guess that looks ok.

**Comment by lulf** [comment]
I think this means there is some issue with the connector service, since it is created, but you don't see an outgoing connection established, neither to the agent (amqp-connector) or the router.  If you can provide me a jstack and a jmap heap dump for analysis I can try to figure out what has happened.

**Comment by calohmn** [comment]
I think the "Connections" tab doesn't show these connections - at least it doesn't on another system of ours where all addresses are ready.

Thread dump is here: 
[threads.dump.zip](https://github.com/EnMasseProject/enmasse/files/1907326/threads.dump.zip)

**Comment by calohmn** [comment]
Here the router connections: 
[router_connections.txt](https://github.com/EnMasseProject/enmasse/files/1907440/router_connections.txt)

**Comment by lulf** [comment]
The autolinks from qdmanage point to the issue I think. After the change to support per-address limits in the broker, the agent changed to create a connector service per queue. However, it looks like this is not happening for some reason, as only connector services amqp-connector and router-connector are present.

**Comment by lulf** [comment]
Looking at the agent code, it looks like the agent only checks if addresses/queues exists and not connector services, thereby not recreating the connector services if an address already exists. This is similar to a bug that was in the queue-scheduler at some point.

@grs In broker_controller.js BrokerController.prototype._sync_broker_addresses it looks like it is doing a listAddresses(), and then creates addresses + connector service for each missing address. If the broker is restarted, however, the broker will return the addresses, but the connector services will be missing in the broker, so the logic must be changed to check the connector services as well. I guess this was introduced when it was changed to create a connector service per address.
