### ISSUE TITLE
Allow authentication service CA to be empty

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1153]
If the certificate presented by keycloak is valid, there is no need to provide the keycloak (and it is in fact specified as an optional parameter for the external authentication service). We should therefore change router and broker configuration to handle the case where the authservice CA cert does not exist.

**Comment by grs** [comment]
I may be misunderstanding the point of this issue, but I believe openssl will always require the appropriate trusted issuer certs to be specified.

**Comment by lulf** [comment]
I tested this with qdmanage. If I didn't supply any cert path, it accepted the ca maybe because it was part of some system certs included in the image?

**Comment by grs** [comment]
The proton python library doesn't do any cert validation by default, so it could also be that.

**Comment by lulf** [comment]
Just verified that running curl or openssl inside the router pod accepts the certificate.  Does proton-c validate certs by default as well? If not, I guess we cannot rely on the system certs.

**Comment by grs** [comment]
If openssl is picking up the system certs, then it should work. (I didn't think it did that by default but some quick googling suggests it will; good to now)

**Comment by lulf** [comment]
Fixed in 0.23.0
