### ISSUE TITLE
build artefacts for travis builds don't contain all logs

### ISSUE THREAD

**Issue by grs** [EnMasseProject/enmasse#1177]
some address spaces just have config maps (but not all, I did see logs in one brokered address space)

**Comment by tkratky** [comment]
@lulf is this enough for closing this issue? https://github.com/EnMasseProject/enmasse/commit/74cd4851963780007e74aa04e015f62cdcda8526

**Comment by tkratky** [comment]
https://github.com/EnMasseProject/enmasse/pull/1179

**Comment by lulf** [comment]
Should be fixed now, thanks @tkratky !
