### ISSUE TITLE
deploy.sh: Use alternative to clusterIP for Keycloak httpUrl

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1197]
When I run the `deploy.sh` to deploy EnMasse on my Minikube cluster (with authentication "standard"), the Keycloak `httpUrl` gets set to the ClusterIP from the Keycloak service.
This IP however isn't reachable from the parent host, which causes the EnMasse console login to not work.
I wonder in which case usage of the ClusterIP here does indeed work?

I guess, finding a mechanism to return the correct `httpUrl` for all possible scenarios is quite difficult.
It could be the Minikube/Minishift IP+NodePort or the Loadbalancer hostname (`.status.loadBalancer.ingress.hostname`) or even something like `.metadata.annotations."dns.alpha.kubernetes.io/external"` if the service was annotated in such a way.

To make it work in the "let's get started with EnMasse and use Minikube/Minishift" case, I would suggest adding a detection for Minikube/Minishift in the `deploy.sh` und use Minikube/Minishift IP+NodePort in that case. I could create a PR for this.

**Comment by lulf** [comment]
The approach used in the ansible playbook is that you can configure the keycloak_http_url setting. I think for more advanced installations we should have ansible work for kubernetes. However, having the deploy.sh is useful for the local deploy/development use case. 

Adding minikube/minishift autodetection is a good approach IMO.

**Comment by lulf** [comment]
@calohmn Ok to close? Or would you like to keep this around in search for another solution?

**Comment by calohmn** [comment]
@lulf yes, closing it. There can be a new ticket for another solution.
