### ISSUE TITLE
K8s deployment: EnMasse Console redirect to Keycloak login page fails

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1204]
Using latest master:

I've modified the `deploy.sh` to use the Minikube IP+NodePort as Keycloak `httpUrl` (see #1197)  and then run: 
````
bash deploy.sh -a "standard" -n enmasse -t kubernetes
````

When accessing the EnMasse console, there is a redirect to Keycloak with the URL:
````
https://192.168.99.100:31173/auth/realms/default/protocol/openid-connect/auth?client_id=enmasse-console&state=4181e5c0-61e7-4dd0-96a6-dd15f97af172&redirect_uri=https%3A%2F%2F192.168.99.100%3A31010%2F%3Fauth_callback%3D1&scope=openid&response_type=code
````
with the error
````
WE'RE SORRY ...
Client not found.
````

Looking in the Keycloak default realm, there is indeed no `enmasse-console` client.
Further debugging into `KeycloakManager`, the client is not created in `Keycloak#createRealm()` because:
- `KeycloakManager#getConsoleRedirectURI()` returns null because
  - There is no default address space endpoint with name "console", there are only these endpoints: console-external, messaging-external and mqtt-external
  - The `console-external` endpoint in the default address space has also no `host` set:
> {
  "name": "console-external",
  "service": "console",
  "port": 31010,
  "cert": {
    "provider": "selfsigned",
    "secretName": "external-certs-console"
  }
}

---------
In the Openshift deployment case, the Keycloak `enmasse-console` client gets added. Endpoint names in the default address space don't have the "-external" suffix and host is set:
> {
  "name": "console",
  "service": "console",
  "host": "console-enmasse2.192.168.42.214.nip.io",
  "port": 443,
  "cert": {
    "provider": "selfsigned",
    "secretName": "external-certs-console"
  }
}

**Comment by k-wall** [comment]
I believe this issue is resolved.
