### ISSUE TITLE
Console crashes if none-authservice crashes

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#122]
Currently, if the none-authentication service crashes (i.e. running out of memory), the console also crashes. The console should be made more robust to deal with that scenario gracefully.

To reproduce: reduce memory available to none-authservice to 8Mb (and make sure none is used as authentication service for the address space).

**Comment by grs** [comment]
I can't reproduce this. The console doesn't let you logon if the auth service keeps crashing, but I don't see the console itself crashing.

**Comment by lulf** [comment]
@grs I've not seen it for a long time, so could be it has been fixed as part of changes to the console since august.

**Comment by lulf** [comment]
I'll close this issue for now then.
