### ISSUE TITLE
(mqtt): large payloads not supported and max payload size not configurable

### ISSUE THREAD

**Issue by ertanden** [EnMasseProject/enmasse#1231]
Seems like currently it's not possible to send large payloads (larger than 8K?) and it's not configurable. 

I would suggest having a default of 128K at least and make it configurable.

**Comment by rgodfrey** [comment]
@ertanden Apologies, we've been looking at MQTT support as a whole, and some of the issues with the current approach, but I don't see any reason why we shouldn't make this obvious change in the meantime.
