### ISSUE TITLE
Upgrade to Artemis 2.6.2

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1252]
Released on 2018/5/22

**Comment by rgodfrey** [comment]
Even better - upgrade to Artemis 2.6.1 which includes [ARTEMIS-1872](https://issues.apache.org/jira/browse/ARTEMIS-1872) which fixed #660

**Comment by k-wall** [comment]
2.6.2 is now out, but as noted by @calohmn the netty-tcnative-boringssl-static jar will not be included any more - see https://issues.apache.org/jira/browse/ARTEMIS-1913.
