### ISSUE TITLE
Router 1.1.0 rc3 shows performance decrease

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1261]
We have done some load-testing and found that using the router image from PR #1227 showed a noticably lower message throughput - it was 1,6k anycast messages vs. 2k messages with the current router image.

Test setup: 10000 clients (on 6 EC2 instances), delay during message sending is set so that roughly 2000 messages per second are sent. A test message has 512 byte.

**Comment by grs** [comment]
Each of the 10,000 clients sends and receives at ~2000 msgs/sec through a single anycast address, is that right? i.e. 20,000 messages per second on aggregate? And was it that the rc3 image was not able to sustain that load, managing only 1600 msgs/sec per pair?

**Comment by calohmn** [comment]
It's 2000 msgs/sec from all clients combined. And yes to the last question.

**Comment by calohmn** [comment]
> So each pair is only sending about 1 message every 5 seconds? 

yes. We are using JMeter with a constant-throughput-timer set to 2000 msgs/sec. 
The value of 10000 clients represents the value that we want to test with, also concerning number of connections. The value of 2000 msgs/sec is something that we have come to because we saw that with our setup (using Hono), we didn't achieve more than 2,2k msgs/sec (we are investigating this separately to see where the bottleneck is). 

> Does the test involve waiting for acceptance of sent message, or waiting to receive it in any way? I.e. could it be a case of increased latency?

There is no waiting for message acceptance. Messages are sent via MQTT to the Hono MQTT Adapter.

> Also, are you using the same base image as from PR #1227 (I.e. not the same router image, just the same base image; just want to confirm that you aren't using the router with full trace logging enabled :-))?

We have adopted the changes from PR #1227 - but not the change that enabled trace logging (and also made sure `PN_TRACE_FRM=1` is not set).

**Comment by grs** [comment]
I've done some simple comparisons between the images. The tests don't match yours in scale or in approach, but are perhaps another useful data point in tracking down the issue. For larger numbers of connections (and I was using hundreds not thousands), I *might* be seeing a small regression (between 2 and 4% at most), however this is at aggregate throughput way higher than what you are looking at (135k msgs/sec). For single sender/receiver the latest image is if anything marginally faster.

I think the regression you are seeing must be coming from some particular interaction. 2k msgs/sec is very, very low.

**Comment by calohmn** [comment]
@grs we have tested some more with your newest base image (`qdrouterd-base:1.1.0-rc3_proton-0.23.0-rc1`) and have now reached 2k msgs/sec again (ie. it's matching the input rate).

**Comment by grs** [comment]
@calohmn thanks for the update! Does that mean we can close this?

**Comment by calohmn** [comment]
@grs we have done some more tests - also with EnMasse 0.20.0 as base and numbers are looking good. So, yes, closing the issue.
