### ISSUE TITLE
Unable to create a queue on a standalone broker because the name is longer than 63 characters

### ISSUE THREAD

**Issue by rmarting** [EnMasseProject/enmasse#1272]
If you try to create a queue on a standalone broker and your name is more longer that 63 characters, the queue is not deployed. 

The following event you see on OpenShift:

> create Pod samplequeuestandalone-a07d784a-b1a2-7542-89c5-08a69c8ec220-0 in StatefulSet samplequeuestandalone-a07d784a-b1a2-7542-89c5-08a69c8ec220 failed error: Pod "samplequeuestandalone-a07d784a-b1a2-7542-89c5-08a69c8ec220-0" is invalid: metadata.labels: Invalid value: "samplequeuestandalone-a07d784a-b1a2-7542-89c5-08a69c8ec220-6bf8df75f7": must be no more than 63 characters

The original name used to define the queue was: sampleQueueStandalone. 

You only see this event if you have access to the OCP, however in Enmasse console you only see that the queue is still pending to be deployed.

It is something that it should be nice to manage from the User Experience perspective to avoid this kind of errors.

PS: If I used 'sampleStandalone' as name, then it is deployed successfully.

**Comment by lulf** [comment]
@k-wall I believe it should be fixed now, as the pods will now be named 'b-<UUID>'.

**Comment by lulf** [comment]
@rmarting Please reopen if it occurs again with 0.21.2
