### ISSUE TITLE
API-Server: AddressSpace list is empty

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1275]
When doing a GET on the AddressSpace resource (`/apis/enmasse.io/v1alpha1/namespaces/enmasse/addressspaces`), an empty AddressSpaceList is returned.

**Comment by calohmn** [comment]
Reason is that when the AddressSpace ConfigMap gets replaced during an AddressSpace update, the `namespace` label doesn't get set.

**Comment by lulf** [comment]
Thanks!
