### ISSUE TITLE
Agent: Used brokered address setting "maxSizeBytes" too restrictive

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1278]
We have configured Artemis with a "GLOBAL_MAX_SIZE" of 1GB (via a parameter in the broker resource-definition).
In the address plan "pooled-queue", we have set the broker credits to `0.0001` - meaning that for up to 10k addresses, we only want to have one broker.

Doing load-tests with this setup, we saw frequent messages like this:
````
AMQ222039: Messages sent to address 'event/LOAD_TEST_TENANT' are being dropped; size is currently: 108,116 bytes; max-size-bytes: 107,374
````
This shows that the max-size-bytes per Artemis address is just around 100kB.

We were a bit surprised to see this, expecting max-size-bytes to be `-1`, so that the entire globalMaxSize is used.

Looking at the Agent code, the `maxSizeBytes` is set to `[broker credits] * [globalMaxSize]`, leading to the above value of 100kB.

This calculation of the `maxSizeBytes` seems quite restrictive and inflexible. 

This relates to #712.

**Comment by lulf** [comment]
@calohmn The per-address restrictions are dropped in 0.20.0. Are you using 0.19?

**Comment by calohmn** [comment]
@lulf ah, ok. Yes, I was using 0.19. 
Have checked with 0.20.0 now and restrictions are gone.
