### ISSUE TITLE
Add support for PATCH to api server

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1279]
Allowing PATCH/json-patch support will allow 'oc edit addressspace foo' to work, which will be a common operation if changing plans etc. Arguably we might want to support changing plans before we add this support.

**Comment by k-wall** [comment]
A use-case that occurs to me is to give the user the ability to add his own annotations to addresses that already exist.  This would allow the user to say, group addresses that relate to a particular business function for ease of monitoring.
