### ISSUE TITLE
Create an uninstall ansible playbook

### ISSUE THREAD

**Issue by hguerrero** [EnMasseProject/enmasse#1297]
As we have a install playbook, it would be great to have an uninstall that takes the same inventory and removes everything from the openshift cluster.

**Comment by dmvolod** [comment]
Before this, it's should be good to add label app=enmasse to all entities configured with ansible to be able delete them by label. I'm working on it right now.

**Comment by hguerrero** [comment]
any update?

**Comment by lulf** [comment]
@hguerrero Playbook not yet created, but instruction on uninstall exists now: 
http://enmasse.io/documentation/openshift/master/#uninstalling-messaging

**Comment by lulf** [comment]
@hguerrero https://github.com/EnMasseProject/enmasse/pull/2064
