### ISSUE TITLE
Loading huge count of addresses takes a really long time

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#1309]
This issue is related to enhancement for paging in console: https://github.com/EnMasseProject/enmasse/issues/1305

**Description:**
When many addresses is created (tested with ~3300 addresses) then loading of all addresses takes something around 20 minutes. 

Javas script console contains output mentioned in following comment: https://github.com/EnMasseProject/enmasse/issues/1305#issuecomment-393856733

ConfigMap of address-plan exists in many-addresses-standard project:
```
{"apiVersion":"enmasse.io/v1","kind":"AddressPlan","metadata":{"name":"pooled-xxs-queue"},"displayName":"pooled-xxs-queue","displayOrder":"0","shortDescription":"Newly defined address plan.","longDescription":"Newly defined address plan.","uuid":"f64cc30e-0d9e-11e8-ba89-0ed5f89f718b","addressType":"queue","requiredResources":[{"name":"broker","credit":0.001}]}
```
ConfigMaps of all addresses exists and have a following content:
```
{"apiVersion":"enmasse.io/v1alpha1","kind":"Address","metadata":{"name":"xxs-queue-0","namespace":"myproject","addressSpace":"many-addresses-standard","uid":"2458847a-6577-11e8-8698-525400e26b8e","selfLink":"/apis/enmasse.io/v1alpha1/namespaces/myproject/addressspaces/many-addresses-standard","creationTimestamp":"2018-06-01T08:38:22Z","resourceVersion":"130830","labels":{"addressType":"queue"},"annotations":{"enmasse.io/broker-id":"broker-2","cluster_id":"broker"}},"spec":{"type":"queue","plan":"pooled-xxs-queue","address":"xxs-queue-0"},"status":{"isReady":true,"phase":"Active"}}
```

![image](https://user-images.githubusercontent.com/17743200/40840376-b0159536-65a6-11e8-9abe-bd3b6e8632db.png)

reproducible via automated marathon test in enable-tests branch: https://github.com/EnMasseProject/enmasse/blob/9fffde3d97a989a55d6311c9769c1bb647fa65c1/systemtests/src/test/java/io/enmasse/systemtest/marathon/PlansMarathonTest.java#L41

Unfortunately I was not able to discover nothing else...

**Comment by RH-sdavey** [comment]
Downstream issue has been fixed and reviewed and completed.  Issue can be closed
