### ISSUE TITLE
need to limit length of address-space name

### ISSUE THREAD

**Issue by grs** [EnMasseProject/enmasse#1318]
The names of the configmaps in which addresses are held are prefixed with the address space and have a uuid appended to ensure uniqueness regardless of any transformation required for addresses with invalid characters.

The maximum length for a name is 60 characters (there is a limit in kubernetes of 63 and we reserve 3 chars for statefulsets which use the qualified address name). A stringified uuid with separator takes up 37 chars. This means the address-space name cannot be allowed to exceed 22 chars (assuming one char for the '.' separator). (An address-space with a name of 22 chars will have all its addresses identified solely by uuid as there will be no space for any part of the actual address).

**Comment by lulf** [comment]
I heard today that configmap names can be longer (up to 253 characters) if you use the dot ‘.’ separator.

I’ll need to test it in detail, but this could potentially allow longer names

**Comment by grs** [comment]
We had a test failure that appeared to be due to the name being too long; it was resolved by reducing the length of the address-space name.

**Comment by lulf** [comment]
```
oc create configmap mynameisverylong.butitisstillpossibletocreate.itwithin256characeters.aslongasyouusedots --from-literal=foo=bar
configmap "mynameisverylong.butitisstillpossibletocreate.itwithin256characeters.aslongasyouusedots" created

echo mynameisverylong.butitisstillpossibletocreate.itwithin256characeters.aslongasyouusedots | wc -c
88
```

This configmap name is 88 characters long. So it might be that we need to update the code in api-server and/or agent that handles/trims these names, because the kubernetes configmap name does not seem to be the limitation.

**Comment by grs** [comment]
You are right! I incorrectly assumed the 422 was a result of name length. It turns out it was due to there being a . followed immediately by a - which is invalid. I'll update the agent code to prevent that.

So I guess for configmap names we can allow the full string to be up to 253 chars?

**Comment by lulf** [comment]
I think so.  The way we autogenerate the name should perhaps become `addressspace.sanitizedaddress.uuid`?

We should have a systemtest that verifies that each of address space and address can be up to 64 characters long.
