### ISSUE TITLE
sending requests with small batches of addresses cause restart of api-server

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#1319]
**Description:**
Sending small batches of addresses (with 10 addresses in AddressList) cause restart of api-server after 150 requests.
There are no async operations, there is wait for response from the api server.
Environment: standard address space with self defined plan for address space and for addresses

reproducible via automated test in **address-batches** branch: (test is disabled in this branch)
`make MULTITENANT=true OPENSHIFT_PROJECT="myproject"  SYSTEMTEST_ARGS='PlansMarathonTest#testHighLoadAddressesInBatches' SYSTEMTESTS_PROFILE="systemtests-marathon" systemtests`

**Comment by k-wall** [comment]
I'm able to reproduce something that matches the symptoms of this failure on my machine.   Looking openshift events I see the health check fail and that cause the restart of the api-server's pod (failure point is always around 2200 addresses).    If I relax the health-check, the 3900 addresses are successfully created.

I don't see an obvious problem in the code that accounts for the health check response not being sent in a timely fashion.  Vertx uses a thread pool to serve the incoming HTTP requests and this pool is adequately sized give the quantity of traffic.    I've also eliminated GC as an cause of the problem.  I am coming to the conclusion that it is simple contention elsewhere on the laptop which is allowing the failure.

**Comment by k-wall** [comment]
Correcting some of above, the algorithm for the creation of many addresses was unnecessarily resource intensive. A request creating n addresses would retrieve the list of all addresses n times, so creating addresses get slower for the more addresses defined.  #2013 avoids some of the waste.
