### ISSUE TITLE
Agent: Improve memory usage

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1324]
Doing a re-test of #1084, the memory consumption of the Agent component in 0.20.0 still seems relatively high:

With the default memory setting of 512Mb for the `agent` container in the `admin` pod, there are OOMKilled errors for the agent container after having created 8000 address ConfigMaps (half anycast, half brokered):
````
2018-06-04 13:39:50.947 [Thread-4] INFO  AddressController:109 - Total: 7589, Active: 5352, Configuring: 1942, Pending: 295, Terminating: 0, Failed: 0
2018-06-04 13:39:56.451 [Thread-4] INFO  AddressController:109 - Total: 7724, Active: 5352, Configuring: 2126, Pending: 246, Terminating: 0, Failed: 0
2018-06-04 13:40:02.651 [Thread-4] INFO  AddressController:109 - Total: 7897, Active: 5352, Configuring: 2237, Pending: 308, Terminating: 0, Failed: 0
2018-06-04 13:40:08.881 [Thread-4] INFO  AddressController:109 - Total: 8010, Active: 5352, Configuring: 2372, Pending: 286, Terminating: 0, Failed: 0
2018-06-04 13:40:14.574 [Thread-4] INFO  AddressController:109 - Total: 8010, Active: 5352, Configuring: 2545, Pending: 113, Terminating: 0, Failed: 0
2018-06-04 13:40:18.358 [Thread-4] INFO  AddressController:109 - Total: 8010, Active: 5352, Configuring: 2658, Pending: 0, Terminating: 0, Failed: 0
````
````
    Image:          docker.io/bsinno/iothub-enmasse-agent:0.20.0_2018-06-01_83_BOSCH
    Image ID:       docker-pullable://bsinno/iothub-enmasse-agent@sha256:140282fddc9721ec5d3536052ef6111d292d0d0e06becb8e79302888e8deeb56
    Ports:          8888/TCP, 8080/TCP, 56720/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Mon, 04 Jun 2018 15:40:16 +0200
      Finished:     Mon, 04 Jun 2018 15:40:56 +0200
````

_With more memory:_
With a memory setting of 1 GB, an OOMKilled error occurred with 12000 addresses:
````
2018-06-04 13:51:57.523 [Thread-4] INFO  AddressController:109 - Total: 12010, Active: 8010, Configuring: 4000, Pending: 0, Terminating: 0, Failed: 0
````

````
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Mon, 04 Jun 2018 15:49:28 +0200
      Finished:     Mon, 04 Jun 2018 15:52:11 +0200
    Ready:          True
    Restart Count:  1
    Limits:
      memory:  1Gi
````

----
For another test, the memory setting of the agent container has been increased to 1500Mb.
Adding 12000 addresses shows memory of the `admin` pod to reach 1200Mb (of course this also includes the "standard controller" container).
````
2018-06-05 14:35:47.646 [Thread-4] INFO  AddressController:109 - Total: 10, Active: 10, Configuring: 0, Pending: 0, Terminating: 0, Failed: 0
...
2018-06-05 14:56:24.877 [Thread-4] INFO  AddressController:109 - Total: 12010, Active: 12010, Configuring: 0, Pending: 0, Terminating: 0, Failed: 0
````
`kubectl top pod`
````
         NAME                                            CPU(cores)   MEMORY(bytes) 
16:35:48 admin-68ff74466b-4s9c9                          10m          211Mi           
..
16:47:02 admin-68ff74466b-4s9c9                          1118m        930Mi           
16:47:07 admin-68ff74466b-4s9c9                          1241m        998Mi           
16:48:01 admin-68ff74466b-4s9c9                          1241m        998Mi           
16:48:06 admin-68ff74466b-4s9c9                          1055m        1090Mi          
16:49:09 admin-68ff74466b-4s9c9                          1096m        1050Mi          
16:50:07 admin-68ff74466b-4s9c9                          1088m        1140Mi          
16:51:05 admin-68ff74466b-4s9c9                          1088m        1140Mi          
16:52:03 admin-68ff74466b-4s9c9                          1071m        1168Mi          
16:53:00 admin-68ff74466b-4s9c9                          1090m        1012Mi          
16:54:03 admin-68ff74466b-4s9c9                          1112m        1226Mi                  
16:56:04 admin-68ff74466b-4s9c9                          1138m        1037Mi    
````

**Comment by calohmn** [comment]
Here are some logs from a test creating 8000 addresses: 
[8000_Addresses.zip](https://github.com/EnMasseProject/enmasse/files/2075912/8000_Addresses.zip)

In the agent logs, there is output of the memory usage. Excerpts:
Max RSS: 714MB
14:17:36.801Z {"rss":749690880,"heapTotal":122736640,"heapUsed":48894664,"external":2707772}

Max HeapUsed: 60MB
14:19:13.029Z {"rss":452190208,"heapTotal":140562432,"heapUsed":63746568,"external":80537514}

Max External: 184MB
14:20:11.568Z {"rss":460722176,"heapTotal":129028096,"heapUsed":55137584,"external":193074715}

Maybe using a newer NodeJS version could also help (?). Currently v6.14.0 is used.

**Comment by kornys** [comment]
I agree with @calohmn, I saw some comparison and nodejs8 has better performance (about 20%) then nodejs6

**Comment by grs** [comment]
I'll have a look at the latest issue. Earlier I was able to create 10000 addresses without changing memory settings so it may just be that one of the more recent changes has had an unexpected hit on memory.

Upgrading the node version seems reasonable, but I think the memory use as described sounds like something to fix in the code anyway.

**Comment by grs** [comment]
With latest master I can create 12000 address (half pooled queues, half anycast) without any crashes using the default memory limits (512Mb). Are you still seeing issues?

**Comment by grs** [comment]
Ulf pointed out that with the switch to maven, the agent is now using a node version pulled by maven. That could have alleviated the issue.

**Comment by calohmn** [comment]
@grs good point, I see there's Node v8.11.2 being used now. I'll repeat the test.
