### ISSUE TITLE
Creation of sharded topics and queue fails to complete

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1327]
On master, there is a regression at a643e5ba833. If I create a sharded topic or queue in the EnMasse console the operation never completes.  The spinner keeps spinning indefinitely.

Inspecting the configmap with `oc get configmap default.mytopic-89bf0ff5-e38c-dd4c-b695-6c0f1394a949 -o yaml` I see the status sticks at "Confguring".

```
apiVersion: v1
data:
  config.json: '{"apiVersion":"enmasse.io/v1alpha1","kind":"Address","metadata":{"name":"default.myopic-89bf0ff5-e38c-dd4c-b695-6c0f1394a949","namespace":"myproject","addressSpace":"default","uid":"de56148f-6965-11e8-872f-aafcf4b0d323","selfLink":"/apis/enmasse.io/v1alpha1/namespaces/myproject/addressspaces/default","creationTimestamp":"2018-06-06T08:44:47Z","resourceVersion":"3242"},"spec":{"type":"topic","plan":"sharded-topic","address":"myopic"},"status":{"isReady":false,"phase":"Configuring","messages":["Address
    myopic is missing connection from broker"]}}'
kind: ConfigMap
```

Commits before a643e5ba833 and did not show the issue.

I see the same issue on Mac OS X (Docker version 17.09.1-ce, build 19e2cf6) and Fedora 28 (Docker version 18.03.1-ce)

**Comment by grs** [comment]
PR #1346 fixes this. However I was only able to reproduce a problem with sharded topics; sharded queues seem to work ok for me. The PR mentioned re-enables the tests for both queue and topic and these seem to all pass.

**Comment by k-wall** [comment]
@grs I agree the problem did only affect sharded topics.  sharded queue were fine.  I guess that may openshift environment had stale data.
