### ISSUE TITLE
Move systemtest playbooks into systemtests

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1342]
The new playbook structure involves having a split between inventory files and playbooks.

Playbooks located in `templates/install/ansible/playbooks/openshift` and example inventory files in `templates/install/ansible/inventory`. 

Right now the systemtest playbooks and roles are part of the release bundle, which I think they should not be.

I propose that instead the systemtest roles and playbooks are moved into the 'systemtests` folder, and that the playbooks for installing 'enmasse' and 'systemtests' are run independently. This way we can verify that the 'install' playbook is working correctly.

There should also be a 'systemtest.inventory' file used when deploying the install playbook. I.e. I'm using the following locally:

```
[enmasse]
localhost ansible_connection=local

[enmasse:vars]
namespace=enmasseci
multitenant=True
enable_rbac=True
api_server=True
register_api_server=False
service_catalog=True
secure_api_server=False
keycloak_admin_password=admin
authentication_services=["none", "standard"]

```

**Comment by kornys** [comment]
@lulf  I agree
