### ISSUE TITLE
Agent build dependent on installed npm

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1394]
When building the agent without `npm` installed, there is an error (`/bin/sh: 1: npm: not found`):
````
make FULL_BUILD=true -C agent 
make[1]: Entering directory '/home/jenkins/workspace/enmasse/agent'
Makefile:8: warning: overriding recipe for target 'clean'
..//Makefile.common:24: warning: ignoring old recipe for target 'clean'
mkdir -p build
MOCHA_FILE=build/test-results/test/TEST-agent.xml MOCHA_ARGS="" npm run test
/bin/sh: 1: npm: not found
..//Makefile.common:35: recipe for target 'npm_test' failed
make[1]: *** [npm_test] Error 127
make[1]: Leaving directory '/home/jenkins/workspace/enmasse/agent'
Makefile:45: recipe for target 'agent' failed
make: *** [agent] Error 2
````
The prerequisites don't list `node` anymore, though.

**Comment by calohmn** [comment]
It looks to me as if the node/npm installed via maven isn't used here because the `PATH` variable doesn't point to it.

Therefore a simple fix would be adding the following near the top of `Makefile.common`:
````
PATH := $(abspath $(TOPDIR))/agent/build/node:$(PATH)
````

**Comment by lulf** [comment]
@calohmn I think this should be in agent/Makefile

Alternatively, we could fix so the test target runs the mvn test instead, which automatically use the downloaded npm version.

**Comment by lulf** [comment]
Fixed on master
