### ISSUE TITLE
Subsequent SUBSCRIBE control packets ignored

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1423]
The MQTT specification defines (MQTT-3.8.4-4) that a series of SUBSCRIBE control packets has the same meaning as a single SUBSCRIBE control packet listing the same set of filters.

If an MQTT sends a series of SUBSCRIBE control packets, current only the first control packet has any effect.   The others are seemingly ignored.  The messages matching the first subscription filter arrive and others are ignored.  If the same set of subscription filters is listed within a single SUBSCRIBE control packet, the problem does not materialised.

Assuming a topic address "foo" exists:

Fails:
```
client.subscribe([("foo/baz1", 1)])
client.subscribe([("foo/baz2", 2)]) # messages matching this filter do not arrive
```
Works:
```client.subscribe([("foo/baz1", 1), ("foo/baz2", 1)])```

**Comment by grs** [comment]
Is the fact that the addresses share a root relevant? E.g. does the following work:

```
client.subscribe([("foo")])
client.subscribe([("bar")])
```

**Comment by k-wall** [comment]
Gordon, yes you are correct.  If the subscribes refer to separate topic roots, the problem does not manifest.
