### ISSUE TITLE
Dispatch Router sporadically goes into a state where TLS connections to the auth service fail

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1443]
Whilst running performance tests against Enmasse, we periodically see a problem where  Dispatch Router goes into a state where fails to form TLS connections to the authservice.  When this occurs, the router needs to be restarted to restore service.   There does not seem to be a pattern to when the issue occurs, but in all cases where it has been seen, the test case included tens or hundreds of concurrently formed connections.

The following message is written to the log:

```
2018-07-06 10:38:45.543519 +0000 AUTHSERVICE (warning) Cannot initialise SSL
```

Unfortunately turning up the router logging (using the following command) reveal no more useful information.   This [Proton improvement JIRA](https://issues.apache.org/jira/browse/PROTON-1886?) was raised to include the diagnostics from OpenSSL.

```
echo '{"enable":"trace+"}' | PN_TRACE_FRM=1 qdmanage update -b amqps://0.0.0.0:55671 --type=log --name=log/SERVER --stdin --sasl-mechanisms EXTERNAL --ssl-trustfile /etc/enmasse-certs/ca.crt --ssl-disable-peer-name-verify --ssl-certificate /etc/enmasse-certs/tls.crt --ssl-key /etc/enmasse-certs/tls.key
```

**Comment by k-wall** [comment]
Issue raised against Qpid Dispatch Router: https://issues.apache.org/jira/browse/DISPATCH-1086

**Comment by calohmn** [comment]
We got this as well. Log output has been appended to [DISPATCH-1086](https://issues.apache.org/jira/browse/DISPATCH-1086).

**Comment by grs** [comment]
Fixed by https://github.com/EnMasseProject/enmasse/pull/1659
