### ISSUE TITLE
EnMasse console display unexpectedly high number of senders when number of dispatch routers scaled above 1 

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1444]
I noticed when the number of dispatch routers were scaled above 1 that the number of “senders” reported by the EnMasse console could be too high (from the end-user's perspective).  It was as if the “senders” statistic was somehow taking into account the internal links within the router mesh.  For example,  for a test with 200 sender workers and 200 receiver workers (each with a separate connection), the console would report exactly 200 receivers but the nunver of senders reported as a value much higher than 200.  This seems counterintuitive to the user.

**Comment by grs** [comment]
@k-wall I can't seem to reproduce this. I altered the plan for sharded queue to require 4 routers (and 2 brokers), created an instance of such a queue then created many senders against it. The sender count in the console is correct.

**Comment by grs** [comment]
Test of sharded topic also shows correct number of senders in my test (with plan set to require 3 routers and 2 brokers per topic).

**Comment by k-wall** [comment]
Agreed, I have retested and I can not longer reproduce the issue.
