### ISSUE TITLE
Make "address-model-lib" maven module publicly available

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1454]
When invoking the EnMasse API server from Java code, it is helpful to use the EnMasse "address-model-lib" module with the Java object model for the Address and AddressSpace objects.

Therefore it would be good to have the module available in a public maven repository.

**Comment by lulf** [comment]
I’m a little sceptic to introduce this. 
We would suddenly get a public java library and API to support and need to concern ourselves with API compatibility, versioning and release management, and the java interfaces I think would have to be more carefully designed than what is there.

We maintain a swagger/openapi spec for the REST API that can be used by users to generate client code (for multiple language if needed) + documentation. 

Would it be sufficient for your needs?

**Comment by calohmn** [comment]
@lulf I get your concerns and yes, we'll go the way of using the approach via the openapi spec, then.
