### ISSUE TITLE
system-tests: create new webconsole test for address type "subscription"

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#1474]
Create new web console test for durable subscription. This test should create and delete address via web console. New test will be very similar to following test: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java#L21

**Comment by grs** [comment]
Only wrinkle is that creating a subscription type address requires choosing a topic that the subscription is on.

**Comment by RH-sdavey** [comment]
https://github.com/EnMasseProject/enmasse/commit/1705f69e72a2b0b4409879fb66552395bc43ab66
