### ISSUE TITLE
Broker,Router don't scale when config maps are changed

### ISSUE THREAD

**Issue by robshelly** [EnMasseProject/enmasse#1487]
When _config maps_ are changed to specify a different number of brokers and/or routers they should automatically scale accordingly. However, they don't.

The following scenarios do not scare correctly:

* when changing _config maps_ for addresses brokers do not scale
* when changing _config maps_ for addresses routes scale but inconsistently, sometimes leaving incorrect number of routers
* when addresses, routers do not scale back to to correct number defined by address-space _config map_

**Comment by k-wall** [comment]
I think the introduction of addressspace plans and address plans has resolved this issue.
