### ISSUE TITLE
Custom resources on OpenShift 3.10 does not work without cluster-admin rights

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1493]
With OpenShift 3.10, with mTLS enabled between API server and OpenShift master, users are not allowed to create address spaces even when being part of the enmasse.io:tenant-edit role.

The reason is that the subject access review done by the SubjectAccessReview must include a 'group' field in the JSON payload to work, so it is easy to fix.

**Comment by kornys** [comment]
@lulf so I should wait with migration to 3.10 in jenkins, right?

**Comment by lulf** [comment]
@kornys No it won't affect systemtests, though it would be nice if we could try to create address spaces as users without cluster-admin privileges.
