### ISSUE TITLE
Possible to create an address of any type and any plan in webgui

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1498]
Its possible to 'start creating' an address of any type with any plan through webgui.
When creating a a new address, modal window appears, if you select any option ( eg: anycast ), provide a name (eg: any_to_multi) and click next,  click next to choose standard-anycast. 
Now on the 3rd screen, if you click directly on the number 1 icon, you can choose any other option, (eg: multicast) and then click directly on the number 3 icon. You are taken to the confirmation page with the following info,

> Name: any_to_multi
> Type: multicast
> Plan: standard-anycast

The address is never actually created, but the webui shows a spinning progress icon, that never ends, which seems to intermittently 'disable' the create button also,even after deleting the nonsensical address, and even after browser refresh ( sometimes the button wont work, other times it will and the next address ( even a valid one ) will be stuck on the looping icon ) . Also, API server and oc command "oc get -o json addresses"  show following output,

`            "spec": {
                "address": "queue_to_multi",
                "plan": "pooled-queue",
                "type": "multicast"
            },
            "status": {
                "isReady": false,
                "phase": "Pending"
            }
        },
`

While such behaviour is probably not so serious, I believe it can be avoided, when clicking on number 1 icon, the preselected choices of number 2 can be flushed for eg.

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.
