### ISSUE TITLE
Topic with long name causes host server to be unresponsive

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1547]
When creating a topic in console with an incredibly long name, 
`topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname-topicwithanincrediblylongname- `

the topic is never created, 
also, any previous topics that were successfully created go to a non-ready state. 
`            "status": {
                "isReady": false,
                "messages": [
                    "Address goodtopic is missing active linkRoute (active in dirs: [])",
                    "Address goodtopic is missing linkRoutes on qdrouterd-0"
                ],
                "phase": "Active"
            }
`

the enmasse deployment is not responsive to any user interaction, with the following output from openshift 

`   Failed to list appliedclusterresourcequotas/quota.openshift.io/v1 (status -1)
Failed to list resourcequotas/v1 (status -1)
`

and any ssh connection to the host becomes so slow its rendered practically unusable. 
top command shows that 'qdrouterd' and 'openshift' processes are each using 150+ % of cpu and ~50% mem each

While the name is unfeasibly long and probably would never be considered in real world usage, the consequences are dramatic.

Steps to reproduce:
1. deploy new Enmasse standard address space
2. create new topic "goodtopic" and wait to be in ready state
3. create new topic "goodtopic2" and wait to be in ready state
4. create new topic with name given at the beginning of this issue
5. Observe as the "goodtopic(2)" become in an unready state, error output from openshift and ssh connection to host slows down dramatically. 

Workaround: delete topic with long name, and after a few minutes all goes back to green.

**Comment by RH-sdavey** [comment]
Workaround worked for me once, and wont work again on subsequent attempts to reproduce. 

Upon further investigation, there is a lot of weird behavior when there are multiple "-"s in the address name. Tested with queues topics and subscribers, all show similar behavior as above.

**Comment by grs** [comment]
I can reproduce the topic not being created (it fails with a 422 Unprocessable Entity undefined on the agent when trying to create the config map, but this is not signalled back in anyway). Simple fix for that is probably just to restrict the length of the input: https://github.com/EnMasseProject/enmasse/pull/1572

I can't see the subsequent instability you mentioned though.
