### ISSUE TITLE
Some brokered addresses not available after broker/agent restart

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1566]
Using EnMasse 0.21.2:
We have restarted the admin pod and shortly after restarted the broker pod.
After that, several brokered addresses were not available - in the EnMasse console they were shown with the "in progress" icon.

This didn't get fixed automatically - only a restart of the admin pod resolved the situation.

This has happened a few times before (we restart these pods on a daily basis). 

We've assembled some logs files (see [logs_180829.zip](https://github.com/EnMasseProject/enmasse/files/2337227/logs_180829.zip)) (unfortunately no qdstat or broker stats for that).

Some observations:
- there are 362 brokered addresses in total ("event/*")
- concerning timing: it looks like while the agent is starting up, it fetches broker statistics while the broker itself is still starting up - probably not getting the eventual number of queues
- as part of the agent restart to fix the situation, the agent pod log (`agent__afterRestart.log`) contains 73 "Creating queue" entries. So these queues must have been missing before - but the broker log shows no indication of that.
- standard-controller logs show nothing special (always the same "Total: 1086, Active: 1086" output)

**Comment by lulf** [comment]
By not available, do you mean that you can't send/recv to them or that they are not active in the console?

**Comment by grs** [comment]
Are the addresses all 'pooled' (rather than 'sharded')?

**Comment by grs** [comment]
also, if pooled, is there one broker or more than one? How do you restart the pods (e.g. delete the pod, or scale down and up again)?

**Comment by calohmn** [comment]
Yes, addresses are of type pooled queue. There is only one broker. 
Restart is done as part of a "kops rolling-update cluster".

**Comment by grs** [comment]
As yet I have not managed to reproduce this. However looking at the logs, of the 73 queues created by the agent after restart, 69 were attempted before the restart but failed, 49 due to 'Binding already exists LocalQueueBinding' 20 due to 'Queue xxx already exists'. For those that failed with the binding error, there are (at least) two concurrent entries in the broker log indicating queue creation. My hunch is that there are two concurrent attempts to create the queue and associated address, and one of them fails. However this doesn't explain why the queue then needs to be recreated later - seemingly it gets deleted for some reason in between, possibly due to the auto-delete behaviour that appears to be enabled by default. I'll continue to try to reproduce, and perhaps experiment with a patch that turns that auto-delete off.

**Comment by grs** [comment]
One other question: did you restart the router also? Which is the router log for?

(If you get another occurrence before we have resolved this, can you save all logs from both previous and restarted pods, just to help give a fuller picture).

**Comment by calohmn** [comment]
No, we didn't restart the router. We have only restarted the "admin" pod.

**Comment by calohmn** [comment]
This morning, the error has occurred again.
I didn't get to analyze it at that point, but we have again log output and additionally some router stats.
See [logs_180905.zip](https://github.com/EnMasseProject/enmasse/files/2352966/logs_180905.zip).

One finding in the router stats is, that there are no autolinks at all at the point of the error.

**Comment by grs** [comment]
What I meant was that the agent_20180905_102332.log seems to be just a little bit more output from the same instance as BEFORE_ADMIN_RESTART_agent__20180905_084309.log, the first 976 lines are identical, but the former has a further 108 lines. It does not look like agent_20180905_102332.log spans a restart.

The first portion - i.e. that common to BEFORE_ADMIN_RESTART_agent_... and agent_... - seems to indicate all but 4 (2 in each direction) of the autolinks shown in the qdstats from after error resolution were created, The second portion - i.e. that only in the agent_... - indicates 'autolinks up to date on Router.qdrouterd-f4f6f5cd8-xk7tg', but subsequently sees two new queue addresses created - event/t94f371466e344976b4def27abce26b2f and event/t025c0bddf559422982679f634629c4cc - for which it then creates autolinks.

**Comment by calohmn** [comment]
Yes, sorry, had a closer look now.
We had a misunderstanding here and all logs in the previous zip were actually from after the admin restart.
I've tried to re-assemble the agent log from before the restart from kibana. Here it is: 
[agent_logs__180905.zip](https://github.com/EnMasseProject/enmasse/files/2357218/agent_logs__180905.zip)

**Comment by grs** [comment]
From examining these logs it looks like there is some issue between the agent and the router. The agent begins creating addresses, but it doesn't complete. I have added some more logging and error handling.

**Comment by calohmn** [comment]
The issue occurred again last week.
All new addresses created after a certain point didn't get properly registered.
Example output when doing an address check:
````
2018-10-02 12:45:56.590 - isAddressReady(telemetry/td5b0d65f52e2402d82ca3217d6630a5c): not ready, phase: Configuring, messages: Address telemetry/td5b0d65f52e2402d82ca3217d6630a5c not found on qdrouterd-0
2018-10-02 12:45:56.590 - isAddressReady(event/td5b0d65f52e2402d82ca3217d6630a5c): not ready, phase: Configuring, messages: Address event/td5b0d65f52e2402d82ca3217d6630a5c is missing autoLinks on qdrouterd-0, Address event/td5b0d65f52e2402d82ca3217d6630a5c not found on qdrouterd-0, Address event/td5b0d65f52e2402d82ca3217d6630a5c is missing active autoLink (active in dirs: [])
2018-10-02 12:45:56.590 - isAddressReady(control/td5b0d65f52e2402d82ca3217d6630a5c): not ready, phase: Configuring, messages: Address control/td5b0d65f52e2402d82ca3217d6630a5c not found on qdrouterd-0
````
Noticable is this output in the agent container before the creation of the not-ready addresses:
````
2018-10-01T05:34:31.721Z agent info addresses_defined: modified event/t2b91220a481343ee9b41b2ccb2fce3a0, event/t31c83e7c4efa4b818fc627cf65c716f2, event/t4fb14ffa9b234329822e255b70074049, event/t5c5f66b05e9a4fa8a4b1bf1ff748b7dd, event/t8d734bceb4894736b1d35ef13740115a and 14 more
2018-10-01T05:35:05.949Z agent info [undefined] aborting pending requests: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): disconnected
    at emitPendingUnhandledRejections (internal/process/promises.js:69:27)
    at process._tickCallback (internal/process/next_tick.js:110:7)
2018-10-01T05:35:06.066Z agent info [qdrouterd-0] router ready
2018-10-01T05:35:08.760Z agent info routers changed: amqp:/_topo/0/qdrouterd-0/$management
````
Logs: [logs_181002.zip](https://github.com/EnMasseProject/enmasse/files/2457779/logs_181002.zip) - see the `_info.txt` inside.

**Comment by grs** [comment]
@calohmn what version was this last incident on?

**Comment by calohmn** [comment]
@grs the incident above was with 0.22.0.
This morning, there was again the error, this time with 0.23.0. Again there was a disconnect in the agent logs:
````
2018-10-12T05:33:43.777Z agent info addresses_defined: modified event/t00de324a5eaa479fae30f4f1dcd6a6d7, event/t00e19a4d599a452da97696c1bdc65106, event/t00f0ebe4c9b44028a3afcaad57609f27, event/t025c0bddf559422982679f634629c4cc, event/t05ac352a0d74498f9ed117839b7b1bef and 265 more
2018-10-12T05:33:45.291Z agent info addresses_defined: modified event/t032a9b74addd48f584abbc2a210b5f5e, event/t06149907b8134ddf8f594344e0ea8e39, event/t0c3221c06e214225930c191979ac4d17, event/t0c40ec981453440ab9ac8c0bf011cf89, event/t0da229523c7e45c9888a6023a6399437 and 76 more
2018-10-12T05:33:47.550Z agent info addresses_defined: modified event/t01a9cf8d1c5b453fb933a0a3fe622302, event/t046839505ce64d7f8b6fe903c5759561, event/t064b83dccf344fdda60eed93d886471f, event/t06c704442a164f7bae6e6f1cf762049e, event/t07533677d5ca453897986d8c085b300c and 107 more
2018-10-12T05:33:52.256Z agent info [undefined] aborting pending requests: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
Failed to retrieve router stats: disconnected
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): disconnected
    at emitPendingUnhandledRejections (internal/process/promises.js:69:27)
    at process._tickCallback (internal/process/next_tick.js:110:7)
2018-10-12T05:33:52.387Z agent info [qdrouterd-default-0] router ready
````
I can merge your logging improvements above to get more info next time.

**Comment by k-wall** [comment]
@calohmn  next time you see an occurrence of this, can you check the stat of the routers using qdstat as I have done [here](https://github.com/EnMasseProject/enmasse/issues/1810#issuecomment-430959432).   I am interested if you see non-zero values in the `psdrop` column for the links corresponding to the agent's connections to the router(s).

**Comment by calohmn** [comment]
@k-wall Concerning the incident with 0.22.0 [above](https://github.com/EnMasseProject/enmasse/issues/1566#issuecomment-427973652), there are qdstat statistics in the attached zip file.
Here are the relevant parts:
````
Connections
  id      host                  container                                                  role             dir  security                              authentication                               tenant
  ==========================================================================================================================================================================================================
  1       ragent:5671           f901b433-ebcf-9d45-af67-3dadc6ccca99                       normal           out  TLSv1.2(ECDHE-RSA-AES128-GCM-SHA256)  x.509                                        
````
````
Router Links
  type      dir  conn id  id     peer  class   addr                                         phs  cap  undel  unsett  del    presett  psdrop  acc    rej  rel  mod  admin    oper
  ================================================================================================================================================================================
  endpoint  in   1        6                                                                      250  0      0       2099   0        0       2099   0    0    0    enabled  up
  endpoint  out  1        7            local   temp.Zq+h+qFxC+pOKo5                              250  0      0       1849   2099     250     0      0    0    0    enabled  up
````
So, `psdrop` is indeed 250.

Concerning the latest occurrence of the issue with 0.23.0, that is also the case (see [qdstat_181015.zip](https://github.com/EnMasseProject/enmasse/files/2491763/qdstat_181015.zip)).
