### ISSUE TITLE
'Asian' characters in console for {any,multi}cast address

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1568]
Create either anycast or multicast address in console, 
send messages to this address using any clients, 
Under the address its possible for user to see "incoming links" and "outgoing links"
click any of the column headers ( eg: Delivery Rate )
There is an asian character, presumably meant to be be for "ascending order"
Click the same column header again
There is an asian character, presumably meant to be be for "descending order"
repeat for all column headers under these address types

![screenshot](https://user-images.githubusercontent.com/32485509/44872437-d21caf80-ac95-11e8-991d-db34a674c109.jpg)

*same seen with queues with clients attached 
![screenshot_q](https://user-images.githubusercontent.com/32485509/44874051-36da0900-ac9a-11e8-9df6-ce3afe218f7a.png)

**Comment by RH-sdavey** [comment]
![screenshot](https://user-images.githubusercontent.com/32485509/44873650-12316180-ac99-11e8-9d11-e8421e535400.png)

**Comment by RH-sdavey** [comment]
Tried many many times to reproduce, cannot be done. Putting it down to a one off anomaly in patternfly / html / local browser.  Issue closed for now, and if I see this again, will re-open.

**Comment by RH-sdavey** [comment]
Reproducer! Im sure I tried this before, with no success but its reproducing 100% now so... issue re-opened. 
* Start enmasse instance and open console
* Connect  cli-proton-python-sender client(s) and start sending messages to a queue (  ) using following example:
`cli-proton-python-sender --timeout 2 --broker amqps://user-015358a9-352d-4bda-9d7a-ab5806155ce0:Jt6efM7H8lFCUY%2FInjgtSBigyR6oquT6dV55XaAIRwY%3D@messaging-myproject-connection-test-addr.<<ip_address_here>>.nip.io:443/new_queue --log-msgs dict --count 100`
* Check connections tab and address details. 
![screenshot_asian1](https://user-images.githubusercontent.com/32485509/45298235-36e2d000-b508-11e8-8a5d-8948cafc3a08.png)

After discussion with kwall, it seems to be a problem with the way the browser is interpreting the charset of console page, the charset is being set in the html header as 'utf-8' but after trying to set this manually with a browser extension ( to utf-8) the problem disappears completely. (In chrome )
With firefox, the same "kanji symbol" is seen, but just for a brief flash before correcting itself to a down arrow, as expected.

**Comment by grs** [comment]
Just fyi, I can't seem to reproduce it.
