### ISSUE TITLE
Sending x messages in  to queue, show x messages out instantly in console

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1571]
When sending x amount  of messages to a newly created queue, **with no subscribers attached**, 
the console shows value of 'x messages in' but also 'x messages out' , this does not seem correct to me, and I believe would cause confusion with a new enmasse user. 

 
![screenshot3](https://user-images.githubusercontent.com/32485509/44906687-e86a5000-ad15-11e8-869e-2b20a12a573d.png)
![screenshot4](https://user-images.githubusercontent.com/32485509/44906701-f3bd7b80-ad15-11e8-8abd-21139d73c561.png)

**Comment by grs** [comment]
Should be fixed by https://github.com/EnMasseProject/enmasse/pull/1573

**Comment by RH-sdavey** [comment]
#1537 approved
