### ISSUE TITLE
[console and router auth-plugin] Username is not showing for an authenticated connections

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1574]
[standard address space with standard authservice]
[console] 
In connections tab, there is an option to filter by user, however in the connections table there is no column for user, meaning that any filtering done for any usernames will always return no results, even when filtering for the username provided in an authenticated connection ( provided by creating a binding, the username is prefixed with "user-" ) 

[router auth-plugin]
after discussion with gsim, and observing outputs from following commands:
oc exec -n myproject-myspace -it qdrouterd-0 -- qdstat -c
oc describe pod/qdrouterd-0 -n myproject-myspace
 oc exec -n myproject-myspace -it qdrouterd-0 -- qdmanage query --type connection
gsim suspects this could be a bug in router auth-plugin thats not exposing the username for authenticated connections.

**Comment by RH-sdavey** [comment]
#1576 approved

**Comment by grs** [comment]
@RH-sdavey are you saying the issue is not fixed?

**Comment by RH-sdavey** [comment]
Sorry @grs , wrong tab!
