### ISSUE TITLE
[console] Address name is not created when starting or ending with .

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1588]
When creating any type of address in console, 
if the name begins **or** ends with .  ( fullstop / period ) then the address creation wizard finishes with no error output, but the address creation is seemingly never begun.
No address is created and output from `oc get -o json addresses` shows no address created either

**Comment by RH-sdavey** [comment]
also noticed, just for topic addresses, if the topic name ends in \#  then the topic never gets created, stuck in a pending state. all other address type ending in \# are created fine.

**Comment by vbusch** [comment]
Added a PR, to keep the 'next' button disabled, until the name is valid.  https://github.com/EnMasseProject/enmasse/pull/1720

**Comment by RH-sdavey** [comment]
Certain chars ( including . ) are no longer allowed and next button is disabled if they are attempted to be used. Issue can be closed
