### ISSUE TITLE
Console does not behave reasonably if address space is deleted

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1595]
If I create a address space (brokered or standard) and then attach a browser to the console, then delete the address space, there is not visual indication to the user that the address space has gone.  Furthermore, the buttons in the console remain usable (that is, I can click between connections and addresses tabs), but there is still no indication to user that the address space is gone.

If I then re-create the address space, the console remains in the same non functional state. The user needs to know to logout and login again.

If I check the browser's console, I see messages like:

```
rhea.js:9323 WebSocket connection to 'wss://console-myproject-brokered.127.0.0.1.nip.io/websocket' failed: Error in connection establishment: net::ERR_NETWORK_CHANGED
connect @ rhea.js:9323
Connection._connect @ rhea.js:5307
Connection.reconnect @ rhea.js:5300
rhea.js:5531 [connection-1] error: [object Event]

```

**Comment by k-wall** [comment]
My ideas for this:

* on the server side, use a signal handler to gracefully close the websocket connection when the agent is closed.   This should allow the client to discover the loss it peer sooner.
* on the client side, use a rhea disconnect handler to trigger the display of a message informing the user that the connection has been lost.  Unfortunately, the client is not going to be able to distinguish between an address space being deleted from a simple agent pod restart, so the message will have to be worded to cover both cases.

**Comment by lulf** [comment]
@k-wall I think detecting that address space is deleted or pod restart would is hard without tapping into the “global” state. IMO “Client disconnected” or “Connection to server lost” would be fine and a sufficient improvement for the lifetime of the per address space console.
