### ISSUE TITLE
[console] message out count, and stored count decrements incorrectly for queues

### ISSUE THREAD

**Issue by vbusch** [EnMasseProject/enmasse#1609]
When receiving 50 stored messages, Messages Out decreased by 91.

Steps to reproduce:
A) start receiver:
./simple_recv.py -a "amqps://$(oc get route -o jsonpath='{.spec.host}' messaging):443/thequeue" -m 50
B) send 50 messages:
./simple_send.py -a "amqps://$(oc get route -o jsonpath='{.spec.host}' messaging):443/thequeue" -m 50
C) Send 50 messages 3 more times 
./simple_send.py -a "amqps://$(oc get route -o jsonpath='{.spec.host}' messaging):443/thequeue" -m 50
./simple_send.py -a "amqps://$(oc get route -o jsonpath='{.spec.host}' messaging):443/thequeue" -m 50
./simple_send.py -a "amqps://$(oc get route -o jsonpath='{.spec.host}' messaging):443/thequeue" -m 50
 D) Receive 50 messages
./simple_recv.py -a "amqps://$(oc get route -o jsonpath='{.spec.host}' messaging):443/thequeue" -m 50
  Note: received 50 messages in random order, Messages Out increased by 151, Messages Stored decreased by 91
E) Receive 50 messages
./simple_recv.py -a "amqps://$(oc get route -o jsonpath='{.spec.host}' messaging):443/thequeue" -m 50 
  Note: received 50 messages in random order, Messages Out increased by 51, Stored decreased by 51

**Message Counts after each step**
Step | Messages In | Messages Out | Stored
---- | ----------- | ------------ | ------
B | 50 | 50 | 0
C | 200 | 50 | 150
D | 200 | **191** | **51**
E |200 | **242** | **0**

![queue_count](https://user-images.githubusercontent.com/1995405/45333186-cb6a2400-b542-11e8-993d-75ac086dc6a9.png)

**Comment by grs** [comment]
The messages out is taken from the router delivery stats for the address and reflects the number of messages transferred, irrespective of acceptance or not, so prefetched and released messages are included.

The stored count is taken from the broker. It looks to me like the simple_recv.py example may actually be at fault here, accepting more messages than specified.

**Comment by k-wall** [comment]
@vbusch were you able to confirm?

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.
