### ISSUE TITLE
List of bugs in singlenamespace branch

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#1624]
- [x] Cannot deploy addressspace with pla unlimited-standard-without-mqtt
- [x] Cannot create addressspace using service catalog (no pod for address-space is created)
- [x] Cannot send mqtt messages in standard addressspace

**Comment by lulf** [comment]
@kornys I think first and third issue should be resolved now. Btw, maybe we could also put this info in the origin issue #1587 as we work on it, not having to create another issue which is strictly only related to that branch.

**Comment by kornys** [comment]
@lulf yes youre right service catalog works, it was problem with my deployment. So Im going to close this issue, all bugs are fixed in branch.
