### ISSUE TITLE
Link that goes nowhere in the documentation

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1628]
In latest documentation ( http://enmasse.io/documentation/0.22.0 ) 
Appendix A.1.1. Installing EnMasse:
  The link "This guide uses a shell script for deploying EnMasse. Windows users are advised to look at **_Installing EnMasse._**"  goes nowhere, it links back to the same section it is part of. Windows users are taken to the part they are currently looking at. (infact I can see no section at all for installing on windows in the docs.. ) 

same for A.1.5. EnMasse on Kubernetes.

Also... The section for Installing Enmasse on Openshift is structured differently than the section for Installing Enmasse on Kubernetes and AWS... please see the below screenshot. ( sorry for the bad paint job! ) 
![docs](https://user-images.githubusercontent.com/32485509/45483536-80722b80-b751-11e8-84c7-70d30ff95d45.png)

**Comment by sjay72** [comment]
@RH-sdavey, I assigned @jenmalloy to take a look at this. (Obviously. :-)) It's not too bad a paint job. ;-)

**Comment by RH-sdavey** [comment]
@sjay72 sorry got mixed up, of course it should be Jen, sorry about that!

**Comment by lulf** [comment]
I think this is fixed in 0.23.0 docs

**Comment by RH-sdavey** [comment]
fixed in latest ( 0.2.3 )  docs, thanks
