### ISSUE TITLE
Add "server" mode to the MQTT LWT service

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse#163]
Today the MQTT LWT service works in client mode only. It's able to connect to a messaging AMQP 1.0 network and on that connection is able to handle attached/detached link for its purpose.
It makes sense to add a server mode (i.e. see the amqp-kafka bridge) for handling incoming connection directly when a router network isn't available.
It's also related to move this component to be a generic AMQP 1.0 connectivity/presence service (see #47) living outside of EnMasse so usable even without a routers netwok.
@lulf @rgodfrey @grs wdyt ?

**Comment by lulf** [comment]
Closing as MQTT support and subserv will be removed
