### ISSUE TITLE
Service catalog wizard link goes to wrong place

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1630]
Sorry for such a minor issue, I think this link labelled 'view Documentation'  should take you to enmasse documentation, rather than the github repo page. ( or at least the documentation link of the README ) 
for both standard and brokered wizards. 
![screenshot](https://user-images.githubusercontent.com/32485509/45487814-b28a8a00-b75f-11e8-8a73-35d81eebedd2.png)

**Comment by RH-sdavey** [comment]
same (wrong destination) link here
![image](https://user-images.githubusercontent.com/32485509/47806194-6c05e480-dd39-11e8-915e-5e5a98ef964f.png)

**Comment by k-wall** [comment]
I'd suggest a suitable target would be http://enmasse.io/documentation/

**Comment by lulf** [comment]
Service broker will be removed in 1.0.
