### ISSUE TITLE
Split messaging service into an internal and internal-external service

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#166]
This makes it clearer what service to use for internal EnMasse communication, that is based on certificate trust vs. the service that is used by external clients that are authenticated using the authentication service.

**Comment by kornys** [comment]
@lulf this is completed, right?

**Comment by lulf** [comment]
@kornys no, everything is still in the same service called 'messaging'.

**Comment by lulf** [comment]
Will be fixed in 1.0
