### ISSUE TITLE
Allow creating routes with re-encrypt

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#1661]
## why

EnMasse manages its own certificates. But when cluster wide certificates are properly installed, it may be beneficial to use them instead.

## Proposal

Currently the routes are created with "passthrough". My recommendation would be to allow them to be created with "reencrypt" in addition. When setting "reencrypt" it would be necessary though to set the "destination CA certificate" as well. The content would be the EnMasse created CA certificate.

This would require a change of the OpenShift templates as well as the component which automatically creates e.g. the "messaging" route.

## Testing

Testing is good, but I don't have a plan.

## Documentation

A new switch in the installer has to be documented.

## Tasklist

* [x] Change templates
* [ ] Create feature in "operator" component
* [ ] Update documentation
* [ ] Test with proper certificate

**Comment by lulf** [comment]
I am doing this as part of #1650 , where both keycloak, restapi and console routes will be using reencrypt (running into a small issue with console there but hope to get it fixed at least). 

The messaging and mqtt routes cannot use reencrypt, because it relies on HTTP features.

**Comment by ctron** [comment]
> The messaging and mqtt routes cannot use reencrypt, because it relies on HTTP features.

Yes, I figured that out. However it still works for the websockets port.

**Comment by ctron** [comment]
Btw .. I did raise an issue about that: https://bugzilla.redhat.com/show_bug.cgi?id=1631377

**Comment by rgodfrey** [comment]
I'd be nervous about the websocket case in the event we (at some point in the future) want to use the SNI information from the original request (unless OpenShift automagically retains this in the re-encrypted communication).

**Comment by lulf** [comment]
Fixed on master/0.240
