### ISSUE TITLE
Keycloak runs into OOM when starting

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#1662]
**Describe the bug**

Enabling the "standard auth service", Keycloak comes up and directly runs into an out-of-memory situation.

**To Reproduce**
1. Deploy EnMasse with `-a standard`
1. Look at the logs of the keycloak pod

**Expected behavior**

Not run into OOM situation.

**Logs**

[keycloak-86f7594ccf-xt6sh.log](https://github.com/EnMasseProject/enmasse/files/2402047/keycloak-86f7594ccf-xt6sh.log)

**Comment by ctron** [comment]
Setting the memory to `-Xmx2048m` fixed the issue for me.

**Comment by ctron** [comment]
Ok, it freaked out a bit later. Now I have `-Xmx3072`

**Comment by k-wall** [comment]
I can possibly accept that 1GB is maybe tight for a Java application so that may explain the startup failure.  It is odd that I haven't been seeing this at all.

 I am slightly surprised by the need to bump from 2 to 3GB.
 
Can you tell me:

* EnMasse version
* Number of address spaces (each address space gets its own keycloak realm)
* Approximate number of authentications that had taken place (order of magnitude estimate fine)

**Comment by ctron** [comment]
EnMasse version: 0.22.0
Number of address spaces: 1
Approximate number of authentications that had taken place: 2

**Comment by lulf** [comment]
@ctron Which version of OpenShift? I have seen this behavior of Keycloak ~1 year ago, but it was with an older version, and there was something that only happened on that particular cluster.

**Comment by ctron** [comment]
OKD 3.10

**Comment by k-wall** [comment]
Unless another occurrence has been seen, I think this issue should be closed.  If it is seen again, turn on ` -XX:+HeapDumpOnOutOfMemoryError` so the reason of for OOME can be investigated.

**Comment by ctron** [comment]
I think a have a new instance of this problem. 107 restarts in 9 days.

@k-wall I can give you access to this cluster if this is of any help. I will enable the Java option as well.

**Comment by ctron** [comment]
I am re-opening this, as I can now provide a heapdump: https://web.tresorit.com/l#Asmvkjv85mkoJPUNpufc4g

**Note:** this link will expire in 30 days

**Comment by lulf** [comment]
A quick look reveals a lot of byte[] objects from qpid proton sasl: 

Some resources that needs to be cleaned up @rgodfrey ?

![proton](https://user-images.githubusercontent.com/19670/49942845-b8bb0e80-fee6-11e8-8bcf-4e9a78cb9464.png)

**Comment by rgodfrey** [comment]
Just to add it seems like all the non closed connections are coming from the same IP address (168.0.0.1 for what it's worth)

**Comment by lulf** [comment]
@ctron This should be fixed on 0.25.0. Would you be able to try it and see if it resolves the issue?

**Comment by ctron** [comment]
I think that I had the same situation as before, but this time the keycloak instance did not restart.

I would say this looks good!
