### ISSUE TITLE
Improve support for wildcards in authorizations

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#1664]
## why

Because it makes live so much easier.

## Proposal

Currently the authorization allows to specific a wildcard at the end of the address. e.g. `topic*`. However it seems that putting the wildcard at the beginning, like `*/DEFAULT_TENANT` doesn't work.

My proposal is to allow wildcards in all locations.

## Testing

I have no plan.

## Documentation

Yes, documentation should be created for that. In any case, as the current situation doesn't seem to be documented either.

## Tasklist

* [ ] Implement
* [ ] Document
* [ ] Test
* [ ] Release

**Comment by lulf** [comment]
This is really a limitation of qpid dispatch router and activemq Artemis, so an issue should be filed against those projects.
