### ISSUE TITLE
Errors found in latest documentation

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1670]
I have found the following errors / inconsistencies in latest documentation http://enmasse.io/documentation/0.22.0/

======================================================================
 inconsistency in wording style:
6. Managing users  Prerequisites
You have created an Address Space

6.3. Deleting users using the command line Prerequisites
An address space must have been created.

======================================================================
 inconsistency in wording style:
5.3.2. Viewing Address Space Status 
You can consider the address space to be ready to use when status.isReady is true in the returned JSON object.

5.3.4. Viewing Configured Addresses
The addresses are ready to be used by messaging clients once the status.isReady field of each address is set to true.

======================================================================
strange word "route" here
A.1.5 Connecting using MQTT
For sending and receiving messages ***route***, you can use the paho-mqtt client library. To connect, fetch the server certificate: 

======================================================================
formatting visible?
A.1.4. Conclusion
:context: kube

======================================================================
search for "the the"   ( case insensitive) 

======================================================================
first person "I" is being used in the below paragraph?
The process for setting up grafana is a bit more involved, but it gives you a nice overview of whats going on over time. First of all, I like to setup everything metric-related in the openshift-infra project. To do that, you must first give your user permission sufficient privileges. In this setup, since it is not a production setup, I grant cluster-admin privileges for simplicity (requires logging into the ec2 instance): 

======================================================================
split "E" on the end of the sentence
After some time, Grafana should become available at oc get route -n openshift-infra -o jsonpath='{.spec.host}' hawkular-grafana. The default username and password is admin/admin. ***E*** 

======================================================================
didnt get to check this on a bigger monitor, but, I think the last column of the tables in the below sections could be resized just a *little* so the weird newlines dont appear.. 
B.1.3. Definitions
io.enmasse.v1alpha1.AddressList
io.enmasse.v1alpha1.AddressSpaceList
![image](https://user-images.githubusercontent.com/32485509/45894247-1fd89380-bdce-11e8-81b4-cc26bf8fa75b.png)

======================================================================
I dont think the below section is true... creating an address space shouldnt need any docker downloads?
5.3.1. Creating an Address Space
Procedure part 2.
Starting up the address space will take a while, usually depending on how fast it is able to download the Docker images for the various components.

======================================================================
search for "NOTE" ... many differences in style

======================================================================
search for "prerequisite" ... inconsistencies in style ( italics, bulletpoints etc )

======================================================================
Search for "Subscriber client" and "Publisher client" and compare the styling of the two headers styles ( 3 in total )

======================================================================
The the publisher publishes the message and disconnects from EnMasse. The message is received by the previous connected subscriber. ==> previously 

sure Ansible is installed on laptop or workstation. ====> installed on your laptop
( sorry for petty ones )

======================================================================
#1628 

======================================================================
really dont understand this sentence in the context around it... (maybe just me ?...)
If you do not have a domain with wildcard support, you can replace with .nip.io, and you will have a working setup without having a specialized domain.

======================================================================
In every "block code example" ( the greyed boxes) I can see they are preceded by a line ending with ":" except for the ones that are preceded by the text "Invoke the deployment script to deploy EnMasse" <--- search for this    ( I can explain this one if its not clear ) 

======================================================================
inconsistency in wording style:
5.3.1. Creating an Address Space /  Procedure
Save the following JSON data to a file 'space.json':
5.3.3. Creating Addresses /  Procedure
To create addresses in the standard address space, save the address definition to a file:
(maybe others, I didnt check)

======================================================================
search for "\*", 
first 3 results should be "* Deploying authentication services."
I believe the * is not needed in these 3 results...

======================================================================

**Comment by RH-sdavey** [comment]
https://github.com/EnMasseProject/enmasse/issues/1628

**Comment by RH-sdavey** [comment]
The the publisher publishes the message and disconnects from EnMasse. The message is received by the previous connected subscriber.  ==> previously  ( sorry for petty ones )

**Comment by RH-sdavey** [comment]
Search for "Subscriber client" and "Publisher client" and compare the styling of the two headers styles ( 3 in total )

**Comment by jenmalloy** [comment]
@RH-sdavey, I'm starting to address some of the obvious errors (like "the the"), and will work my way through. Thanks!

**Comment by RH-sdavey** [comment]
@jenmalloy Most of these look fixed in latest 0.2.3 docs to me. All the "important" ones at least. 
We can go ahead and close this issue and #1628 (fixed also) wdyt?

**Comment by jenmalloy** [comment]
@RH-sdavey, yes, I'm fine with that. Thank you!
