### ISSUE TITLE
A connection's message counts remain zero when messaging is in progress

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1722]
**Describe the bug**
In the Console's connection tab, the messages in and messages out values remain at zero even when messaging is in progress.    This is a regression since 0.22.0.

**To Reproduce**
1. Create a standard address space.
2. Create a Pooled Queue
3. Run JMS client's HelloWorld modified with a `System.in.read()` before the connection close.
4. Examine the connection in the Console.
5. Connection is present, but the Message In and Message Out values are at 0. 

**Expected behavior**
Message In and Message Out values should be 1.

**Comment by k-wall** [comment]
On the brokered space issue, in my previous comment, the absence of the message out value is expected.  The Broker does not provide that information.  The column ought to be hidden.

**Comment by grs** [comment]
@k-wall Column is hidden by the second commit in PR #1723
