### ISSUE TITLE
[Console] About button doesn't work as I would expect

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1733]
In console, the About link provided in the ? icon dropdown in the top right doesnt seem to do anything reasonable or provide any reasonable information about enmasse.

it seems to just redirect the user back to the Dashboard information screen. I would expect rather that it would provide some information about the enmasse build itself. (version, author, latest updates etc) 
Also, when it send the user to the dashboard information, it doesnt update the highlighted tab on the left menu, to reproduce, 

- open console
- click on Addresses tab on the left  = addresses tab highlighted and addresses page shown
- select About from the ? icon on the top right = addresses tab still highlighted but dashboard info showing 

![about_button](https://user-images.githubusercontent.com/32485509/46410430-21cd1b80-c719-11e8-9f4b-503dda25e3d2.png)

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced and the about feature reimplemented.
