### ISSUE TITLE
[console] filter should have option to filter for multiple values

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1734]
## why
At the moment, the address filter in console is quite exclusive in how it operates, that is, I can filter for type: topic  AND type: subscription (which of course matches nothing), with no way to filter both topics OR subs, I believe this would be a useful feature

## Proposal
Edit the address filter functionality so that multiple filters can be applied, 
some examples I can imagine that a user may wish to do:

- filter types for all topics and all subcriptions  at the same time
- filter types for all multi and anycast addresses at the same time
- filter name for multiple names at the same time.   ( related but not similarly named topics/queues etc )

**Comment by vbusch** [comment]
@RH-sdavey do you think users would also want to filter by name & type together?  For example, apply a filter to find only topics who's name matches?

**Comment by grs** [comment]
Just to clarify, multiple filters *can* be applied. However they are combined at present with AND logic, i.e. an item must match all the active filters to be shown.

I believe the request here is to support combining filters with OR logic as well(?).

**Comment by RH-sdavey** [comment]
@vbusch  its surely a possibility, as gsim correctly points out, I think this would already be possible, with AND logic. That is I can filter by topics, then filter for "mytopic" name and will see all matches, I cant immediately think ( pre-coffee ) of any reasonable scenario to search for topics OR a certain name... but if its possible to do it, I will leave it at your discretion.

@grs youre absolutely right, should have been more clear in the description. yes, the request is for OR logic.

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.
