### ISSUE TITLE
Existing connection filters not applied to new forming connections.

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1757]
**Describe the bug**
If a new connection is created after a Console user has established a filter, the new connection appears on his results even if the connection does not match.  I am testing in the Standard address space.

**To Reproduce**
1. Create a queue
2. Create a connection that uses the queue.
3. Establish a connection filter that filters on the connection's uuid
4. Create a second connection that uses the queue
5. Connection appears in the user's filtered list (**DEFECT**)

**Expected behavior**
As new connection has a randomly assigned UUID, it should not match the predicates, so its appearance in the results is unexpected.

We should check if the same issue exists in the address tab too.

**Comment by RH-sdavey** [comment]
https://issues.jboss.org/browse/ENTMQMAAS-813 is moved to done and green from QE.
issue is fixed after #1767, issue can be closed.
