### ISSUE TITLE
Improve aesthetics of address tab

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1759]
#1708 reformatted address rows so that the messages in/messages out fields includes a legend allowing the user to know that the values are over the last five minutes.

As recorded as comments on #1708 there is dislike for the new aesthetics.  Specifically the position of the checkbox/additional information expansion icon relative to the rest of row (it is not centralised), and whether the stacked values interrupt the flow.

Screenshots showing the problem are recorded https://github.com/EnMasseProject/enmasse/pull/1708#issuecomment-427393826

**Comment by k-wall** [comment]
I have spent some looking for ways to centralise the checkbox/additional information with the rest o the information on the row.   I can't see a see a way to achieve that with angular patternfly.  

I noticed that if you are using patternfly purely declaratively, as with the [demo app](https://github.com/patternfly/patternfly-demo-app), the issue does not occur when the row includes a stacked item.

**Comment by yih-wang** [comment]
Hi Keith, I create a wireframe to improve aesthetics and usabilities of the Address tab. You can have a look here: https://redhat.invisionapp.com/share/WDOQSTTPU7J
