### ISSUE TITLE
Systemtests for upgrading EnMasse

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1761]
With #1741 , we need to be able to test that upgrades work. I think the following test scenario should give a good first coverage of upgrades:

1. Deploy latest EnMasse release
2. Create brokered address space with 1 queue and 1 topic
3. Try send/recv on all brokered addresses.
4. Send a couple of durable messages to brokered queues
5. Create standard address space with 1 anycast, 1 multicast, 1 queue, 1 topic, 1 sharded queue, 1 sharded topic
6. Try send/recv on all standard addresses
7. Send a couple of durable messages to standard queues
8. Deploy EnMasse from master (re-run playbook)
9. Wait for all components to be upgraded/restarted
10. Receive from brokered queues
11. Receive from standard queues
12. Try send/recv on all brokered addresses
13. Try send/recv on all standard addresses

**Comment by kornys** [comment]
@lulf lgtm I will do that, I will create new test group for this scenario.

**Comment by lulf** [comment]
@kornys I think it makes sense to create a separate jenkinsfile and job for this perhaps, Jenkinsfile-upgrade and enmasse-master-upgrade. It would first deploy $params.LATEST_RELEASE , run the UpgradeTests, then deploy the latest master build, then rerun UpgradeTests?

**Comment by kornys** [comment]
@lulf that makes sense, after refactoring of jenkins files on which Im working on It should be easy.

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/1778/commits/1e378a4c08cba0486a55455c93263319e1524743

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/1794/commits/c39bc4a6885844f88ce876050ddf80dcfd2fb539

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/commit/782e192502013e4df5624cc2a77c58ab34746f6f
