### ISSUE TITLE
Agent unexpectedly deleting queues

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1781]
I am running a [scripted](https://github.com/EnMasseProject/enmasse/files/2473655/create_queues.zip) test that creates sequentially numbered pooled queues in a loop.   I am noticed that after about 1200 queues, the agent log reports that queues (and auto links) are being deleted.  When this occurs I am seeing many queues revert to a `.status.isReady = false`.

The `address-plan-pooled-queue` had been altered  so `requiredResources` for `broker` and `router` were 0.005.  No messages were being sent to the queues.

Here's one example:

2018-10-12T14:57:38.046Z agent info [broker-pooled-i6zbsyu6xh-5] Creating queue "b187"...
...
2018-10-12T14:57:43.396Z agent info [broker-pooled-i6zbsyu6xh-5] Deleted queue "b187"
..
2018-10-12T14:57:43.936Z agent info deleted autolink in b187 on qdrouterd-i6zbsyu6xh-2
2018-10-12T14:57:43.936Z agent info deleted autolink out b187 on qdrouterd-i6zbsyu6xh-2

I am seeing this for many addresses.

[agent.log](https://github.com/EnMasseProject/enmasse/files/2473646/agent.log)

**Comment by grs** [comment]
From log:

addresses_ready: added ["b192","b194","b196","b198","b200"], modified ["b187"]

I think it is whatever causes the agent to believe the definition of b187 has changed which then prompts the deletion. Is it possible the broker it is allocated to is changing?

**Comment by grs** [comment]
Also:

2018-10-12T15:03:45.155Z agent info addresses_ready: added ["b641"], modified ["b467"]
2018-10-12T15:03:45.487Z agent info [broker-pooled-i6zbsyu6xh-8] Creating queue "b467"...
2018-10-12T15:03:45.559Z agent info [broker-pooled-i6zbsyu6xh-7] Deleting queue "b467"...
2018-10-12T15:03:45.952Z agent info [broker-pooled-i6zbsyu6xh-7] Deleted queue "b467"
2018-10-12T15:03:45.997Z agent info [broker-pooled-i6zbsyu6xh-8] Created queue "b467"

Which would match the theory that the queue is being reallocated.

**Comment by grs** [comment]
@k-wall a change that might shed further light on whether the theory above holds: https://github.com/EnMasseProject/enmasse/pull/1785

**Comment by k-wall** [comment]
@grs - reproduction with additional logging #1785

[agent_20181015.log](https://github.com/EnMasseProject/enmasse/files/2478037/agent_20181015.log)

**Comment by k-wall** [comment]
This is a race condition.  In the problematic case `AddressController#onUpdate` acts on an address whose state is stale in the `FifoQueue#store`.    This means that the address is treated as if they were `Pending` when in actual fact they have already been moved to `Configuring` by a previous invocation of `AddressController#onUpdate`.  This then causes the Agent the assign address to a new broker.   (as testified by the logging added by #1785).

The store is updated either by incoming watch notifications or a periodic resync.   When the store is updated by a watch notification, this triggers AddressController#onUpdate on a different thread, passing the current state of the whole store.  If many addresses are being created concurrently, this opens the possible where an update to address A causes the AddressController#onUpdate` to see stale address B, simply because the notification for B has not hit the store yet.


   The problem is most likely to be seen when creating many addresses concurrently.   
 




 some of which have stale states.

The issue is that the `FifoQueue#store` can  stale.   The store is updated either by incoming watch notifications or a periodic resync.  If many addresses are being created concurrently


I see the race occurring when there a system has many hundreds or thousands of addresses though I think the issue could occur with smaller number of addresses.

  The sequence of the events is:

1. AddressController#onUpdate provisions resources for a new address and updates the address AddressApi#replaceAddress.





The AddressController#onUpdate is passed a set
