### ISSUE TITLE
[UX Improvement]Creating the links between Address and Connection

### ISSUE THREAD

**Issue by junezhang** [EnMasseProject/enmasse#1786]
[User Story]
As a Monitor, I want to, through the address info, I can get the related connections along with their authenticated identity, age, last activity time, ingress/egress rates, and protocol.

Related issue: https://github.com/EnMasseProject/enmasse/issues/1605

[Task]
Create the design proposal for the user story

**Comment by yih-wang** [comment]
Based on #1836 , the Container ID can be the bridge of Address and Connection tabs. Thus updated the design as follows:

![navigation-address 2x](https://user-images.githubusercontent.com/23331885/47434638-85f17580-d7d5-11e8-9dd7-d90b7d44cbce.png)
![navigation-connection 2x](https://user-images.githubusercontent.com/23331885/47434646-8853cf80-d7d5-11e8-8ffd-69db24efb3a6.png)

Visit the whole wireframe through this link: https://redhat.invisionapp.com/share/BMOR5TP4GZJ
