### ISSUE TITLE
[UX Improvement] Address list usability improvement

### ISSUE THREAD

**Issue by junezhang** [EnMasseProject/enmasse#1787]
[User Story]
As a Monitor, I want to, for a single address space, view all addresses and their types, along with current size/depth an ingress/egress rates, last inbound arrival time, last outbound message time, etc.

Related issues:

- [Add paging to Addresses page](https://github.com/EnMasseProject/enmasse/issues/1305)
- [Add Select All function](https://github.com/EnMasseProject/enmasse/issues/619)
- [Add Sum Row in link table](https://github.com/EnMasseProject/enmasse/issues/992)
- [Bug of wizard](https://github.com/EnMasseProject/enmasse/issues/1498)
- [Improve aesthetics of address tab](https://github.com/EnMasseProject/enmasse/issues/1759)

[Task]
Provide the design solution to improve the address usability

**Comment by yih-wang** [comment]
Firstly improve aesthetics and usabilities based on the current functions, wireframe can be found here: https://redhat.invisionapp.com/share/WDOQSTTPU7J Reference #1847
