### ISSUE TITLE
Add more information to cli output

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1808]
## why

Kubernetes APIs supports a `Table` format to be requested when retrieving resources using `oc` or `kubectl`. This is triggered by the CLI setting the header `Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json`

The API servers then respond with both a schema for the table and the data within it.

See https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables for more information

## Proposal

Add support for the `Table` format in the API server so that cli can provide better information about addressspaces, addresses and messagingusers.

## Testing

What is the test plan for the feature/change?  

## Documentation

Examples must be updated with the actual output.

## Tasklist

- [ ] Decide on what columns to display
- [ ] Add support for parsing Accept header and detect requested table format
- [ ] Add types and responses for Table type.

**Comment by k-wall** [comment]
I think being able to easily see the status of address and addressspans from the command line would be valuable.   For addresses that are queue like, being able to see a recent queue depth would be really useful too.

Would there be benefit to expose connections too?

Would we want to

**Comment by lulf** [comment]
I think we should not expose information there that are not persisted in the configmap. Also it doesn't feel right to have the api server query brokers for stats. Lastly something like queue depths would need to be updated regularly, requiring a lot of writing to the configmap compared to today where we only write it in rare cases. I think metrics etc. maybe long elsewhere.

**Comment by lulf** [comment]
@k-wall A couple of ideas that came up discussing this with @rgodfrey and @robshelly : 

a) provide a command line tool to manage all of enmasse from an ops side (enmassectl :))
b) provide a read-only addressstatus resource that can be queried for stats of an address and that will cause api-server to query broker, router etc. for information

We should also consider service admin vs. tenant here... I think an enmassectl would be useful for an admin to manage an EnMasse instance, whereas `oc get addressstatus` is perhaps mostly interesting for a messaging tenant.

I think alternative 'a' has a lot of potential to be used for installing, upgrading etc. as well and as a way to inspect routers, brokers etc. in more detail. This is also a well-established approach used by the Istio project for instance.

Alternative 'b' will meet the requirements of getting more stats about addresses without requiring to write stats to the configmap and is perhaps a more realistic short-term task.
