### ISSUE TITLE
[console] Allow user  to change the amount of time that the metrics shown for each address are aggregated for

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1826]
## Why
Allow the user to change the amount of time that the metrics shown for each address are aggregated for. 
The end user may wish to see values for different time periods other than 5 minutes 
(is it possible to extract metrics for longer than 5 minutes?)

## Proposal
At the moment, metrics for each address are shown for  the last 5 minutes, see screenshot[1] , I believe end users may wish to see metrics for example the last 1 hour, 24 hours, etc etc  ( if its possible ) 

## Testing
Could be tested via marathon test plan

## Tasklist
Would need to be decided if it was worth it to do this for individual addresses or blanket change for all addresses metrics at the same time. 

## Screenshot
[1] 
![image](https://user-images.githubusercontent.com/32485509/47291730-0745de00-d605-11e8-9f8a-cf76b75271fe.png)

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.
