### ISSUE TITLE
[console] Add option to filter by address state

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1827]
## why

Add feature to filter to by address state, End users could filter addresses by state or phase.
"status": { "isReady": false, "phase": "Pending" } 

This way, if there is a large number of addresses with some periodically or intermittently 'flipping' to a non-ready state or experiencing errors, users could filter these out quickly (eg: for debugging)

## Proposal

add extra option to filter to filter by address state

## Testing
webconsole filter tests

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced. The new console has this feature.
