### ISSUE TITLE
How to exercise mqtt connection tutorial steps with minishift?

### ISSUE THREAD

**Issue by LeeWong** [EnMasseProject/enmasse#183]
Hi there,

I am new to the enmasse and openshift origin. I installed a openshift oirigin via minishift but am having trouble on exercising the following mqtt connection tutorial steps:

MQTT

For sending and receiving messages, the quitto_sub -h $(oc get service -o jsonpath='{.spec.clusterIP}' mqtt) -t mytopic -q 1osquitto clients are the simpler way to go. These clients can be used either against the local service IP or the external route. To connect using the local service IP:

In order to subscribe to a topic (i.e. mytopic from the previous addresses configuration), the mosquitto_sub can be used in the following way :

mosquitto_sub -h $(oc get service -o jsonpath='{.spec.clusterIP}' mqtt) -t mytopic -q 1
Then the subscriber is waiting for messages published on that topic. To start the publisher, the mosquitto_pub can be used in the following way :

mosquitto_pub -h $(oc get service -o jsonpath='{.spec.clusterIP}' mqtt) -t mytopic -q 1 -m "Hello EnMasse"
The the publisher publishes the message and disconnects from EnMasse. The message is received by the previous connected subscriber.

For sending and receiving messages using the external route, have a look at an example python sender and receiver.

In order to subscribe to a topic (i.e. mytopic from the previous addresses configuration), the receiver client can be used in the following way :

./tls_mqtt_recv.py -c "$(oc get route -o jsonpath='{.spec.host}' mqtt)" -p 443 -t mytopic -q 1 -s ./server-cert.pem
Then the subscriber is waiting for messages published on that topic. To start the publisher, the sender client can be used in the following way :

./tls_mqtt_send.py -c "$(oc get route -o jsonpath='{.spec.host}' mqtt)" -p 443 -t mytopic -q 1 -s ./server-cert.pem -m "Hello EnMasse"
The the publisher publishes the message and disconnects from EnMasse. The message is received by the previous connected subscriber.

Even with the route configuration,  ./server-cert.pem is missing from sending and receiving mqtt messages in the python commands. 

Here is my Services table on openshift:

Name | Cluster IP | External IP | Ports | Selector | Age
-- | -- | -- | -- | -- | --
ragent | 172.30.211.248 | none | 5672/TCP | name=admin | 3 hours
subscription | 172.30.81.232 | none | 5672/TCP | name=subserv | 3 hours
console | 172.30.39.178 | none | 5672/TCP, 8080/TCP | name=admin | 3 hours
messaging | 172.30.150.75 | none | 5672/TCP, 5671/TCP,55673/TCP,55672/TCP | capability=router | 3 hours
mqtt | 172.30.189.183 | none | 1883/TCP, 8883/TCP | name=mqtt-gateway | 3 hours
queue-scheduler | 172.30.160.39 | none | 5672/TCP | name=admin | 3 hours
configuration | 172.30.53.98 | none | 5672/TCP | name=admin | 3 hours
address-controller | 172.30.148.85 | none | 8080/TCP, 8081/TCP,5672/TCP | name=address-controller | 3 hours

Thank you so much.

Cheers,
Lee

**Comment by lulf** [comment]
Hi Lee,

Which one of the commands is not working for you?

The commands that connect directly to the MQTT service (mosquitto_*) will not work when running on minishift. The reason for that is that minishift runs OpenShift inside a VM, so you cannot connect to the service ips, because they are internal to the VM. 

You can still connect to the MQTT service using the exposed mqtt route, but that requires use of TLS:

```
For sending and receiving messages using the external route, have a look at an example python sender and receiver.

In order to subscribe to a topic (i.e. mytopic from the previous addresses configuration), the receiver client can be used in the following way :

./tls_mqtt_recv.py -c "$(oc get route -o jsonpath='{.spec.host}' mqtt)" -p 443 -t mytopic -q 1 -s ./server-cert.pem
```

**Comment by LeeWong** [comment]
Hi lulf, 

This does not work for me : ./tls_mqtt_recv.py -c "$(oc get route -o jsonpath='{.spec.host}' mqtt)" -p 443 -t mytopic -q 1 -s ./server-cert.pem

Do you know where server-cert.pem is located? Thank you.

Cheers,
Lee

**Comment by lulf** [comment]
Lee,

Try to run: oc extract secret/external-certs-mqtt

This should create the files. The doc needs some updating, sorry!

**Comment by LeeWong** [comment]
Thank you so much for the quick reply. It solves the issue. :+1:

**Comment by LeeWong** [comment]
Should "Hello EnMasse" be showing on the receiver console, after ./tls_mqtt_send.py -c "$(oc get route -o jsonpath='{.spec.host}' mqtt)" -p 443 -t mytopic -q 1 -s ./server-cert.pem -m "Hello EnMasse" is executed?

**Comment by LeeWong** [comment]
I can tell from the console that the connection to enmasse is established. However, I did not see the message received in the console from the subscripted topic "mytopic". Is it expected?

**Comment by lulf** [comment]
This should've worked. Can you run the clients with environment variable PN_TRACE_FRM=1 ?

Also, providing the output after running this log printing script would be useful: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/scripts/print_logs.sh

**Comment by LeeWong** [comment]
Hi @lulf, I ran the clients with what you recommended. However, I am still seeing the same issue.

Here are the output after running the log printing:
[testlog.txt](https://github.com/EnMasseProject/enmasse/files/1277970/testlog.txt)

I am using the release version 0.12.3

Thank you.

**Comment by LeeWong** [comment]
Here is the summary of the log file:
#######################################################################
oc logs -c address-controller address-controller-3982660230-sprz7 : 

....... (to ignore identical logging information)

2017-09-05 15:32:08 INFO  AddressController:85 - Check address in address space controller: []
2017-09-05 15:32:08 INFO  AddressController:106 - Current set of clusters: []
#######################################################################
oc logs -c ragent admin-2502725539-dl5b4 : 
Fri, 01 Sep 2017 14:12:34 GMT ragent info Router agent starting
Fri, 01 Sep 2017 14:12:34 GMT ragent info Subscribing with selector: {"name":"ragent"}
Fri, 01 Sep 2017 14:12:34 GMT ragent info Router agent listening on 55672
[connection-1] error: Error: connect ECONNREFUSED 127.0.0.1:5672
[connection-1] disconnected 
[connection-1] error: Error: connect ECONNREFUSED 127.0.0.1:5672
[connection-1] disconnected 
[connection-1] error: Error: connect ECONNREFUSED 127.0.0.1:5672
[connection-1] disconnected 
[connection-1] error: Error: connect ECONNREFUSED 127.0.0.1:5672
[connection-1] disconnected 
[connection-1] error: Error: connect ECONNREFUSED 127.0.0.1:5672
[connection-1] disconnected 
[connection-1] error: Error: connect ECONNREFUSED 127.0.0.1:5672
[connection-1] disconnected 
[connection-2] disconnected 
[connection-3] disconnected 
[connection-4] disconnected 
[connection-5] disconnected 
[connection-6] disconnected 
[connection-7] disconnected 
[connection-8] disconnected 
[connection-9] disconnected 
[connection-10] disconnected 
[connection-11] disconnected 
[connection-12] disconnected 
[connection-13] disconnected 
[connection-14] disconnected 
Fri, 01 Sep 2017 14:14:50 GMT ragent info Router connected from Router.qdrouterd-2034113809-5w0s8
Fri, 01 Sep 2017 14:14:50 GMT ragent info retrieved listeners for Router.qdrouterd-2034113809-5w0s8: 172.17.0.7:55672
Fri, 01 Sep 2017 14:14:50 GMT ragent info Router.qdrouterd-2034113809-5w0s8 not ready for connectivity check: false false
Fri, 01 Sep 2017 14:14:50 GMT ragent info retrieved connectors for Router.qdrouterd-2034113809-5w0s8: 
Fri, 01 Sep 2017 14:14:50 GMT ragent info Router.qdrouterd-2034113809-5w0s8 not ready for connectivity check: false true
Fri, 01 Sep 2017 14:14:50 GMT ragent info EXTRACT, results: , attributes: name,identity,type,prefix,distribution,waypoint,ingressPhase,egressPhase
Fri, 01 Sep 2017 14:14:50 GMT ragent info retrieved addresses for Router.qdrouterd-2034113809-5w0s8: {}
Fri, 01 Sep 2017 14:14:50 GMT ragent info retrieved link routes for Router.qdrouterd-2034113809-5w0s8: raw-> [{"name":"override.lwt_in","identity":"1","type":"org.apache.qpid.dispatch.router.config.linkRoute","prefix":"$lwt","distribution":"linkBalanced","connection":null,"containerId":"lwt-service","dir":"in","operStatus":"active"},{"name":"override.lwt_out","identity":"2","type":"org.apache.qpid.dispatch.router.config.linkRoute","prefix":"$lwt","distribution":"linkBalanced","connection":null,"containerId":"lwt-service","dir":"out","operStatus":"active"},{"name":"override.locate","identity":"3","type":"org.apache.qpid.dispatch.router.config.linkRoute","prefix":"locate","distribution":"linkBalanced","connection":"subscription-service","containerId":null,"dir":"out","operStatus":"inactive"}]
Fri, 01 Sep 2017 14:14:50 GMT ragent info retrieved link routes for Router.qdrouterd-2034113809-5w0s8: {}
Fri, 01 Sep 2017 14:14:50 GMT ragent info updating addresses for Router.qdrouterd-2034113809-5w0s8
Fri, 01 Sep 2017 14:14:50 GMT ragent info checking connectivity for Router.qdrouterd-2034113809-5w0s8
Fri, 01 Sep 2017 14:14:50 GMT ragent info checking connectors on router Router.qdrouterd-2034113809-5w0s8, missing=, stale=
[connection-16] disconnected 
[connection-17] disconnected 

......

#######################################################################

oc logs -c mqtt-gateway-tls mqtt-gateway-2959230739-rh3kf : 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

14:13:12.119 [main] INFO  enmasse.mqtt.Application - Starting Application on mqtt-gateway-2959230739-rh3kf with PID 1 (/mqtt-gateway.jar started by ? in /)
14:13:12.122 [main] DEBUG enmasse.mqtt.Application - Running with Spring Boot v1.5.4.RELEASE, Spring v4.3.9.RELEASE
14:13:12.122 [main] INFO  enmasse.mqtt.Application - No active profile set, falling back to default profiles: default
14:13:12.191 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@443b7951: startup date [Fri Sep 01 14:13:12 UTC 2017]; root of context hierarchy
14:13:12.929 [main] DEBUG enmasse.mqtt.Application - Starting up 1 instances of MQTT gateway verticle
14:13:12.962 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - Starting MQTT gateway verticle...
14:13:12.966 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - SSL/TLS support enabled key /etc/mqtt-gateway/ssl/server-key.pem cert /etc/mqtt-gateway/ssl/server-cert.pem
14:13:13.415 [vert.x-eventloop-thread-0] WARN  i.netty.util.internal.MacAddressUtil - Failed to find a usable hardware address from the network interfaces; using random bytes: d9:17:b6:9c:f0:4f:e6:76
14:13:13.455 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - MQTT gateway running on 0.0.0.0:8883
14:13:13.456 [vert.x-eventloop-thread-1] DEBUG enmasse.mqtt.Application - Verticle instance 1 deployed [fffc862a-55e2-4ea0-95e5-91a691c63037]
14:13:13.456 [main] INFO  enmasse.mqtt.Application - MQTT gateway startup completed successfully
14:13:13.591 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
14:13:13.601 [main] INFO  enmasse.mqtt.Application - Started Application in 1.952 seconds (JVM running for 3.148)

......

15:31:07.765 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - PUBLISH [1] from MQTT client send
15:31:15.178 [vert.x-eventloop-thread-0] ERROR io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51076 failed to connect over ssl: java.nio.channels.ClosedChannelException
15:31:25.184 [vert.x-eventloop-thread-0] ERROR io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51134 failed to connect over ssl: java.nio.channels.ClosedChannelException
15:31:27.794 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - PUBLISH [1] from MQTT client send
15:31:35.177 [vert.x-eventloop-thread-0] ERROR io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51186 failed to connect over ssl: java.nio.channels.ClosedChannelException
15:31:45.184 [vert.x-eventloop-thread-0] ERROR io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51238 failed to connect over ssl: java.nio.channels.ClosedChannelException
15:31:47.837 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - PUBLISH [1] from MQTT client send
15:31:55.179 [vert.x-eventloop-thread-0] ERROR io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51288 failed to connect over ssl: java.nio.channels.ClosedChannelException
15:32:05.182 [vert.x-eventloop-thread-0] ERROR io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51352 failed to connect over ssl: java.nio.channels.ClosedChannelException
15:32:07.880 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - PUBLISH [1] from MQTT client send
15:32:15.180 [vert.x-eventloop-thread-0] ERROR io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51410 failed to connect over ssl: java.nio.channels.ClosedChannelException
15:32:25.185 [vert.x-eventloop-thread-0] ERROR io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51464 failed to connect over ssl: java.nio.channels.ClosedChannelException
15:32:27.909 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - **PUBLISH** [1] from MQTT client send
15:32:35.244 [vert.x-eventloop-thread-0] **ERROR** io.vertx.core.net.impl.NetServerBase - Client from origin /172.17.0.1:51516 failed to connect over ssl: java.nio.channels.ClosedChannelException

#######################################################################

oc logs -c mqtt-gateway mqtt-gateway-2959230739-rh3kf : 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

14:12:43.720 [main] INFO  enmasse.mqtt.Application - Starting Application on mqtt-gateway-2959230739-rh3kf with PID 1 (/mqtt-gateway.jar started by ? in /)
14:12:43.735 [main] DEBUG enmasse.mqtt.Application - Running with Spring Boot v1.5.4.RELEASE, Spring v4.3.9.RELEASE
14:12:43.740 [main] INFO  enmasse.mqtt.Application - No active profile set, falling back to default profiles: default
14:12:43.972 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@443b7951: startup date [Fri Sep 01 14:12:43 UTC 2017]; root of context hierarchy
14:12:46.523 [main] DEBUG enmasse.mqtt.Application - Starting up 1 instances of MQTT gateway verticle
14:12:46.654 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - Starting MQTT gateway verticle...
14:12:47.587 [vert.x-eventloop-thread-0] WARN  i.netty.util.internal.MacAddressUtil - Failed to find a usable hardware address from the network interfaces; using random bytes: b9:42:61:e4:16:7b:d4:a8
14:12:47.682 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - MQTT gateway running on 0.0.0.0:1883
14:12:47.702 [vert.x-eventloop-thread-1] DEBUG enmasse.mqtt.Application - Verticle instance 1 deployed [b6bacf4e-88a9-42ee-aed7-7e5c569ee5bc]
14:12:47.702 [main] INFO  enmasse.mqtt.Application - MQTT gateway startup completed successfully
14:12:48.825 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
14:12:48.839 [main] INFO  enmasse.mqtt.Application - Started Application in 7.667 seconds (JVM running for 14.423)


#######################################################################

oc logs -c mqtt-lwt mqtt-lwt-1280706187-5b88z : 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

14:12:42.604 [main] INFO  enmasse.mqtt.Application - Starting Application on mqtt-lwt-1280706187-5b88z with PID 1 (/mqtt-lwt.jar started by ? in /)
14:12:42.616 [main] DEBUG enmasse.mqtt.Application - Running with Spring Boot v1.5.4.RELEASE, Spring v4.3.9.RELEASE
14:12:42.620 [main] INFO  enmasse.mqtt.Application - No active profile set, falling back to default profiles: default
14:12:42.756 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@443b7951: startup date [Fri Sep 01 14:12:42 UTC 2017]; root of context hierarchy
14:12:44.727 [main] DEBUG enmasse.mqtt.Application - Starting up 1 instances of MQTT LWT service verticle
14:12:44.823 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttLwt - Starting MQTT LWT service verticle...
14:12:45.745 [vert.x-eventloop-thread-0] WARN  i.netty.util.internal.MacAddressUtil - Failed to find a usable hardware address from the network interfaces; using random bytes: 61:c2:86:1b:13:69:61:c3
14:12:46.525 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttLwt - MQTT LWT service connected to the messaging service internal ...
14:12:46.571 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttLwt - MQTT LWT service connected to the messaging service ...
14:12:46.575 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttLwt - MQTT LWT service connected to the storage service ...
14:12:46.588 [vert.x-eventloop-thread-1] DEBUG enmasse.mqtt.Application - Verticle instance 1 deployed [ac10cef2-49c3-4c55-80f8-654326b635d0]
14:12:46.589 [main] INFO  enmasse.mqtt.Application - MQTT LWT service startup completed successfully
14:12:47.330 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
14:12:47.396 [main] INFO  enmasse.mqtt.Application - Started Application in 6.442 seconds (JVM running for 14.479)
14:35:10.502 [vert.x-eventloop-thread-0] WARN  i.v.proton.impl.ProtonConnectionImpl - Connection closed with error
io.vertx.core.impl.NoStackTraceThrowable: Error{condition=amqp:resource-limit-exceeded, description='local-idle-timeout expired', info=null}
14:35:11.632 [vert.x-eventloop-thread-0] **ERROR** i.vertx.core.net.impl.ConnectionBase - java.io.IOException: Connection reset by peer

#######################################################################

oc logs -c router qdrouterd-2034113809-5w0s8 : 

......

2017-09-05 15:32:40.965849 +0000 SERVER (info) Accepting incoming AMQP connection from 172.17.0.2:58976 to 0.0.0.0:5672 with connection id [58377]
2017-09-05 15:32:40.986334 +0000 SERVER (info) Accepting incoming AMQP connection from 172.17.0.2:58978 to 0.0.0.0:5672 with connection id [58378]
2017-09-05 15:32:46.250791 +0000 SERVER (info) Accepting incoming AMQP connection from 172.17.0.1:51216 to 0.0.0.0:5672 with connection id [58379]

#######################################################################

oc rsh -c router qdrouterd-2034113809-5w0s8 qdmanage query --type=address : 
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"no such file or directory\"\n"

#######################################################################

oc rsh -c router qdrouterd-2034113809-5w0s8 qdmanage query --type=connection : 
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"no such file or directory\"\n"

#######################################################################

oc rsh -c router qdrouterd-2034113809-5w0s8 qdmanage query --type=connector : 
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"no such file or directory\"\n"

#######################################################################

oc logs -c metrics qdrouterd-2034113809-5w0s8 : 

#######################################################################

oc logs -c subserv subserv-3953856722-7pmg3 : 
Tue, 05 Sep 2017 14:35:17 GMT subserv info Starting subserv
Tue, 05 Sep 2017 14:35:17 GMT subserv info Connecting to config service 172.30.53.98:5672 with id=configuration-service
Tue, 05 Sep 2017 14:35:17 GMT subserv debug opening link to configuration service...
[messaging-service] error: Error: connect ENETUNREACH 172.30.150.75:5672
Tue, 05 Sep 2017 14:35:17 GMT subserv debug disconnected undefined [messaging-service]
[configuration-service] error: Error: connect ENETUNREACH 172.30.53.98:5672
Tue, 05 Sep 2017 14:35:18 GMT subserv debug disconnected undefined [configuration-service]
Tue, 05 Sep 2017 14:35:18 GMT subserv debug connected Router.qdrouterd-2034113809-5w0s8 [connection-1]
[messaging-service] error: Error: connect ENETUNREACH 172.30.150.75:5672
Tue, 05 Sep 2017 14:35:21 GMT subserv debug disconnected undefined [messaging-service]
[messaging-service] error: Error: connect ENETUNREACH 172.30.150.75:5672
Tue, 05 Sep 2017 14:35:24 GMT subserv debug disconnected undefined [messaging-service]
Tue, 05 Sep 2017 14:35:24 GMT subserv debug connected Router.qdrouterd-2034113809-5w0s8 [messaging-service]
Tue, 05 Sep 2017 14:35:24 GMT subserv debug opened anonymous sender
Tue, 05 Sep 2017 14:35:26 GMT subserv debug disconnected undefined [connection-2]
[configuration-service] error: Error: connect ENETUNREACH 172.30.53.98:5672
Tue, 05 Sep 2017 14:35:33 GMT subserv debug disconnected undefined [configuration-service]
Tue, 05 Sep 2017 14:35:33 GMT subserv debug connected configuration-service [configuration-service]

......

Tue, 05 Sep 2017 15:22:26 GMT subserv debug disconnected undefined [connection-284]
Tue, 05 Sep 2017 15:22:26 GMT subserv debug received message: {"subject":"close","correlation_id":"$mqtt.to.recv.publish"}
Tue, 05 Sep 2017 15:22:26 GMT subserv debug close($mqtt.to.recv.publish)
Tue, 05 Sep 2017 15:22:27 GMT subserv debug close($mqtt.to.recv.publish) succeeded
Tue, 05 Sep 2017 15:22:27 GMT subserv debug received message: {"message_id":1,"subject":"subscribe","correlation_id":"$mqtt.to.recv.publish","body":{"mytopic":"1"}}
Tue, 05 Sep 2017 15:22:27 GMT subserv debug subscribe($mqtt.to.recv.publish,[object Object])
Tue, 05 Sep 2017 15:22:27 GMT subserv debug subscribe($mqtt.to.recv.publish,[object Object]) failed: Error: Unrecognised topic: mytopic
Tue, 05 Sep 2017 15:22:36 GMT subserv debug disconnected undefined [connection-285]
Tue, 05 Sep 2017 15:22:46 GMT subserv debug disconnected undefined [connection-286]
**Tue, 05 Sep 2017 15:22:48 GMT subserv debug received message: {"subject":"close","correlation_id":"$mqtt.to.recv.publish"}
Tue, 05 Sep 2017 15:22:48 GMT subserv debug close($mqtt.to.recv.publish)
Tue, 05 Sep 2017 15:22:48 GMT subserv debug close($mqtt.to.recv.publish) succeeded
Tue, 05 Sep 2017 15:22:49 GMT subserv debug received message: {"message_id":1,"subject":"subscribe","correlation_id":"$mqtt.to.recv.publish","body":{"mytopic":"1"}}
Tue, 05 Sep 2017 15:22:49 GMT subserv debug subscribe($mqtt.to.recv.publish,[object Object])
Tue, 05 Sep 2017 15:22:49 GMT subserv debug subscribe($mqtt.to.recv.publish,[object Object]) failed: Error: Unrecognised topic: mytopic**
Tue, 05 Sep 2017 15:22:56 GMT subserv debug disconnected undefined [connection-287]
Tue, 05 Sep 2017 15:23:06 GMT subserv debug disconnected undefined [connection-288]
Tue, 05 Sep 2017 15:23:16 GMT subserv debug disconnected undefined [connection-289]
Tue, 05 Sep 2017 15:23:26 GMT subserv debug disconnected undefined [connection-290]
Tue, 05 Sep 2017 15:23:36 GMT subserv debug disconnected undefined [connection-291]
Tue, 05 Sep 2017 15:23:46 GMT subserv debug disconnected undefined [connection-292]
Tue, 05 Sep 2017 15:23:56 GMT subserv debug disconnected undefined [connection-293]
Tue, 05 Sep 2017 15:24:06 GMT subserv debug disconnected undefined [connection-294]
Tue, 05 Sep 2017 15:24:07 GMT subserv debug received message: {"subject":"close","correlation_id":"$mqtt.to.send.publish"}
Tue, 05 Sep 2017 15:24:07 GMT subserv debug close($mqtt.to.send.publish)
Tue, 05 Sep 2017 15:24:07 GMT subserv debug close($mqtt.to.send.publish) succeeded

**Comment by grs** [comment]
Have you created a topic address called 'mytopic'?

**Comment by LeeWong** [comment]
./tls_mqtt_send.py -c "$(oc get route -o jsonpath='{.spec.host}' mqtt)" -p 443 -t mytopic -q 1 -s ./server-cert.pem -m "Hello EnMasse" won't create the topic address 'mytopic'? If not, how can I do so? Sorry, I am very new to the EnMasse.

**Comment by grs** [comment]
Yes, at present you do need to create the topic. The simplest way is to use the enmasse console. You can get a URL to this from the console route in the openshift console. Alternatively you can use the REST api directly, see 'configuring addresses' in https://github.com/EnMasseProject/enmasse/blob/master/documentation/getting-started/openshift.adoc

I agree that from MQTT you probably wouldn't expect to have to do anything here. The mapping of the MQTT topic space onto the more general EnMasse (AMQP) address-space is something we want to do give some more thought to. At present the base topics exposed for MQTT are those created explicitly. Another option is to have a single enmasse topic address that represents the whole MQTT topic-space (and perhaps let you choose between these)

**Comment by LeeWong** [comment]
Thank you so much for the help, @grs . After creating "my topic" via the rest api, "Hello EnMasse" is showing in the console. Do you think if this project is production-ready? Thank you.

**Comment by lulf** [comment]
@LeeWong it is by no means production-ready, but we are working towards that goal. We still have several features that we need done before we consider the project 'ready', but even then we need to do stress and performance testing, improving documentation etc. before I'd say it's production ready.

We're open for contributions in any of the above areas though.

**Comment by LeeWong** [comment]
@lulf I will start with contributing the documentation as I am getting more familiar with EnMasses. ;) What are the features that are planned for the production readiness?

**Comment by lulf** [comment]
@LeeWong Great! The past month we have currently been working on:

* Authentication of clients: https://github.com/EnMasseProject/enmasse/blob/master/documentation/design/authentication.adoc
* Authentication of internal components: https://github.com/EnMasseProject/enmasse/blob/master/documentation/design/internal-tls.adoc

This means that in the next release, you will be able to control who is allowed to connect and send/receive messages, and not able to connect to the internal components from untrusted clients.

In the next month, we will focus on some technical debt and stability issues, as well as a 'brokered' address space. The brokered address space will be a more 'light-weight' alternative to the 'standard' address space, where we only deploy a broker. This will limit scalability, but will in turn allow more advanced features such as message grouping and transactions.

After that, the priorities are more uncertain, but authorization (on individual addresses and send/receive) is something that is coming soon.

**Comment by LeeWong** [comment]
@lulf Thanks for the detailed answer. I am very looking forward to seeing how well this project will grow. l think the auto scaledown feature could be considered for the later release.
