### ISSUE TITLE
Remove incoming and outgoing link tables (brokered address space)

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1841]
In the Brokered address space, we currently don't have sufficient data to populate the incoming and outgoing link tables in a useful way.   We will remove the tables from the view for the moment.
See #1812

**Comment by k-wall** [comment]
Fixed by #1845

**Comment by RH-sdavey** [comment]
Downstream closed, issue no longer needed as tables for links have been removed. Closing now
