### ISSUE TITLE
[console] Message in/out metrics are not working with re-created topic

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1852]
**Describe the bug**
related to issue #1851 , if I delete a topic that previously had messages flowing through with sender / receiver, then create another topic with the same name and send messages again... the message in/out metrics are not working at all, that is, they stay on 0. 

**To Reproduce**
1. Create brokered addr space
2. Create brokered topic
3. Send and receive messages through topic ( metrics are not correct(as in 1851) but they are 'working' )
4. delete the topic
5. create a new topic with exact same name
6. Send and receive messages to this topic
7. Observe that the messages in/out remain on 0

**Expected behavior**
metrics for new topic with same name will be working as expected

**Screenshots**
new topic with 1000 messages sent and received.. 30 seconds before screenshot 
![image](https://user-images.githubusercontent.com/32485509/47434170-45c4cf80-d7a2-11e8-9688-b4daf415a6ec.png)

**Additional context**

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.
