### ISSUE TITLE
Inconsistent naming "senders" vs "incoming links"

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1858]
In the standard address space, when looking at an address in the Address tab, we use the word "Senders" and "Incoming links" to mean the same thing.  On the Connections tab the word "Senders" is used consistently.   Standard terminology would be best.

![inconsistentnaming](https://user-images.githubusercontent.com/18440250/47505607-5f2f4f80-d866-11e8-9a85-1e30072f0025.png)

**Comment by junezhang** [comment]
+1 for using the same terminology.
Vote for "Senders" for keeping consistent.

**Comment by k-wall** [comment]
> +1 for "Senders".
> Besides, the screen from your screenshot should belong to Addresses tab but it isn't highlighted in navigation, maybe something needs to be fixed.

This should be raised separately.
