### ISSUE TITLE
Inconsistent terminology - "Container" vs. "Container ID" vs "Id"

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1859]
In the Console, the terms "Container" vs. "Container ID" vs "Id" are all used to refer to the Container ID of the Client.  We should choose on term and use it consistently.

![inconsistentnamingcontainerid](https://user-images.githubusercontent.com/18440250/47506360-c7326580-d867-11e8-9ea7-39fffd37ad0b.png)

**Comment by jenmalloy** [comment]
My vote is for "Container ID" if space will allow

**Comment by junezhang** [comment]
+1 for the Container ID.

btw, for the Container ID,  It should be the Connection's container ID, so I'd like to know do we have any other Container ID in this page, such Router Container ID?

**Comment by yih-wang** [comment]
vote for 'Container ID'.

What do you think if we switch Container Id and Name columns. Name is the identification of an object (a row). Container ID is more like a class, and could be the same in different rows. Also, Name is the first column of tables in Connection tab. Users could match an object more easily when switching between the tabs if the first columns are same. So place Name as the first column makes more sense.

**Comment by grs** [comment]
Note that container id is an AMQP concept. In the standard space there isn't much really any support in the console except for AMQP. In the brokered space we don't actually get the container id as such. (One other possibility might be client id, but that is not entirely accurate either).

**Comment by k-wall** [comment]
> What do you think if we switch Container Id and Name columns. Name is the identification of an object (a row). Container ID is more like a class, and could be the same in different rows. Also, Name is the first column of tables in Connection tab. Users could match an object more easily when switching between the tabs if the first columns are same. So place Name as the first column makes more sense.

Note that the name of the sender or receiver need not be unique here.  Indeed, it would be legal for many different connections to have a sender or receiver called '1' attached to the same queue. This is under the AMQP client's control.  I think what we have now is already good enough.
