### ISSUE TITLE
router / ragent can get stuck in an infinite loop trying to create an address

### ISSUE THREAD

**Issue by rgodfrey** [EnMasseProject/enmasse#192]
There seems to be an issue whereby if an address is deleted and then an address witht he same name is rapidly recreated the router/ragent get into an infinite loop trying and failing to create the "new" address.

Prior to the merge of https://github.com/EnMasseProject/enmasse/pull/191 this would happen if a PUT request was made to the AddressController API containing an address list with pooled queues that was a superset of the existing list of pooled queues.  (e.g. the system has a pooled in-memory queue "q1"; a request is made against the rest API to set the addresses to be q1 and q2, both pooled in-memory queues).

The symptoms of the looping are seen as per 

[router_loop_on_create_queue.txt](https://github.com/EnMasseProject/enmasse/files/1278104/router_loop_on_create_queue.txt)
[ragent_loop_on_create_queue.txt](https://github.com/EnMasseProject/enmasse/files/1278105/ragent_loop_on_create_queue.txt)

(after the merge of https://github.com/EnMasseProject/enmasse/pull/191 the address controller no longer attempts to delete the existing queues before recreating)

**Comment by grs** [comment]
I believe this is a router bug: https://issues.apache.org/jira/browse/DISPATCH-821

**Comment by lulf** [comment]
Closing as the router issue is closed
