### ISSUE TITLE
Add ability to select any pod by label component

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1941]
## why
Add ability to select any  pods by label  component, as well as name when using oc commands with label selector

## Proposal

At the moment, if I wish to use oc command to perform an action on a pod, I can select almost all pods by "-l name=<name_here>"
however, api-server does not have this label, and must be selected by "-l component=<name_here>
- oc delete pod -l name=keycloak-controller
- oc delete pod -l component=api-server

I believe this could be confusing to end user. 
Please make it possible to select all components by "-l component=" as well as "-l name="

## Testing
Systemtests can be created to differentiate between the two selectors. 

## Documentation
This should be documented. ( I am already creating a new jira with few issues for d/s docs, and will put this as a point in the jira )

**Comment by lulf** [comment]
Api server is removed.
