### ISSUE TITLE
Allow setting the X-FRAME-OPTIONS and Content-Security-Policy for auto-created realms

### ISSUE THREAD

**Issue by david-martin** [EnMasseProject/enmasse#1953]
## why

We have a Walkthroughs webapp that takes a user through multiple tasks for integrating different services to solve a larger problem.
EnMasse is one of those services.
We've been progressing some spikes around showing the different services alongside the walkthrough steps in an iframe. e.g. when I get to the task that has EnMasse bits, we open the EnMasse console in an iframe.

## Proposal

Allow configuring what values are set for the X-FRAME-OPTIONS and Content-Security-Policy whenever a new Realm is created for an Address Space.
See https://www.keycloak.org/docs/3.2/server_admin/topics/threat/clickjacking.html for more info

> What are the components involved in this change and how will they change?

Probably the keycloak controller, when a realm is created?

> Describe any new components introduced by this change

None proposed.

## Testing

> What is the test plan for the feature/change?  

Configure EnMasse to set the headers to specific values .
Create a new Address Space (which will create a new Realm in Keycloak with those header values)
Create a simple webpage that has an iframe with src set to this EnMasse instance.
Verify the iframe loads correctly.

## Documentation

> What documentation will be created for this feature? 

How to configure EnMasse to set these default realm settings

## Tasklist

> Enumerate the tasks required to complete the feature

I'll leave this to someone more familiar with the project

**Comment by lulf** [comment]
@david-martin Would something like running this work: `oc patch configmap keycloak-config -p '{"data":{"browserSecurityHeaders":"{\"X-FRAME-OPTIONS\":\"opts\"}"}}'`

I've facing some issues applying the headers using the keycloak java client, so still not ready. We're thinking to create a 0.24.1, will you be ok with this going into 0.25.0 instead?

**Comment by david-martin** [comment]
> Would something like running this work

Yes, I'd be happy with any way that makes it possible currently.
And patching a configmap is a pretty reasonable way.


> will you be ok with this going into 0.25.0 instead

No issue here. 0.25.0 sounds good.

Thanks for the quick response
