### ISSUE TITLE
Docs: Add step to creating users procedure

### ISSUE THREAD

**Issue by jenmalloy** [EnMasseProject/enmasse#1959]
In all sections re: creating users, there should be an extra code section to show how to list the new user created, eg: oc get messagingusers

**Comment by RH-sdavey** [comment]
@jenmalloy 
Update with "oc get messagingusers" command looks fine to me, thanks for that, one quick point... the sections 
2.1.5. Creating users using the command line   and
4.10.1. Creating users using the command line
are identical, as are, 
2.1.4. Creating addresses using the command line
4.6.2. Creating addresses using the command line

just an enquiry if thats the best way? or if it would be better to have a link from one section (2.1.5) to the other (4.10.1) instead. 

tested with latest docs on staging link.

**Comment by jenmalloy** [comment]
@RH-sdavey, this is necessary because one is for the Getting Started (or nonproduction scenario) content, and the other one for the production scenario. (We could split this content out into separate books, but since it's already split out by platform, the number of books would quickly multiply to 6, which is a much larger burden to maintain than I think we're prepared to handle at this point.)
