### ISSUE TITLE
Docs: qdstat procedure fix

### ISSUE THREAD

**Issue by jenmalloy** [EnMasseProject/enmasse#1961]

**Comment by jenmalloy** [comment]
PR: https://github.com/EnMasseProject/enmasse/pull/1962

**Comment by RH-sdavey** [comment]
Hi Jen, thanks for updates, the new commands for qdstat are perfect, just what we needed...
but the output blocks are not looking so good  :/
![image](https://user-images.githubusercontent.com/32485509/48398711-d8adb580-e721-11e8-9e87-dc73e7923bb2.png)
the user can definitely get the correct results layout by running the command his machine, 
![image](https://user-images.githubusercontent.com/32485509/48398877-5a9dde80-e722-11e8-9dd5-7083a2da299f.png)
so I dont know if theres much you can do, as I suppose there is some styling restrictions on how wide you can have these code blocks right?  jsut wondering if theres anything that can be done about weird outputs. (all tables in qdstat are the same)
