### ISSUE TITLE
Getting started : explicit project creation isn't needed

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse#2]
The step related to project creation: 

oc new-project enmasse

seems to be useless if the line related to run the deployment script has -p "enmasse".
Of course the script works but provides this line : 

Using project "enmasse".
Error from server: project "enmasse" already exists

What do you think to remove the extra step of explicit creation of the "enmasse" project with new-project command outside of the script ?

Even because the script creates a project in any case with DEFAULT_OPENSHIFT_PROJECT name if -p option isn't used.

**Comment by lulf** [comment]
Forgot to close this. This should be fixed a while ago.
