### ISSUE TITLE
Standardize on UTC date/time stamps in logs.

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#2003]
Current the NodeJS based components log using with UTC based timestamps (2018-11-19T14:32:58.102Z), the Java based components use a timezone based on server local time (2018-11-19 14:37:21).

Problem diagnosis would be easier in all timestamps used UTC.  Switch the Java based components to datestamp in the same format to the same precision.

**Comment by grs** [comment]
@k-wall yes, I've raised a new issue, shoul not be hard to fix this: https://issues.apache.org/jira/browse/DISPATCH-1187

**Comment by kornys** [comment]
@lulf Serivce-broker still use old pattern
