### ISSUE TITLE
Changing address (space) plans

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2004]
## why

One much desired feature of EnMasse is to be able to dynamically change the plan of address space plans and address plans. This applies only to the `standard` address space type in the first instance, since there are not plan limit enforcement or scaling performed in the `brokered` address space.

### Address space plans

Changing the address space plan (i.e. from `standard-small` to `standard-medium`) need to happen without losing data. Making sure that the address space plan change is applied is the responsibility of the address-space-controller. The AddressSpace should have an annotation `enmasse.io/applied-plan` that tracks the currently applied plan, vs. the 'desired' plan specified in `.spec.plan`.

#### Scaling up

Moving from a 'small' to a 'larger' plan involves increasing the number (until we have some way of enforcing address space level quotas) of `min routers` specified by new plan. Alternatively, if we merge #1917, we don't need to think about this as its part of the infra config instead.

#### Scaling down

Moving from a larger plan to a smaller one should be possible assuming the amount of currently used resources can fit in the new plan. If the amount of used resources can fit the new plan, we should catch this in the api-server or the address-space-controller. We can either

a) Reject the plan change in api-server and tell the user to try again when resource consumption is reduced
b) Accept the plan change in api-server, but have address-space-controller set a status error message on the address space resource explaining why it can't change the plan. The address-space-controller will then apply the plan change as soon as resource usage is below the limit.

### Address plans

Changing the address plan for `anycast` and `multicast` address types does not require any broker changes, only that quota is checked and have the change rejected by standard controller if the new plan is above quota limits.

In general, for "stateful" address types, the following changes are needed:

* Add `enmasse.io/applied-plan` annotation to `Address` resource to indicate the current plan in use
* Update standard-controller to check `enmasse.io/applied-plan` against `.spec.plan` and start the
  migration process.
* Add a new phase 'Migrating' to indicate data "migration" is in progress
* If quota won't allow the migration, don't do anything and add error message to address status
* Deprecated the `enmasse.io/broker-id` annotation and introduce an array `.status.brokers`
  containing the list of brokers managing that address. The `.status.brokers` array would contain
  the following objects: `{.id="same value as old annotation", .state=Active|Draining}`
* Use `.status.brokers` for sharded queues as well, i.e. change standard-controller to treat pooled and sharded queues in the same way in terms of 'allocating' brokers (separate deployments for sharded). This means that a queue sharded over 2 brokers would have two brokers in the array, belonging to the same deployment. 

#### Queues

For the `queue` address type, allocation changes can be done by creating new brokers and marking the old to be decomissioned when no longer active. 

Moving from a `standard-small-queue` to a `standard-medium-queue` may cause the need to allocate one or more brokers. The following changes can be made to allow that to happen reliably:

* Standard-controller: If new plan can fit within the existing broker, just update applied-plan
* Standard-controller: If new plan requires moving to another broker, set the `.status.phase` field of the Address to
    `Migrating`, update the `.status.brokers` list with the current broker state set to `Draining`,
    and add the new broker(s) to the list. 
* Agent: for addresses in `Migrating` phase, the agent will delete the router incoming traffic
  autolinks on brokers in Draining state.
* Agent: for addresses in `Migrating` phase and number of messages in queue is 0, delete the router outgoing traffic autolinks
* Standard-controller: Delete brokers containing no addresses or where addresses addresses are all
  Draining on that broker and without any active autolinks on the router (in both directions).
  Remove broker from address list.
* Standard-controller: For addresses in `Migrating` phase with not brokers in Draining, move back to
  `Active` phase and update applied-plan.

The above procedure should work moving from a pooled to a sharded queue and back.

### Topics

When a topic is scaled up, it may need to switch to a different set of brokers. The process will work the same as for queues, with brokers being marked as Draining for the address which is going to be moved to another address. All durable subscriptions of a topic must also migrate to the new broker. This may cause ordering issues in the same way as for queues.

* Standard-controller: If new plan can fit within the existing broker, just update applied-plan
* Standard-controller: If new plan requires moving to another broker, set the `.status.phase` field of the Address and all subscriptions for topic to
    `Migrating`, update the `.status.brokers` list with the current broker state set to `Draining`,
    and add the new broker(s) to the list. 
* Agent: for topics in `Migrating` phase, the agent will delete the router incoming linkRoute/autolink on brokers in Draining state.
* Agent: for durable subscriptions in `Migrating` phase and number of messages for subscription is 0, delete the router outgoing traffic autolinks
* Standard-controller: Delete brokers containing no topics and subscriptions, or where topics and subscriptions are all
  Draining on that broker and without any active linkroutes+autolinks on the router (in both directions).
  Remove broker from address list.
* Standard-controller: For addresses in `Migrating` phase with not brokers in Draining, move back to
  `Active` phase and update applied-plan.

### Durable subscriptions

Changing the plan of a durable subscription is possible as long as its within the range of the topic credits (as today). There should not be any need for migrating a durable subscription from scaling up. Only when the topic plan is changed, the subscription may need to be migrated to a different broker.

For scaling down, a durable subscription may be moved to a different broker, in which case the same steps as for a queue should apply.

## Testing

What is the test plan for the feature/change?  

## Documentation

What documentation will be created for this feature? 

## Tasklist

For changing address space plans:
- [ ] Add applied-plan annotation on address space and allow plan field to change
- [ ] Check quota to determine if new plan can be applied
- [ ] Add phase field for address space status which can be Active or Pending (if not created or while plan change is taking effect).
- [ ] Apply new plan and change annotation when sucessful
- [ ] Allow plan field to be changed in rest api

For changing plans for queues
- [ ] Move broker assignment to `.status.brokers[]` where the field `status.brokers[].id` is the expected broker id, and change agent to first look for .status.brokers[] before looking for the annotation (for backwards compatibility)
- [ ] Change standard-controller to write `.status.brokers[]` field.
- [ ] Add new field .status.brokers[].state which can be Active, Draining
- [ ] Add `applied-plan` field to address annotation and set it when changing plan
- [ ] Allow plan field to be changed in rest api
- [ ] Set address draining state when plan is migrated to other broker
- [ ] Cut off incoming links for migrating addresses

**Comment by k-wall** [comment]
For migration of addresses, do i understand that EnMasse itself won't actively move messages but instead await the application's natural behvaviour to completely drain a queue but the migration will be completed?

**Comment by lulf** [comment]
> 
Is this a feature that would be supported during production runtime? e.g. support dynamic scale up/down use cases in sympathy with customer demand profile.

Yes, though it will be triggered by explicitly changing the plan and not auto-changes, though I imagine we can build that on top of thia

**Comment by rgodfrey** [comment]
For subscriptions I don't think we can ever "migrate" the subscription, as we'll risk losing messages (or getting dupes).  We can make an "indicative" plan change which would either make more logical space available on a broker, or reduce the logical space... but obviously if you scale up you might find that the allocated logical space on a broker now exceeds 1.0 ... and potentially there is nothing you can do about that.  

For topics without active subscribers, scaling up is easy I think.  Conceptually even scaling up a pooled topic is easy - is there any reason why we can't have two brokers each with a 0.5 "shard" of a topic?  Scaling down is more difficult when it gets to the point where we want to remove a broker from the topic... If there are any subscribers on that broker we obviously can move them without killing the client.  Is there some way we can prevent new subscribers connecting though?

**Comment by rgodfrey** [comment]
> > Is this a feature that would be supported during production runtime? e.g. support dynamic scale up/down use cases in sympathy with customer demand profile.
> 
> Yes, though it will be triggered by explicitly changing the plan and not auto-changes, though I imagine we can build that on top of this

@k-wall Yes, my thought is that "auto-scaling" is actually a good bit more complicated than just looking at metrics like CPU / memory / disk.  By allowing for addresses/spaces to be scaled through updating plans, "auto" scaling can be achieved by having a monitoring process which explicitly calls the plan changing process.  The most effective scaling is probably achieved by pre-empting anticipated high level of demand, rather than waiting until they are already high.  You also want to avoid scaling up/down too frequently as these will not be costless operations

**Comment by grs** [comment]
> is there any reason why we can't have two brokers each with a 0.5 "shard" of a topic?
You need to ensure that all messages published go to both brokers (currently that is done for shared topics by having durable subscriptions between them with a simple loop prevention).

**Comment by lulf** [comment]
> For subscriptions I don't think we can ever "migrate" the subscription, as we'll risk losing messages (or getting dupes). We can make an "indicative" plan change which would either make more logical space available on a broker, or reduce the logical space... but obviously if you scale up you might find that the allocated logical space on a broker now exceeds 1.0 ... and potentially there is nothing you can do about that.
> 
> For topics without active subscribers, scaling up is easy I think. Conceptually even scaling up a pooled topic is easy - is there any reason why we can't have two brokers each with a 0.5 "shard" of a topic? Scaling down is more difficult when it gets to the point where we want to remove a broker from the topic... If there are any subscribers on that broker we obviously can move them without killing the client. Is there some way we can prevent new subscribers connecting though?

I think if we had some way to shard the subscriptions, we could get around it by creating the scaled-up subscription on a new broker in the pool for instance.

We could then set up some forwarder like the topic-forwarder or using core bridges maybe to forward messages for those subscriptions to the new shard. For scaling down, I guess we would do the same thing + drain and decomission old broker?

I keep thinking it would be really nice if the router could multicast to the brokers :/

**Comment by lulf** [comment]
@EnMasseProject/dev i've updated the proposal to include topics /subscriptions as well. Changing the topic plan may cause durable subscriptions to be moved, in which case they are drained in the same way as queues. However, I think preserving the ordering is somewhat a larger effort that I'm not sure we can solve in the current architecture. 

Changing the plans of a subscription I think will not require any data migration, because it is anyway restricted by the topic credits, so I think that will just work. There might be a case where scaling down from a durable subscription spanning 2 brokers to 1 broker might need some kind of draining in the same case as for a queue i guess.

**Comment by k-wall** [comment]
One orthogonal thought.   It should be possible for the user to understand the progress (or lack of it) on their change addressspace/space request.  We should have the controllers emit events about the migrations so that the user can do this in a standard manner.

**Comment by rgodfrey** [comment]
> > is there any reason why we can't have two brokers each with a 0.5 "shard" of a topic?
> 
> 
> You need to ensure that all messages published go to both brokers (currently that is done for shared topics by having durable subscriptions between them with a simple loop prevention).

@grs - sure, my point was that conceptually a topic of size "1" could be represented by two shards of size 0.5... from an AMQ Online / router configuration point of view this looks exactly like a topic of size "2", and the only difference is really about where durable subs might be placed.  For non-durable subs, I don't believe we currently have a way of refusing subscriptions once we believe some notion of "quota" is used up... similarly we don't have a way of controlling which broker the consumer is actually attached to (so dividing into shards of 0.9 and 0.1 wouldn't make any sense, unless we were only expecting durable subs to that topic)

**Comment by lulf** [comment]
Done
