### ISSUE TITLE
Unable to use generated Kubernetes Go client informer with "AddressSpace" resource

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#2074]
**Describe the bug**

It look to me as if it is not possible to use the Kubernetes generated Go client information implementation to list `AddressSpace` resources.

Instantiating a new informer fails with the follow error when refreshing:

~~~
E1203 14:46:50.687772 1 reflector.go:134] github.com/enmasseproject/enmasse/pkg/client/informers/externalversions/factory.go:107: Failed to list *v1alpha1.AddressSpace: RESTEASY003210: Could not find resource for full path: https://172.30.0.1:443/apis/enmasse.io/v1alpha1/addressspaces?limit=500&resourceVersion=0 
~~~

**To Reproduce**
1. Generate Go client resources
1. Instantiate Informer and list

**Expected behavior**

Kubernetes generated Go resources seems to support this operation. My expectation would be that EnMasse supports this as well.

**Comment by lulf** [comment]
From the rest URL it tries to access address spaces as a cluster resource, but address spaces are namespaced. Is there a way to configure the informer with a namespace?

**Comment by ctron** [comment]
No the resource is Namespaced. However the default query options use `NamespaceAll`, which is the same as `NamespaceNone` and documented as:

~~~go
// NamespaceAll is the default argument to specify on a context when you want to list or filter resources across all namespaces
~~~

So it might be that "all" and "none" are handled the same way, and it simply looks like a non-namespaced request. Which would make sense to some degree.
