### ISSUE TITLE
[Docs] Change example and  Add note to 2.1.5. Creating users using the command line procedure

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#2082]
It would be good to add a note to 2.1.5. Creating users using the command line section
to explain how to correctly base64 encode a password for the user template file.

`echo -n password | base64 `    #cGFzc3dvcmQ=
is the correct way, if the user executes
`echo password | base64 `   #cGFzc3dvcmQK
they will get a different base64 encoded password, and thus, wont be able to login to enmasse.

also--

the example shown will be better if changed to show that "manage" permissions or a global option rather than per address setting, as this is not clear from current documentation. 
for example, 
![image](https://user-images.githubusercontent.com/32485509/49451693-0b5a4380-f7e0-11e8-8cd5-dbfde64cc1cf.png)

**Comment by jenmalloy** [comment]
PR: https://github.com/EnMasseProject/enmasse/pull/2625

**Comment by jenmalloy** [comment]
PR merged
