### ISSUE TITLE
[standard] Address space has status ready even if second qdrouter pod is not ready

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#2095]
**Describe the bug**
AddressSpaceStatus is set to ready but second qdrouter pod is still in not ready state.

**To Reproduce**
1. Deploy standard address space
2. check ready status of address space and qdrouter pods

**Comment by k-wall** [comment]
I still see this issue testing with 0.28.1 with a standard-unlimited   standard address space.  I see the addressspace go ready before the second router pod itself is marked ready.

**Comment by lulf** [comment]
This is on purpose. Multiple routers are there for redundancy, and everything functions with 1 router.
