### ISSUE TITLE
AuthenticationService doesn't implement hashCode/equals

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#2104]
**Describe the bug**
To me it looks like as if the authentication service is missing an implementation to `hashCode`/`equals`, but the change validation makes use of `equals`:

https://github.com/EnMasseProject/enmasse/blob/18948435b1be1defed135697bdecec6943c918d4/api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java#L180

https://github.com/EnMasseProject/enmasse/blob/18948435b1be1defed135697bdecec6943c918d4/address-model-lib/src/main/java/io/enmasse/address/model/AuthenticationService.java#L15-L53

**Comment by ctron** [comment]
This makes it impossible to update the resource:

~~~
Error from server (Bad Request): error when replacing "/tmp/oc-edit-t91r3.yaml": Cannot change authentication service of address space default from io.enmasse.address.model.AuthenticationService@7724473f to io.enmasse.address.model.AuthenticationService@3ff0dc56
~~~

**Comment by lulf** [comment]
PR merged
