### ISSUE TITLE
Unable to modify MessagingUser

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#2119]
**Describe the bug**

Modifying a MessagingUser currently is not possible, at least not in a "get, modify, store" way.

**To Reproduce**
1. Create MessagingUser
1. Read MessagingUser
1. Make change to 
1. Store
1. BANG

This results in:

~~~
Error from server (Bad Request): error when replacing "/tmp/oc-edit-k4y5b.yaml": java.lang.NullPointerException: 'password' must be set for 'password' type
~~~

The cause for this seems to be the fact that, when reading the messaging user, you do not get the password. The internal Keycloak API layer accepts the fact that the password is missing, but the `validate` method of the `User` object requires this. And this is checked before the actual storing takes place.

**Expected behavior**

It should be possible to update the MessagingUser in this way.

**Propose solution**

I think this should be solved by letting the actual "create" method check for the existence of the password, instead of the model. As the model may transport `null` in this field. The server itself reports back with a model that wouldn't validate, it is omits the password.

**Comment by lulf** [comment]
@ctron If you remove the 'authentication' field it should work. When it is set, it is assumed that you want to update the password. Though I agree perhaps the logic should be a bit more permissive.

**Comment by lulf** [comment]
Fixed on master
