### ISSUE TITLE
Ragent test failure

### ISSUE THREAD

**Issue by LeeWong** [EnMasseProject/enmasse#214]
Hi,

I tried to run build with the latest changes and hacking tutorial but encountered the following test failures:

make
make FULL_BUILD=true -C ragent 
make[1]: Entering directory '......./enmasse/ragent'
mkdir -p build
Nothing to build
MOCHA_FILE=build/test-results/test/TEST-ragent.xml mocha 

  basic router configuration
    1) "before each" hook for "configures a single anycast address"

  address source subscription
    2) subscribes to configuration service
    3) subscribes to admin service on configuration port
    4) prefers configuration service over admin service

  tls options
    ✓ uses correct default path for ca
    ✓ uses correct default path for cert
    ✓ uses correct default path for key
    ✓ uses CERT_DIR in determining path for ca
    ✓ uses CERT_DIR in determining path for cert
    ✓ uses CERT_DIR in determining path for key
    ✓ uses CA_PATH as path for ca
    ✓ uses CERT_PATH as path for cert
    ✓ uses KEY_PATH as path for key

  9 passing (22s)
  4 failing

  1) basic router configuration "before each" hook for "configures a single anycast address":
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) address source subscription subscribes to configuration service:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  3) address source subscription subscribes to admin service on configuration port:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  4) address source subscription prefers configuration service over admin service:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

../Makefile.common:18: recipe for target 'mocha' failed
make[1]: *** [mocha] Error 4
make[1]: Leaving directory '....../enmasse/ragent'
Makefile:23: recipe for target 'ragent' failed
make: *** [ragent] Error 2

Cheers.

**Comment by ppatierno** [comment]
Hi @LeeWong,
do you have the npm "debug" package installed ? It happened to me as well and it was the reason for the failure.

**Comment by LeeWong** [comment]
HI @ppatierno , after I uninstalled debug package, I am still seeing the same errors.

**Comment by rgodfrey** [comment]
I experienced similar test failures previously when there were processes already listening on ports used by the test.  IIRC the test opens up listeners on ports 55672 and 8888 and may silently fail if one of those is already bound to another process.

**Comment by LeeWong** [comment]
I double checked the environment to see if either 55672 or 8888 is used by another process. However, none of them is used. I have to dig deeper. Thanks, @rgodfrey

**Comment by LeeWong** [comment]
With the latest changes, the build failure on ragent is gone. Thanks for fixing it.
