### ISSUE TITLE
Address space creation/deletion time

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2150]
Creating an issue for this to track the time spent creating/deleting standard address spaces in different configurations, and some considerations on how we can speed it up a bit, mainly to improve systemtest execution time.

| Num routers | Mqtt enabled | Router metrics side car enabled | Address space create time (seconds) | Address space delete time (seconds) |
| --- | --- | --- | --- | --- |
| 2 | yes | yes | 105 |  112 |
| 2 | yes | no | 77 |  61 |
| 2 | no | yes | 82 | 77 |
| 1 | no | yes | 77 | 53 |

From the above, the largest gains can be made in the deletion time, either by removing the router metrics side car, or using only 1 router. The latter configuration has some HA implications, but most systemtests don't need to use 2 routers.

### Router metrics side-car

At present we run a router-metrics container as a side-car to the qpid dispatch router container. There have been some issues where configuring prometheus to poll for its metrics would cause it to fall over.

Moreover, address space create/delete time is 35%/85% slower when keeping it, mainly due to pod deletion being slow when running > 1 containers that may not exit at the same time (see https://github.com/kubernetes/kubernetes/issues/60518 for details).

One option is to remove the sidecar for now and longer term try to get some sort of native 'plug-in' for the router that exposes the metrics instead of running the side car.

**Comment by k-wall** [comment]
As router metrics are now an inbuilt feature of the Broker, the body of this issue becomes moot.  Closing
