### ISSUE TITLE
JSON empty addresses list should be represented by an empty array

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse#216]
I have noticed that invoking a GET operation on the address REST API when there are no addresses defined, I received the following : 

`{"apiVersion":"enmasse.io/v1","kind":"AddressList"}`

Maybe it could be better having the "items" field as where with an empty array as a value so : 

`{"apiVersion":"enmasse.io/v1","kind":"AddressList","items":[ ]}`

For completeness and clarity.
What do you think ?

**Comment by lulf** [comment]
I agree, this is how its done for kubernetes resources in general
