### ISSUE TITLE
Not possible to create any other address after creating Large Queue in standard-small addr space 

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#2172]
**Describe the bug**
After creating standard-small address space, and there creating 1 large-queue, it is not possible to create any other addresses, any addresses attempted to be created are stuck in 'Pending' status. 
Vice versa, you can create any other queue size ( medium or small ) and then attempt to create a large queue and it will be stuck in pending state. No dedicated broker pods are being are being created. 

I can understand why this may be happening due to restrictions on resources/credits when creatinga  standard-small addr space but I would expect maybe some warning when trying to create the doomed addresses. **Or the possibility of not being able to create anything that would exceed the remaining resource limitations.** 

at the very minimum this could be mentioned in docs as a known limitation. 

**To Reproduce**
1. create a standard-small address space
2. create a large-queue
3. observe the broker pod is initialized and running => address is ready
4. try to recreate another address of any type or size
5. address is stuck in pending state
6. alternatively try to create an address ( any type/size ) first, then create a large queue

**Comment by lulf** [comment]
@RH-sdavey yes, this is expected behavior. If you do oc get addresses -o wide you should see an error message stating quota exceeded for the addresses in Pending.

I agree we should improve the documentation on how the plans and credit system works for the standard address space.

**Comment by RH-sdavey** [comment]
ah understood, ( wanted to ask you but I didnt see you online on gchat )  I will close this issue and create a docs issue first thing a.m tomorrow, thanks for explanation
