### ISSUE TITLE
Possible to replace address plan with any other type of address

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#2176]
**Describe the bug**
its possible to replace an existing address plan with any other type of plan, for example I can create a queue, edit the address plan definition yaml, then use "oc replace -f myEditedAddress.yaml" to change that queue to any other type of address/plan. Potentially this could lead to lost messages, for example when changing a queue to a topic. 

**To Reproduce**
1. create a queue address plan  ( standard-small-queue.yaml )  
2. oc create -f standard-small-queue.yaml  => small queue created, and ready
3. send x messages to the queue => messages sent and stored
3. edit standard-small-queue.yaml, changing the address type and plan from queue to topic
4. address is changed to topic, and messages are dropped/lost

**Expected behavior**
api server should reject attempt to change the address type

**Comment by lulf** [comment]
I find the description of the bug is slightly confusing. 

Changing the address type and plan of an address gives me the eerror 'Cannot change type of address foo from queue to topic'. 

Is this the bug being reported or is it that you change the 'addressType'  of the address plan standard-small-queue?

**Comment by RH-sdavey** [comment]
@lulf sorry it seems I missed a step between 4 and 5 in reproducing to "oc replace -f standard-small-queue.yaml", however, that doesnt seem to matter, 
as I cant reproduce it at all now, Im seeing the same output as you mentioned in your comment. 
So I will say this issue is no longer required, I will try to reproduce it a few more times to see if theres anything I missed, if not, I will go ahead and close this issue.

**Comment by lulf** [comment]
Yeah, this enforcement was added in december sometime i think
