### ISSUE TITLE
[console] show which topic a subscription is for

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#2268]
## why
in the console, it is not currently possible to see which topic a subscription is for. I believe this is a useful feature that would benefit the end user. 
This information is currently available from command line [1], and could be useful also in the console.

## Proposal
Upon Subscription creation, the console could display ( inside the twisty dropdown for the address ) which topic it is a subscription for. 

## Testing
This could be tested easily with existing systemtests web tests 

## Documentation
Documentation update should not be needed for this change

[1]
![image](https://user-images.githubusercontent.com/32485509/51900219-0adfc280-23b5-11e9-87a3-f0021496039f.png)

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced. The new console has this feature.
