### ISSUE TITLE
[console] Message in/out metrics are not working with re-created subscription

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#2273]
**Describe the bug**
If I delete and then recreate a subscription with exactly the same name and plan, any messages that are sent to the topic and forwarded on to the new subscription are not reflected in the messages in/out field in console, the values stay on 0. 

**To Reproduce**
1. create standard addr space
2. open console
3. create a topic and subscriber for that topic
4. send messages to the topic --> successfully sent and forwarded to the sub ( messages in is correct )
5. delete subscription, and recreate with same name/plan
6. send messages to the topic ---> successfully sent and forwarded ( messages in stays on 0 ) 

**Expected behavior**
messages in will reflect the correct messages sent on recreated subscription

**Additional context**
I suspect its the same root cause as #1852

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.
