### ISSUE TITLE
[console] possible to create subscription without topic in console

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#2275]
**Describe the bug**
Using identical technique from #1498 it is possible to create a subscription without a selected topic.
(sub is stuck in permanently pending state) 
I believe this is not critical, but rather an example of how its possible to subvert the address modal wizard rules.

**To Reproduce**
1. create standard addr space
2. open console and login
3. click on create > enter topic1 for name > select topic > click next > click next
4. when on summary page, click on the number 1 icon above the summary
5. select subscription, dont enter anything for the topic
6. click on number 3 icon to take you directly back to the summary ( skipping step 2 ) 
7. click create --> address is shown and stuck in pending
 
**Expected behavior**
the subscription should not be able to be created without a topic entered

**Screenshots**
![image](https://user-images.githubusercontent.com/32485509/51916234-2e1e6800-23dd-11e9-88b6-30bed168aed8.png)
![image](https://user-images.githubusercontent.com/32485509/51916258-3d051a80-23dd-11e9-8808-d1efcc895c43.png)

**Additional context**
related to closed #1498

**Comment by rgodfrey** [comment]
Is this purely a console issue, or should we not validate this in the backend and simply fail to create this address with an error?

**Comment by RH-sdavey** [comment]
@rgodfrey sorry, just caught this comment Rob, I believe this is only possible through console, I cant recreate it using cli/api at all. Its basically the silly 'trick' with pressing the 1,2,3 buttons rather than the 'next' button. same as #1498.

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced..  What's more, the controller on the back validate that the subscription is valid and put the address into a appropriate if it is not.
