### ISSUE TITLE
[console] when idle for x hours, the address metrics (messages in/out) don't work properly

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#2283]
**Describe the bug**
When left idle for x amount of hours ( only tried with 8 hours between two business days ) then the console messages in/out address metrics dont work, that is, they stay on 0 messages in/out no matter how many messages are sent and received to any address type

**To Reproduce**
1. create standard address space ( didnt test yet with brokered ) 
2. open console and create one of each address, (queue and topic tested so far ) 
3. send messages to the these addresses --> all metrics fine
4.  leave console idle (possibly whole enmasse deployment) idle for ~8 hours
5. send messages to the addresses ---> stored messages increases, messages in/out does not, (0)

**Expected behavior**
When console is used after x hours of being idle, the metrics will continue to work as expected

**Screenshots**
all these addresses have messages sent and received within the previous 2-3 minutes,
![image](https://user-images.githubusercontent.com/32485509/51989166-bae12880-24a6-11e9-9886-377664a50c67.png)

**Additional context**
This may be part of a larger problem where the whole console ( connections tab, address 'twistys', create button ) are unresponsive after the console is left idle for some time, or ive also observed it when there has been some "pushing" the application from api/cli from my side, trying to stress the application  (creating many addresses a the same time, sending millions of messages etc ), the console can become unresponsive until a page refresh. Due to the nature of this, it can be quite hard to recreate every time, but it is possible very often.

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.
