### ISSUE TITLE
Kubernetes console docs should mention the need to create an admin user

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2345]
**Describe the bug**
The Kubernetes install requires an admin user to be created in order to reach the console. This should be documented.

**To Reproduce**
1. Install EnMasse on Kubernetes
2. Follow steps http://enmasse.io/documentation/0.26.2/kubernetes/#assembly-using-console-messaging
3. Unable to access the console. 

**Expected behavior**
For the Kubernetes doc, I would expect an instruction to create an admin user with console access.

**Comment by k-wall** [comment]
Superseded by #2919, closing
