### ISSUE TITLE
Upgrade nodejs from 6 to 8 or 10

### ISSUE THREAD

**Issue by vbusch** [EnMasseProject/enmasse#2372]
Nodejs 6 is EOL in April https://github.com/nodejs/Release
We should upgrade to 8 or 10.

**Comment by kornys** [comment]
do we know if scl repo contains nodejs 8/10 ?

**Comment by vbusch** [comment]
Yes, both 8 & 10 are available.

**Comment by lulf** [comment]
I think we should attempt to upgrade to 10 first, then fallback to 8 if there are significant work needed to support 10.

**Comment by lulf** [comment]
Done
