### ISSUE TITLE
User annotations on address spaces and address can be added or updated but not removed.

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#2398]
The AddressSpace and Address APIs allow the user to put arbitrary metadata annotations on the objects.  This presumably to allow the user to add business domain specific annotations to drive business process etc.

```

```

Currently, the user can add or change annotations via the replace operation (and now patch), but removal is disallowed.  This seems to be a defect.

EnMasse ought to continue to protect is own annotations from modification, but allow the user to add/change/remove others without restriction.

_Originally posted by @k-wall in https://github.com/EnMasseProject/enmasse/pull/2369#issuecomment-469157179_

**Comment by lulf** [comment]
I think this is fixed with the move to CRDs.
