### ISSUE TITLE
Image versions in YAMLs in 0.26.3 release zip set to 0.26, not 0.26.3

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#2417]
In the YAML files in the install directory of the 0.26.3 release zip, the image versions don't contain the full version string anymore, ie. the image version is set to 0.26 instead of 0.26.3.

````
$ cd install/components/address-space-controller/ && grep -R 'docker.io/enmasseproject/agent'
020-ConfigMap-address-space-definitions.yaml:              image: docker.io/enmasseproject/agent:0.26
020-ConfigMap-address-space-definitions.yaml:              image: docker.io/enmasseproject/agent:0.26
020-ConfigMap-address-space-definitions.yaml:              image: docker.io/enmasseproject/agent:0.26
````
The 0.26 image version exists on Dockerhub and seems to have been updated for 0.26.3.
But, as the `imagepullpolicy` is set to `always`, this could lead to EnMasse components in one cluster using different versions. This would happen when a new EnMasse version is released along with an update of the 0.26 image on Dockerhub and when only one pod in the cluster gets restarted, thereby already pulling the new image while the other pods still use the older version.

**Comment by lulf** [comment]
@calohmn This was intentional, and the idea is that micro releases of EnMasse only contain critical bug and security fixes that:

1. Require no changes to templates
2. Each component may be updated individually

To upgrade micro releases, the thought is that a simple component restart should be enough. 

However, if you think this is confusing and bad policy, we can probably change it back to use full version.

**Comment by calohmn** [comment]
Ok. Yes, upside would be easier updates, downside would be not seeing the actual image version.
I guess, the easier updates are more important here.

Another potential disadvantage could be that in the case of a Dockerhub downtime, EnMasse components wouldn't restart during that time because of the `imagePullPolicy: Always` setting (would cause an `ErrImagePull` status).

**Comment by lulf** [comment]
@calohmn Thinking more about this, I wonder if we should change it back to the previous behavior. I would imagine that having multiple ways to do updates is not very common. I think the downsides warrant us to consider changing it.

CC @EnMasseProject/dev

**Comment by lulf** [comment]
This has been moved back to the previous model
