### ISSUE TITLE
Proposal: unify standard and brokered infra configs

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2418]
The motivation behind having different types of infra config for different address space types was motivated by the ability to have different schema easily validated.

After having used this scheme for a while, I think there are some annoyances with the current approach:

* you have to maintain twice the number of infra configs if you have the same broker and admin settings for both address space types
* the schema of the standard infra config is made so that standard specific settings in the router is anyway it’s own sub-object.
* if the goal is to provide a unified interface, having this split between the types works against that goal

I propose that we create a new type ‘InfraConfig’ based on the ‘StandardInfraConfig’ and use that for everything. The existing types can be deprecated in the next release and supported as a fallback for existing deployments. With Kafka support, the new type can be extended with the Kafka settings rather than introduce another type.

Wdyt, @rgodfrey, @k-wall, @vbusch, @robshelly

**Comment by rgodfrey** [comment]
@lulf would the InfraConfig have a type field within it, "standard", "brokered", "kafka"... whatever... or would you think it possible to share the same InfraConfig instance between plans for different addressspace types.  The latter to me seems confusing, as if you were only creating brokered space it would be weird to define router size/minReplicas... and omitting the router info would (I presume) make the InfraConfig invalid for a standard plan.

**Comment by lulf** [comment]
@rgodfrey they could have a type, but I originally thought it would be ok to reuse I.e broker settings between standard and shared for instance. Right now, the only required field is version, all others are optional, so you can have an infra config without router section for instance.

Question is if we think broker setting in standard and brokered will differ at some point, in which case I think we need the type field and require different infra config instances. 

In any case I think having 1 resource with a type could be easier to manage than 2 distinct kinds.

**Comment by k-wall** [comment]
I am not sure I see this as an improvement to the model.   I see brokered and standard being quite different and Kafka would be more different still.   Sure we could represent their needs as type + loosely typed bag of stuff, but why is this preferable to the string typing we have now?  Also, wouldn't we lose the ability to make effective use of CustomResourceValidation?

**Comment by rgodfrey** [comment]
@k-wall @lulf if we want to share broker and admin pod settings between the plans of different types, would it not make more sense to have the infra configs actually be specific to a single resource type, and have the address space plans reference the different configs for the different resources (i.e. a brokered space plan would reference an admin resource config and a broker resource config; a standard space would reference a router resource config, a broker resource config and an admin resource config).  The individual resource configs seem to me to be essentially independent

**Comment by lulf** [comment]
@k-wall 
For the ability to do custom resource validation, I'm not sure we can make use of this  anyway, as we don't have any mandatory fields in the config. But the points you raise I would say are the reason why we have distinct types.

What made me write this proposal is that the configs are that its a bit hard to reuse infra configs. I think @rgodfrey's last comment is probably even better though.

**Comment by lulf** [comment]
So we would have:

```
kind: AdminConfig
metadata:
  name: default
spec:
  version:
  resources:
    memory: 512Mi
```

```
kind: RouterConfig
spec:
  version:
...

```
kind: BrokerConfig
spec:
  version:
```

And then

```
kind: AddressSpacePlan
spec:
  config:
    admin: default
    router: routercfg
    broker: brokercfg
```

**Comment by lulf** [comment]
However, where would we put things like `networkPolicy`?

**Comment by rgodfrey** [comment]
@lulf good question, is there anything else "like networkPolicy"?  In some ways networkPolicy could move down to the broker/router configs I guess, though that's not terribly appealing

**Comment by lulf** [comment]
@rgodfrey not at present. They could move down, in which case you could dictate policy for only those resources.

**Comment by k-wall** [comment]
@lulf I don't understand AdminConfig in the model sketch.  What would 512Mi apply to?  If this config relates to the EnMasse as a whole, why wouldn't NetworkPolicy belong there?

**Comment by lulf** [comment]
@k-wall AdminConfig is for agent/standard-controller config, which are per address space

**Comment by rgodfrey** [comment]
> @rgodfrey not at present. They could move down, in which case you could dictate policy for only those resources.

@lulf having it on broker/router seems wrong (since which resource it applies to really depends on the addsressspace type ... for brokered it applies to the broker, for standard it is the router) which makes me think that it is really something that applies at the plan level rather than the config (for shared infra how we we manage this isolation - would it be possible to limit one space to internal only, one space to internal+external, another space to no internal access?)

**Comment by lulf** [comment]
> @lulf having it on broker/router seems wrong (since which resource it applies to really depends on the addsressspace type ... for brokered it applies to the broker, for standard it is the router) which makes me think that it is really something that applies at the plan level rather than the config (for shared infra how we we manage this isolation - would it be possible to limit one space to internal only, one space to internal+external, another space to no internal access?)

I think it applies to 'all' the infra, because it uses the podSelector etc. to manage the infra. With shared infra, we will not be able to enforce network policies per address space or address space plan, because it operates at the infra level granularity which is shared.

**Comment by lulf** [comment]
1.0 unifies brokered and standard.
