### ISSUE TITLE
fix unstable test enmasse.systemtest.QueueTest > testInmemoryQueues

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#243]
enmasse.systemtest.QueueTest > testInmemoryQueues STANDARD_ERROR

    [OkHttp https://localhost:8443/api/v1/namespaces/enmasseci/pods?resourceVersion=1350&watch=true WebSocket Close Reply] INFO io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - WebSocket close received. code: 1000, reason: 

    [OkHttp https://localhost:8443/api/v1/namespaces/enmasseci/pods?resourceVersion=1350&watch=true WebSocket Close Reply] WARN io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Ignoring onClose for already closed/closing websocket

    [OkHttp https://localhost:8443/...] INFO io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - WebSocket successfully opened

    [Test worker] INFO test - Testing endpoint : restapi-enmasseci.10.10.20.137.nip.io:80

    [Test worker] INFO test - Test is running in multitenant mode

    [Test worker] INFO test - Following HTTP request will be used for getting address space:/v1/addressspaces/ with host: restapi-enmasseci.10.10.20.137.nip.io with Port: 80

    [vert.x-eventloop-thread-0] INFO test - Following list of address spaces received{"apiVersion":"enmasse.io/v1","kind":"AddressSpaceList","items":[{"metadata":{"name":"testspace","namespace":"testspace"},"spec":{"type":"standard","plan":"unlimited","endpoints":[{"name":"console","service":"console","host":"console-testspace.10.10.20.137.nip.io"},{"name":"messaging","service":"messaging","host":"messaging-testspace.10.10.20.137.nip.io","certProvider":{"name":"secret","secretName":"external-certs-messaging"}},{"name":"mqtt","service":"mqtt","host":"mqtt-testspace.10.10.20.137.nip.io","certProvider":{"name":"secret","secretName":"external-certs-mqtt"}}],"authenticationService":{"type":"none","details":{}}},"status":{"isReady":true}}]}

    [Test worker] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/

    [Test worker] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[{"metadata":{"name":"inMemoryQueue1","addressSpace":"testspace"},"spec":{"address":"inMemoryQueue1","type":"queue","plan":"inmemory"}},{"metadata":{"name":"inMemoryQueue2","addressSpace":"testspace"},"spec":{"address":"inMemoryQueue2","type":"queue","plan":"inmemory"}}]}

    [Test worker] INFO test - Waiting for 7 pods

    [Test worker] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace/inMemoryQueue1

    [Test worker] INFO test - Waiting until destination: inMemoryQueue1 will be in ready state

    [Test worker] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace/inMemoryQueue1

    [Test worker] INFO test - Waiting until destination: inMemoryQueue1 will be in ready state

    [Test worker] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace/inMemoryQueue1

    [Test worker] INFO test - Waiting until destination: inMemoryQueue1 will be in ready state

    [Test worker] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace/inMemoryQueue1

    [Test worker] INFO test - Waiting until destination: inMemoryQueue1 will be in ready state

    [Test worker] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace/inMemoryQueue1

    [Test worker] INFO test - Waiting until destination: inMemoryQueue1 will be in ready state

    [Test worker] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace/inMemoryQueue1

    [Test worker] INFO test - Waiting until destination: inMemoryQueue1 will be in ready state

    [Test worker] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace/inMemoryQueue1

    [Test worker] INFO test - Waiting until destination: inMemoryQueue1 will be in ready state

    [Test worker] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace/inMemoryQueue2

    [Test worker] INFO test - Waiting until destination: inMemoryQueue2 will be in ready state

    [Test worker] INFO test - External endpoint: messaging-testspace.10.10.20.137.nip.io:443, internal: messaging-testspace.10.10.20.137.nip.io:443

    [vert.x-eventloop-thread-0] INFO test - Sender link inMemoryQueue1 opened, sending messages

    [Test worker] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/

    [Test worker] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[]}

    [Test worker] INFO test - Waiting for 5 pods

enmasse.systemtest.QueueTest > testInmemoryQueues FAILED

    java.lang.AssertionError: Sending messages timed out after sending 0

        at org.junit.Assert.fail(Assert.java:88)

        at enmasse.systemtest.QueueTest.runQueueTest(QueueTest.java:159)

        at enmasse.systemtest.QueueTest.testInmemoryQueues(QueueTest.java:66)

**Comment by kornys** [comment]
Test is already removed, queue/topic plans were changed -> close
