### ISSUE TITLE
iot-operator doesn't watch for IoTConfig

### ISSUE THREAD

**Issue by famartinrh** [EnMasseProject/enmasse#2487]
https://github.com/EnMasseProject/enmasse/blob/2d3f74cf8ac7e97caa03d747d674c25a89e15b80/templates/iot/operator/050-Deployment-iot-operator.yaml

the iot-operator deployment doesn't set the env var `CONTROLLER_ENABLE_IOT_CONFIG` and therefore iot-operator doesn't watch for IoTConfig resources ...

https://github.com/EnMasseProject/enmasse/blob/2d3f74cf8ac7e97caa03d747d674c25a89e15b80/pkg/controller/add_iotconfig.go#L14-L15

**Comment by ctron** [comment]
The `iot-operator` should not watch that resource. The `IoTConfig` resource is processed by the `enmasse-controller-manager`. So I think that is fine.

**Comment by famartinrh** [comment]
in that case, the problem is in `enmasse-operator` because it isn't watching for IoTConfig too 

https://github.com/EnMasseProject/enmasse/blob/2d3f74cf8ac7e97caa03d747d674c25a89e15b80/templates/enmasse-operator/050-Deployment-enmasse-operator.yaml

**Comment by lulf** [comment]
Shouldn't this be the responsibility of the iot-operator though?

**Comment by ctron** [comment]
No the "iot-operator" works cluster wide while the enmasse-controller-manager only works in the enmasse infrastructure project. And thus has different permissions.

It looks like @lulf deactivated the IoTConfig module here: https://github.com/EnMasseProject/enmasse/commit/5c25b06be27dff35d3396356bc0b96eb12971a48#diff-b5797c7936e90c9bb18dc959ef2a73c9L38

**Comment by ctron** [comment]
In combination with the IoT system tests being called wrongly in travis, no one noticed. I created PR #2488 which should fix calling the systemtests on travis.

So they should run into an error now. And then we can think how to fix this.

**Comment by lulf** [comment]
@ctron Hmm, perhaps we can grant iot-operator cluster-wide permissions to get watch iot configs as well? I would like to avoid depending on the IoTConfig CRD being installed for the enmasse-operator to work.

**Comment by ctron** [comment]
So whole cause for this was to limit the capabilities of the two different functionalities. IoTConfig is only valid for "enmasse-infra" and must create deployments, read/write secrets, … while the IoTProject part requires cluster wide access to only IoTProject, and Address, AddressSpace, MessagingUser.

However, the controller runtime can only run either namesspaced or non-namespaced … but not both in a single operator instance.

So mixing those two functionalities again would mean to set the watch namespace to cluster wide, and that would cause it to also watch for secrets cluster wide, which we did not want to grant.

**Comment by lulf** [comment]
Good point, I was a bit confused about the IoTConfig vs. IoTProject. We should move the IoTConfig CRD to 'templates/crds' then and add the necessary rules to enmasse-operator/20-Role-enmasse-operator.yaml
