### ISSUE TITLE
qdrouter - "amqp:connection:framing-error No valid protocol header found" in log

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#250]
This messages is wrote into the log of qdouter periodically:  Connection from 172.17.0.1:51714 (to 0.0.0.0:5672) failed: amqp:connection:framing-error No valid protocol header found

Liveness probe doesn't present valid credentials, probably.

**Comment by lulf** [comment]
Actually, its not even sending AMQP frames, it's just opening a TCP socket.

**Comment by k-wall** [comment]
@tkratky @lulf - is the reported issue actually a defect?

**Comment by lulf** [comment]
@k-wall I argue that it is not a defect, but I think the plan is to provide a better liveness/readiness probe for the router that does some more thorough checking rather than just opening a tcp connection.
