### ISSUE TITLE
iot-device-registry credentials hash-function

### ISSUE THREAD

**Issue by famartinrh** [EnMasseProject/enmasse#2569]
**Describe the bug**
following the iot example I noticed that the `hash-function` property of the credentials doesn't match the hash-function provided when creating the credentials.

I made a POST request to the credentials endpoint of the device-registry indicating `sha-512` as  hash-function, but querying the just created credential the hash-function is `bcrypt`

**To Reproduce**
```
[examples](systemtests-iot|+7)$ curl --insecure -X POST -i -H 'Content-Type: application/json' --data-binary '{"device-id": "4711","type": "hashed-password","auth-id": "sensor1","secrets": [{"hash-function" : "sha-512","pwd-plain":"'hono-secret'"}]}' https://$(oc get routes device-registry --template='{{ .spec.host }}')/credentials/myapp.iot
HTTP/1.1 201 Created
location: /credentials/myapp.iot/sensor1/hashed-password
content-length: 0
Set-Cookie: cf4e55db6204a0536329ceeca925c096=9a04f233a8eec5c077aa66bdbe4077b0; path=/; HttpOnly; Secure

[examples](systemtests-iot|+7)$ curl --insecure -X GET -i https://$(oc get routes device-registry --template='{{ .spec.host }}')/credentials/myapp.iot/4711
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-length: 221
Set-Cookie: cf4e55db6204a0536329ceeca925c096=9a04f233a8eec5c077aa66bdbe4077b0; path=/; HttpOnly; Secure
Cache-control: private

{"total":1,"credentials":[{"device-id":"4711","type":"hashed-password","auth-id":"sensor1","enabled":true,"secrets":[{"hash-function":"bcrypt","pwd-hash":"$2a$10$bAL7Zz8QQDk6vcysP7jazedzrf00nMRbHFtRAYY1iAdkypqLrELOm"}]}]}
```

I'm not sure if this is the expected behaviour or the request is not correct or if there is a bug here.

**Comment by ctron** [comment]
Yea, I think the whole API of the credentials part of the device registry is … complicated and should be fixed, completely.

When you provide the plain password, then the hash is ignored IIRC. When you provide the hash algorithm, then you need to hash the password yourself. And also do the salt yourself.

You can have a look here:

https://github.com/ctron/hat/blob/5ca0920a9f88c7e387060277bfa4abdf05dc5fcd/src/credentials.rs#L419-L450

**Comment by famartinrh** [comment]
Sounds reasonable to me, Thank you @ctron

**Comment by ctron** [comment]
There is currently a discussion going on removing this altogether: https://github.com/eclipse/hono/pull/1130#issuecomment-479829977
