### ISSUE TITLE
Manual installation of 0.27.1 on Kubernetes not working

### ISSUE THREAD

**Issue by mbaeuerle** [EnMasseProject/enmasse#2603]
**Describe the bug**
Following the instructions in https://enmasse.io/documentation/0.27.0/kubernetes/#installing-using-manual-steps-messaging 
the address-space-controller is crashing with this error message:
```
Error starting address space controller: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/enmasse-infra/configmaps/broker-prometheus-config. 
Message: Forbidden!Configured service account doesn't have access. 
Service account may have been revoked. configmaps "broker-prometheus-config" is forbidden: 
User "system:serviceaccount:enmasse-infra:address-space-controller" cannot get resource "configmaps" in API group "" in the namespace "enmasse-infra".
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Start up Minikube
2. Follow instructions https://enmasse.io/documentation/0.27.0/kubernetes/#installing-using-manual-steps-messaging
   - Before step __Deploying the example authentication service__:  
Apply missing crds (`kubectl apply -f install/components/crds/`)
3. `kubectl get logs address-space-controller-xxx` shows the error 

**Expected behavior**
EnMasse starting up

**Comment by lulf** [comment]
@mbaeuerle Thanks for reporting the issue, we will have a look at it. The manual installation steps are somewhat out of date.

As a workaround, the following steps are tested in our CI and should work: https://enmasse.io/documentation/master/kubernetes/#installing-using-bundle-messaging

**Comment by lulf** [comment]
We have removed the manual install docs for now as the 'bundle' installation is anyway the 'minimal' installation needed now that authentication services are explicitly configured.
