### ISSUE TITLE
Allow setting security context of pods using persistent volumes

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2714]
**Overview**

In order to support Ceph persistent volume claims, pods may need to be configured with a security context. This affects components such as:

* standard authservice
* brokered address space broker
* standard address space broker

For the brokers, the podTemplate.spec in the standardinfraconfig/brokeredinfraconfig can be extended to specify the security context.

For standard-authservice, the syntax of AuthenticationService resource needs to be extended.

**Comment by k-wall** [comment]
This feature will also support the running of EnMasse under OLM, where for installation in some namespaces, securityContext.fsGroup must be applied.   The scope of the features needs to include the IoT file device registry, which also requires a persistent volume.

**Comment by k-wall** [comment]
As @lulf suggests above, for brokers, the existing pod template can be extended to respect the security context contained with the template attached to the infraconfig.

For the authentication service, one way to achieve this is to add a podTemplate to the standard spec.   For consistency, we'd also support the same field on the `none` authentication service too.

For the IoT file device registry, we could add a `SecurityContext` to the `CommonServiceConfig`.  I rejected the idea of adding a `PodTemplate` there as is role would overlap partially with the existing remit of ContainerConfig.

Currently the EnMasse operator supports a FS_GROUP_OVERRIDE environment variable allow the fs group to be specified globally.  This is flawed.  It is only a coincidence that the broker/keycloak/file device registry images happen to require the same gid.   Support for the FS_GROUP_OVERRIDE will be removed.  The upshot is that is the user wants to install EnMasse in openshift-operators (i.e. cluster wide, the user *must* specify the security context in the resources defined above.

**Comment by lulf** [comment]
@k-wall Looks reasonable to me. Note that the additional FS_GROUP_STANDARD_AUTHSERVICE_OVERRIDE i made should be removed as well.

I'm a bit divided on adding podTemplate to authservice spec, mainly because we already have resources called out explicitly in the schema today. I think if we add podTemplate to the spec, we should make sure one can set resources there as well. I'm fine with adding a securityContext field explicitly as well.

**Comment by k-wall** [comment]
@lulf I share your concerns about the addition of the podTemplate.  On the one hand it is nice as it gives the user controls over many aspects, in a way that it is familiar to the Kubernetes user, and follows the pattern we have established on the infraconfigs. On the other, I have a dislike for too many levers.

**Comment by ctron** [comment]
> or the IoT file device registry, we could add a `SecurityContext` to the `CommonServiceConfig`. I rejected the idea of adding a `PodTemplate` there as is role would overlap partially with the existing remit of ContainerConfig.

I wouldn't add it to the `CommonServiceConfig`, as only the `FileBasedDeviceRegistry` uses a PVC. And IIRC this would only make sense for pods which have a PVC attached. So we should only add this to the `FileBasedDeviceRegistry`.

For Infinispan we would need to set this on the Infinispan pods.

**Comment by k-wall** [comment]
After reflection, I think to add code to default the appropiate fs group if there is no security context provided and the target namespace is `openshift-operators`.  That way, EnMasse will work out of the box if installed cluster wide using OLM.

To allow for this I add a environment variable which will be set from the enmasse operator deployment which specifies the file system GIDs to be applied if the namespace is `openshift-operators`.
