### ISSUE TITLE
Allow providing non-encoded password input for MessagingUser

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2728]
Requiring MessagingUser passwords to be base64-encoded has been a common source of errors for users. It would be convenient if they could specify the password as plain text instead of base64. Possible using a type 'password-plain' or change 'password' to 'password-base64'.

**Comment by dmvolod** [comment]
@lulf , as idea, it could be the same field as now, but marked password as Artemis does. If it contains ENC(xyz) the password must be encoded, if no, it's already encoded. Also, could be added additional properties with encoding algorithms and/or encoding on the flight mark.

**Comment by k-wall** [comment]
Perhaps we should follow the model used by Kubernetes secrets `stringData` i.e. use a separate field that accepts the clear text and internally produces the encoded value.

**Comment by dmvolod** [comment]
In this way, may be try to use Kubernetes secrets for store passwords and not implement own logic for this.

**Comment by lulf** [comment]
@dmvolod Using secrets would require EnMasse to have access to the secrets in an application's namespace, requiring the application to setup an addition Role + RoleBinding. We can certainly support that use case as well though, but for application running on cluster, I think the serviceaccount user type is more attractive.

**Comment by lulf** [comment]
This is addressed in #4391
