### ISSUE TITLE
Enable web console to create projects/namespaces

### ISSUE THREAD

**Issue by hguerrero** [EnMasseProject/enmasse#2731]
**Overview**

When creating a new address space, if you're able, allow the creation of a new project too.

**Design**

If you have a more detailed design in mind, or as you plan to implement this feature, write a design doc with the details. Use the [template](https://github.com/EnMasseProject/enmasse/blob/master/documentation/design/proposals/design-template.adoc) and raise a PR with the design doc, and link to this issue.

**Tasklist**

If/when you can, enumerate the tasks required to complete the feature in order to track progress as the feature is implemented.

**Comment by lulf** [comment]
Duplicate of #2730
