### ISSUE TITLE
Separate the building of the Artemis image from the EnMasse code base

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#2756]
Currently, the EnMasse build cycle creates an Artemis image based on the Apache Artemis tgz.  This is done as there is no Artemis image published by the Apache project.

As this image changes infrequently, the repetitive work is superfluous and slows the build/test cycle of the developers.

It would be better if we moved production of the image to a separate project beneath https://github.com/EnMasseProject/ in a similar way as to what already done for `enmasse/qdrouterd-base` by https://github.com/EnMasseProject/router-docker-base.

I see we started down this path before, https://github.com/EnMasseProject/artemis-docker-base, so I propose to re-use the existing project as its home.  @dejanb @lulf thoughts?

**Comment by lulf** [comment]
Fully agreed

**Comment by k-wall** [comment]
Image build now -> https://github.com/EnMasseProject/artemis-docker-base/pull/1
