### ISSUE TITLE
Address space console should show addressspace name (and namespace) 

### ISSUE THREAD

**Issue by rgodfrey** [EnMasseProject/enmasse#2777]
Currently the address space specific console does not show the name of the address space (or the namespace within which the address space exists) anywhere on the screen.  It should do so.

When the address space console is integrated into the central console, it should also be possible to easily navigate to another address space without having to go back to the central console.

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.  The new console has this feature.
