### ISSUE TITLE
Namespace of address spaces and addresses is wrong in Grafana

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#2779]
When enabling monitoring of EnMasse, the namespace shown for address spaces in the EnMasse dashboard seems wrong:

![image](https://user-images.githubusercontent.com/19670/57227457-b9794c00-7011-11e9-931c-1b6c9d118086.png)

Note that the namespace is set to 'enmasse-infra', but the namespace of these should actually be 'myapp':

```
oc get addressspaces -o jsonpath='{.items[*].metadata.namespace}'
myapp myapp
```

The namespace is also wrong for the labels on the addresses graph.

**Comment by robshelly** [comment]
Fixed in #2842
