### ISSUE TITLE
Metrics of senders not correctly reported on console

### ISSUE THREAD

**Issue by jcordes73** [EnMasseProject/enmasse#2815]
**Describe the bug**
Correct metrics of senders are reported

**To Reproduce**
1. Create topic address
2. Send message to topic
3. Verify senders counter on console

**Expected behavior**
Correct number of senders should be reported

**Screenshots**

![image](https://user-images.githubusercontent.com/2852314/57704283-df31d100-7661-11e9-9d36-de25452e2189.png)

**Additional context**

**Comment by k-wall** [comment]
@jcordes73  Your report is not too clear to me.   "Senders" is the count of the number of _sending links_ currently established by the application(s).  The term _link_ here comes from AMQP 1.0 parlance [1].   "Senders" is not a function of the number of messages sent to the address.  

[1] http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#section-links
