### ISSUE TITLE
Operator install stays in unknown state due to incorrect YAML in docs

### ISSUE THREAD

**Issue by garethahealy** [EnMasseProject/enmasse#2821]
**Describe the bug**
Following the install for the operator doesn't work. The Subscription has an invalid source value. Currently points to _enmasse-operators_, but should be pointing to the named CatalogSourceConfig, which is: _installed-enmasse-operators_ 

**To Reproduce**
Following docs @ https://github.com/EnMasseProject/enmasse/blob/e44c8c596d187171e580746d1caba84a3ce13aa9/documentation/modules/proc-installing-using-olm.adoc

**Expected behavior**
Operator installs successfully following docs

**Comment by k-wall** [comment]
Fixed by #2822
