### ISSUE TITLE
Upgrade from 0.28 to current master does not work

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#2824]
**Describe the bug**
Upgrade of enmasse from 028 to current master does not work. Images of deployed addressspaces are not upgraded.

for more info please look into jenkins on enmasse-master-upgrade job

**Comment by k-wall** [comment]
@kornys the symptom you've described above matches the bug that @vbusch fixed #2868.  There the image of resources related to the addressspace would stay at the old version.

However, I checked the  latest enmasse-master-upgrade job and currently it appears that it is currently failing earlier. Non-address space images are failing to be pulled.  I'm seeing:

`20m         22m          4         address-space-controller-8446f7f7b8-zcjsf.15a4ab3be3705184   Pod            spec.containers{address-space-controller}   Warning   Failed                kubelet, localhost         Failed to pull image "docker-registry.upshift.redhat.com/enmasseproject/address-space-controller:jenkins-enmasse-master-folder-enmasse-master-69": rpc error: code = Unknown desc = Error: image enmasseproject/address-space-controller:jenkins-enmasse-master-folder-enmasse-master-69 not found
`
