### ISSUE TITLE
DashboardURL on ServiceInstances created 1.0 do not work in 1.1

### ISSUE THREAD

**Issue by philbrookes** [EnMasseProject/enmasse#2825]
**Describe the bug**
Any ServiceInstances created in AMQ Online 1.0 will have dashboard URLs that do not work once having upgraded to AMQ Online 1.1.

**To Reproduce**
- Install AMQ Online 1.0
- Deploy AMQ Online Standard from the catalog
- Check Dashboard URL works normally
- Upgrade to AMQ Online 1.1 with [these instructions](https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/installing_and_managing_amq_online_on_openshift_container_platform/index#upgrading-enmasse-using-ansible-messaging)
- Check Dashboard URL is no longer valid.

**Expected behavior**
The dashboard URL should still work.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rgodfrey** [comment]
@philbrookes when you say "Dashboard URL is no longer valid" are you saying you get a 404, or that you can no longer log in, or some other symptom?

**Comment by vbusch** [comment]
Reproduced with amq-online 1.0, and upgrading to 1.1
SSO redirection is failing: 

https://172.30.149.188:8443/auth/realms/amq-online-infra-my-space/protocol/openid-connect/auth?client_id=enmasse-console&state=0612acaa-6576-4096-b613-6b2e349b6f85&redirect_uri=https%3A%2F%2Fconsole-o66h8qvqqa-amq-online-infra.127.0.0.1.nip.io%2F%3Fauth_callback%3D1&scope=openid&response_type=code&kc_idp_hint=openshift-v3
/auth/realms/amq-online-infra-my-space/protocol/openid-connect/auth?client_id=enmasse-console&state=fc8e1b99-ad3b-4a59-bd4a-6c0b8a100f73&redirect_uri=https%3A%2F%2Fconsole-o66h8qvqqa-amq-online-infra.127.0.0.1.nip.io%2F%3Fauth_callback%3D1&scope=openid&response_type=code&kc_idp_hint=openshift-v3
![console_url](https://user-images.githubusercontent.com/1995405/58603348-68e6be80-825e-11e9-8eb5-fed78fb4c52b.png)

It is fixed upstream.  Tested with 0.26 and upgrading to latest.

**Comment by vbusch** [comment]
Existing address spaces are not updated during the upgrade process.  The address space configurations should be reviewed, and then updated manually.   Added documentation for how to do this.

**Comment by lulf** [comment]
Please use https://issues.jboss.org/projects/ENTMQMAAS for issues related to the AMQ Online Red Hat product.
