### ISSUE TITLE
Console "Connections" shows stuff from "ragent"

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse#287]
Maybe we could filter connections from ragent and not showing them in the "Connections" view in the console ? They are all related to the $management address and some temporary ones (I guess for replies or something like that).
Are them useful to the final user ?
Wdyt @grs ?

**Comment by grs** [comment]
I agree, we are already filtering some of the internal connections already but need to expand the criteria for exclusion.
