### ISSUE TITLE
Admin console unavailable in version 0.28.1-r4

### ISSUE THREAD

**Issue by aaron0609** [EnMasseProject/enmasse#2875]
**Describe the bug**
The port 8080 is not listening in admin pod, which means the web console is not available here

**To Reproduce**
1. kubectl exec -it admin.v7ey5cyo01-64759d5dfb-pnxzk -- /bin/sh
2. netstat -ntpl (No 8080 port listening here)

**Comment by aaron0609** [comment]
Well using the image "docker.io/enmasseproject/standard-controller:0.27" in admin deployment instead of latest one can temporarily resolve it.

**Comment by k-wall** [comment]
@aaron0609 On Kubernetes, for the console to be available, Kubernetes itself needs to be integrated with an OpenID connect provider [1] and the consoleservice CR instance, console, needs to be wired up with to the same OpenID connect service.    This will also make the global console available which provides you with a view across all address spaces.   (For some background, the console feature in EnMasse is being reworked at the moment. It is envisaged that the global console will subsume responsibilities from the address space consoles. It current state, at 0.28, is a stepping stone towards that goal).

[1] https://kubernetes.io/docs/reference/access-authn-authz/authentication/
