### ISSUE TITLE
mocha-junit-reporter is incompatible with mocha ver. 4

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#290]
new version of mocha was released today, but mocha-junit-reporter still require version: ^3.0.0
https://github.com/michaelleeallen/mocha-junit-reporter/issues/54

**Comment by tkratky** [comment]
created PR: https://github.com/EnMasseProject/enmasse/pull/291

**Comment by lulf** [comment]
Closing, fixed by #291
