### ISSUE TITLE
Standard authentication service no longer includes persistence (postgres)

### ISSUE THREAD

**Issue by david-martin** [EnMasseProject/enmasse#2906]
**Describe the bug**
When installing with the 'standard' authentication service, postgres doesn't seem to be installed anymore for keycloak (since 1.1. Was there in 1.0).

The regression looks to be introduced in https://github.com/EnMasseProject/enmasse/commit/5c25b06be27dff35d3396356bc0b96eb12971a48#diff-6c8aa2a82099386b15c24c8b9813d46b

We thought it would be ok to not have any authentication service specified during install, and just create an authentication service after install e.g. https://github.com/integr8ly/installation/blob/v1.4/roles/enmasse/templates/authenticationservice.yml.j2#L11-L18

However, if the 'standard' authentication service is not speicfied during install, it seems that some CRDs e.g. MessagingUser (and possibly other stuff?) don't get installed either.

**To Reproduce**
1. Install with `enmasse_authentication_services` set to `[]`
2. See that the MessagingUser CRD is not available

1. Install with `enmasse_authentication_services` set to `["standard"]`
2. See that keycloak is installed, but with no persistence

**Expected behavior**
What we're looking for is a way to have the full functionality of enmasse from after the install (see internal issue https://issues.jboss.org/browse/INTLY-2491), and have a single AuthenticationService (keycloak) that is persistent.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by k-wall** [comment]
Postgresql backed keycloak was never an out of the box feature of EnMasse.    Please use https://issues.jboss.org/projects/ENTMQMAAS to report issues affecting only AMQ Online.
