### ISSUE TITLE
Allow the installer to be run against an already existing namespace

### ISSUE THREAD

**Issue by david-martin** [EnMasseProject/enmasse#2908]
**Overview**

Allow the installer to be run against an already existing namespace.
Our use case is that we want to install enmase to a namespace called `openshift-enmasse` (for OSD related reasons).
However, the `oc new-project` cmd is not allowed to create namespaces that start with `openshift-`.
Instead, a namespace has to be created by a system:admin.

Ideally, the enmasse installer can accept an already existing namespace to install things into instead of always creating a project.

**Design**

Allow the namespace to be specified (I believe this is already OK)
When creating the project, ignore any errors if it already exists, as this may be deliberate as in our use case.

**Tasklist**

-

**Comment by kornys** [comment]
fixed
