### ISSUE TITLE
Certs fail to generate if the CN is greater than 64 chars

### ISSUE THREAD

**Issue by garethahealy** [EnMasseProject/enmasse#2910]
**Describe the bug**
When following the docs:
- https://github.com/EnMasseProject/enmasse/blob/cc76afc1e5254cea788da42f8690114b640869d1/documentation/modules/proc-iot-installing-services.adoc
- https://github.com/EnMasseProject/enmasse/blob/master/templates/iot/examples/k8s-tls/create#L47

The certs fail to generate if the CN is greater than 64 chars. For example:
```
CLUSTER="apps.cluster-none-a4b2.none-a4b2.openshiftworkshop.com"
$ ./create
```

Gives an error:
> 4548265580:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:158:maxsize=64

**To Reproduce**
1. CLUSTER="apps.cluster-none-a4b2.none-a4b2.openshiftworkshop.com"
2. install/components/iot/examples/k8s-tls/create
3. Get error.

**Additional context**
> $ openssl version
> OpenSSL 1.0.2s  28 May 2019

@dejanb @ctron

**Comment by ctron** [comment]
@garethahealy The solutions sounds easy, use a shorter DNS name :grin: … sorry, couldn't resist

This seems to be a limitation of the "CN" field, and the solution is to put "something" into CN, and use the SAN field instead, which allows longer hostnames.
