### ISSUE TITLE
Address go type is missing AddressStatus property

### ISSUE THREAD

**Issue by secondsun** [EnMasseProject/enmasse#2942]
**Describe the bug**
The Address resource has a read only property "status" that isn't represented in the go type.

**To Reproduce**
1. Be writing a client in golang
2. Deploy an Address resource
3. In golang fetch your address
4. There is no status object on the address type.

**Expected behavior**
Go types should have the address

**Additional context**
a example for the go type : 

```
type Address struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AddressSpec   `json:"spec"`
	Status AddressStatus `json:"status"`
}

type AddressStatus struct {
	IsReady bool `json:"isReady"`
}
```
I've patched a copy of my types in my vendor directory with this and am able to access the status thusly (apologies for the out of context code)
```
foundQueue := newQueue(instance, address) //Sets some defaults for my use case
err = r.client.Get(context.TODO(), types.NamespacedName{Name: foundQueue.Name, Namespace: foundQueue.Namespace}, foundQueue) //fetches
/* snip error check*/
if !foundQueue.Status.IsReady {
				reqLogger.Info("Queue Not ready", "Queue.Name", foundQueue.Name)
				requeueCreate = true
			}

```

**Comment by k-wall** [comment]
@secondsun thanks for the report.  Indeed it is absent.  Please feel free to raise a PR, that would be much appreciated.

**Comment by secondsun** [comment]
https://github.com/EnMasseProject/enmasse/pull/2948
