### ISSUE TITLE
Document uninstall using Ansible

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#3002]
#1297 created an uninstall playbook, but did not update the docs.  This task is to add it to the documentation.  The documentation should direct the user to use the same inventory file that they used when they installed EnMasse (with Ansible).  It should also inform the user that the infra namespace will be deleted by the playbook. 

```ansible-playbook -i _inventory-file_ ansible/playbooks/openshift/uninstall.yml```

**Comment by jenmalloy** [comment]
PR: https://github.com/EnMasseProject/enmasse/pull/3005

**Comment by jenmalloy** [comment]
PR merged; closing
