### ISSUE TITLE
In the address space console, the user shows as unknown when connections tab is reloaded

### ISSUE THREAD

**Issue by vbusch** [EnMasseProject/enmasse#3014]
The user name (top right corner), shows as "unknown", when you reload the connections tab.

**To Reproduce**
1. Go to the address space console
2. Click on 'connections tab'
3. You see your username.
4. Reload the page
5. Your username is replaced with 'unknown'

**Expected behavior**
You still see your username

![connections-unknown-user](https://user-images.githubusercontent.com/1995405/61412782-c0e18f00-a8b7-11e9-8b84-bf042c51ca80.png)

**Comment by k-wall** [comment]
@vbusch is this a regression?

**Comment by vbusch** [comment]
@k-wall I doubt it.  If you go to the console, then click on the connection tab.  Things work as expected.  I don't think I have ever tested reloading the connection tab.

**Comment by k-wall** [comment]
The console referred to by this issue is removed.
