### ISSUE TITLE
separate system-tests to full and reduced set of tests

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#304]
With growing count of tests will not possible to execute full set of tests in master. For this reason should be system-tests separated to full and reduced set of tests. Full sort of tests will executed separately.

**Comment by lulf** [comment]
I think we need to split the tests into different packages first. Then, we must configure gradle tasks for each set. Example 47.10 in https://docs.gradle.org/current/userguide/java_plugin.html shows an example

**Comment by tkratky** [comment]
this is done, tests were separated to SmokeTests and others
-> close
