### ISSUE TITLE
AddressController REST API: no distinction between address spaces

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#308]
With 0.13.0, the AddressController  REST API operations don't seem to take the addressSpace in the URL into account.

To reproduce:
(Tests done on minikube, initialized via ./deploy-kubernetes.sh -a "none standard")

- Create new addressspace "test"
POST http://[server:port]/v1/addressspaces
with payload
````
{
  "apiVersion": "enmasse.io/v1",
  "kind": "AddressSpace",
  "metadata": {
    "name": "test",
    "namespace": "enmasse"
  },
  "spec": {
    "type": "standard",
    "plan": "unlimited",
    "authenticationService": {
      "type": "none",
      "details": {}
    }
  }
}
````

- add address to "default" namespace
POST http://[server:port]/v1/addresses/default
with payload
````
{
  "apiVersion": "enmasse.io/v1",
  "kind": "AddressList",
  "metadata": {
    "addressSpace": "default"
  },
  "items": [
	{
	    "apiVersion": "enmasse.io/v1",
	    "kind": "Address",
	    "metadata": {
	        "name": "test1_default", 
	        "addressSpace": "default"
	    },
	    "spec": {
	        "type": "multicast"
	    }
	}
  ]
}
````
- get addresses of "test" namespace
GET http://[server:port]/v1/addresses/test

=> also returns addresses from "default" addressSpace

- try to reference the "test1_default" address (from the "default" addressSpace) via "test" addressSpace
GET http://[server:port]/v1/addresses/test/test1_default

=> returns the address - would have expected 404 here

**Comment by lulf** [comment]
For this REST API to work correctly, you must deploy the address controller in multitenant mode. For kubernetes, the template is hardcoded to deploy as single tenant. To deploy as multitenant, you must edit the kubernetes/enmasse.yaml and change the environment variable MULTIINSTANCE in the address controller deployment from 'false' to 'true'.

**Comment by calohmn** [comment]
Ah, ok, I forgot about this setting. Maybe trying to add a 2nd address space in the single-instance case can be handled with some kind of error response? Anyway, I'll close the ticket.
