### ISSUE TITLE
Agent process's memory allocation doesn't respect container memory limits

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#3086]
NodeJS (before v12) does not constrain itself to the container's memory.   This means that Node may try to use more memory than the Kubernetes environment will permit leading to OOM at the container level.

With NodeJS v10 (used by 0.29), the default node heap is 1400MB if the _host_ machine has more than 512MB/64bit arch.  This means that the memory resource controls exposed by standardinfraconfig for the admin pod, will lead to unexpected effects if the container's memory size is below (1400MB + overhead for node).

**Comment by k-wall** [comment]
It would be possible to have launch_node.sh compute a `--max_old_space_size` based on `/sys/fs/cgroup/memory/memory.limit_in_bytes`

**Comment by vbusch** [comment]
The upgrade to v12 would be nice for 1.3.  But version 12 doesn't seem to be available yet in the redhat software collections.  Which would make the downstream build a little more complicated.

I believe setting the variable would be easiest for now.
