### ISSUE TITLE
AddressController REST API: POST with single address doesn't work

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#309]
Trying to add a single address on an addressSpace via POST doesn't seem to have an effect (although 200 is returned).

POST http://[server:port]/v1/addresses/default
with payload
````
{
    "apiVersion": "enmasse.io/v1",
    "kind": "Address",
    "metadata": {
        "name": "test1_default", 
        "addressSpace": "default"
    },
    "spec": {
        "type": "multicast"
    }
}
````
=> Addresslist of addressSpace "default" is unchanged, with no added "test1_default" address.
see GET on http://[server:port]/v1/addresses/default

(Test done in minikube, using EnMasse 0.13.0)

**Comment by lulf** [comment]
See my comment in #308. This does not work when the address controller is deployed in non-multitenant mode).

**Comment by lulf** [comment]
To add a single address, you must use the following JSON at present:

```
{
  "apiVersion": "v1",
  "kind": "AddressList",
  "items": [
    {
        "metadata": {
            "name": "test1_default", 
            "addressSpace": "default"
        },
        "spec": {
            "type": "multicast"
        }
    }
  ]
}
```

POST of a single address remains to be implemented :)
