### ISSUE TITLE
Field selectors no working

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#3152]
**Describe the bug**
Using field selectors doesn't work properly. Instead of reporting that the field selector is not supported, the field selector is ignored, and non-matching entries are returned.

**To Reproduce**

1. Create an address with a plan named "foo"
1. Execute the command: `oc get address  --field-selector status.planStatus.name=standard-small-anycast -o yaml`
1. The result will return the entry with "foo" as well.

**Expected behavior**
Either properly support field selectors, or report an error.

Also see: https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-fields

**Comment by lulf** [comment]
I think this works now with CRDs?
