### ISSUE TITLE
 Global console liveness probes fails on minikube

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#3247]
**Describe the bug**

When configuring the global console on minikube using Google OIDC, the liveness probes fail to authenticate to the oauth-proxy. This causes the console to be restarted.

**To Reproduce**
1. Configure console with Google Oauth
2. Watch console pod getting restarted due to liveness probe failure

**Expected behavior**
No restarting

**Comment by k-wall** [comment]
The health endpoint ought not require authentication.  The issue will be the probe path differs between pusher's oauth-proxy and open shift's.  The former provides "/ping" whereas "/oauth/healthz" for the latter.

https://github.com/pusher/oauth2_proxy/blob/master/docs/configuration/configuration.md
