### ISSUE TITLE
Switch go dependency management to use go modules

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#3283]
**Overview**

Now that Kubernetes itself uses go modules for tracking dependencies, migrating enmasse to use go modules as well should be possible. 

This should simplify dependency managed for Go code.

**Design**

Convert glide.yaml and glide.lock to go modules.

**Comment by lulf** [comment]
There are still a few dependencies such as openshift/client-go and openshift/api that are not yet migrated to go modules.

**Comment by k-wall** [comment]
I tried the same thing a few days ago and hit similar sounding problems.  The automated conversion from glide failed.  I tried a manual approach and hit problems with openshift/client-go.
