### ISSUE TITLE
Example for using mqtt client

### ISSUE THREAD

**Issue by LeeWong** [EnMasseProject/enmasse#3403]
I tried to test enmasse 0.30.0-rc4 with a paho mtt python client but having trouble to find the right certificate. which certificate I should extract from kubernetes secret? external-certs-mqtt? I cannot find any related information on documentation. Could you please point me to the right direction? Thank you.

**Comment by lulf** [comment]
If you are using the defaults for address space (selfsigned), your cert can be retrieved like this:

`kubectl get addressspace <name> -o jsonpath={.status.caCert} | base64 -d`

**Comment by LeeWong** [comment]
Thank you.
