### ISSUE TITLE
Use CRD instead of api-server for AddressSpace, Address and MessagingUser

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#3407]
**Description**

Introduce CRDs for AddressSpace, Address and MessagingUser and remove api-server

**Design**

https://github.com/EnMasseProject/enmasse/blob/master/documentation/design/proposals/crdification.adoc

**Tasklist**

* [x] Enable CRD for AddressSpace and Address
* [x] Enable CRD for MessagingUser
* [x] Add notes on resulting API changes

**Comment by lulf** [comment]
@EnMasseProject/dev 

For the next task, converting MessagingUser to CRDs, there most logical place to put reconciliation of MessagingUser -> Keycloak is in enmasse-operator. 

However, the enmasse-operator would then need to watch MessagingUser resources across all namespaces. The main problem with that is that controller-runtime only allows a controller manager to either watch a single namespace, or all namespaces: At present, the iotconfig, authenticationservice and consoleservice controllers also watch deployments, configmaps, secrets and other resources created based on their respective CRs. If enmasse-operator was changed to watch all namespaces, this would mean it would need permissions to watch Deployments, Configmaps, Secrets etc. across the entire cluster, which would grant it too wide privileges.

The way this is solved for the IoTProject resource is that a separate process, iot-operator is created that only needs cluster-wide privileges for iot-related resources. 

This problem will also need to be solved for shared infra, where the enmasse-operator will need to watch addresses and addressspaces across all namespaces (which is currently handled by address-space-controller).

Alternatives:

1. Deploy a 'local-enmasse-operator' and 'global-enmasse-operator' deployment on install. The first would contain the local privileges, and the latter would contain cluster-wide privileges for iotproject, addressspace, address, messaginguser. There might be some unforseen pitfalls here where the global-enmasse-operator for some reason would need to watch a secret but can't with this model (i.e. to watch user-supplied endpoint cert secrets is one thing that comes to mind).
2. Attempt to run multiple controller-runtime managers in the same process. This doesn't seem feasible due to each manager setting up signal handlers and metrics endpoints.
3. Implement a time-based reconciliation of messaginguser resources for now in enmasse-operator without using controller-runtime, and work with controller-runtime project upstream to add support for watching both local and global namespaces before working on shared infra. This would be my preference assuming the community would be willing to accept such a change.
4. Bypass the controller-runtime and setup informers and caches so that both global and namespaced resources can be mixed. This alternative would prevent us from taking advantage of the simplified controller-runtime API.

**Comment by ctron** [comment]
I would strongly suggest not do do 2, 3., and 4., all of them sounds like "swimming against the stream", and will most likely only cause issues in the future.

I would suggest to go for 1. … However, I would not mix IoT with "standard messaging". We already have the "modules" in the operator, so the code can sit in the same repo and image. However you might want decide and not install IoT (not sure why you want to do this, but hey :wink:). That option would then no longer be possible.

Also are we currently deploying the iot-operator when the IoTConfig gets created. So we don't have two operators that we install, but one. And I think it makes sense to keep this model.

So having another "global" operator is a good idea. But I think that should be a "global enmasse core" operator.

**Comment by lulf** [comment]
> I would strongly suggest not do do 2, 3., and 4., all of them sounds like "swimming against the stream", and will most likely only cause issues in the future.

I've raised https://github.com/kubernetes-sigs/controller-runtime/issues/687 to get some clarity on this. If we get an OK upstream for this approach, I don't really see an issue with alternative 3 at least.

> I would suggest to go for 1. … However, I would not mix IoT with "standard messaging". We already have the "modules" in the operator, so the code can sit in the same repo and image. However you might want decide and not install IoT (not sure why you want to do this, but hey wink). That option would then no longer be possible.

I don't think there is any point in keeping it separate, as the enmasse-operator already enables the module for iotconfig, all IoT CRDs are created etc. EnMasse is effectively including IoT support already. I think we should enable the iotproject module in the enmasse operator if we sort out the permissions problem.

> So having another "global" operator is a good idea. But I think that should be a "global enmasse core" operator.

The main issue with this approach is the case where you create a MessagingUser referencing the password in a secret (or AddressSpace referencing certificates in a secret) in the same namespace as the MessagingUser. Now, the 'global' operator will not be able to watch that secret without cluster-wide secret permissions, and it won't help to grant it ability to watch that single secret, because the controller-runtime api will not allow watching it.

We should be wary of designing our way around Kubernetes. This is how we have ended up with design like the per-addressspace admin pod, or the infamous 'configserv'. This time, I'd like to design the architecture the way it makes sense for someone operating it, and not just for making our own work convenient.

**Comment by ctron** [comment]
> The main issue with this approach is the case where you create a MessagingUser referencing the password in a secret (or AddressSpace referencing certificates in a secret) in the same namespace as the MessagingUser. Now, the 'global' operator will not be able to watch that secret without cluster-wide secret permissions, and it won't help to grant it ability to watch that single secret, because the controller-runtime api will not allow watching it.

But you could simply "read" the secret. That already works with the updated controller-runtime. You need to use the "API reader" though. It will not set up a watch. Of course this would mean that updating the messaging user secret would be delayed by the reconcile period of the MessagingUser CRD.

**Comment by k-wall** [comment]
I like the sound of 3 - providing that there is a genuine willingness on the part of the upstream community for this change in the medium term.   I don't think the short term measure needs to be time based - can't you just list/watch the messaging users global using the client-go library directly (that's what I'm doing with the console backend work).

**Comment by vbusch** [comment]
Option 1 sounds the simplest.  Option 3 would provide the nicer longer term solution, if upstream kubernetes is willing to allow support to be added for watching both local & global namespaces.  I would aim for option 3, provided your [kubernetes-sigs/controller-runtime#687](https://github.com/kubernetes-sigs/controller-runtime/issues/687) isn't rejected.

**Comment by lulf** [comment]
I have raised a PR for the required-functionality in controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/pull/692 and incorporated this into a development branch for now.

**Comment by matskiv** [comment]
If you would go with Option 3, and have operator watch local namespace with some controllers, and watch all namespaces with other controllers, how are you going to securely use two different ServiceAccounts with one operator?

**Comment by lulf** [comment]
@matskiv They would use the same service account, which has the required privileges for watching local namespace resources and the required privileges for resources watched across namespaces. The latter are restricted to our own CRDs types.

**Comment by matskiv** [comment]
@lulf Makes sense, I don't know why I thought you would use cluster permissions for all the resources :). Thanks for the explanation.

Anyway, +1 on this issue, it was fairly confusing to not being able to find CRDs for enmasse custom types.
