### ISSUE TITLE
CSV manifest is missing configmap finalizers permission

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#3410]
**Describe the bug**
When deploying EnMasse using OLM, the api-server fails to create configmaps due to a missing permission on configmaps/finalizers. This permission was added to the regular deployment permissions, but is missing for all service accounts in the CSV.

**To Reproduce**
1. Deploy EnMasse using OLM
2. Try to create address space

**Expected behavior**

Address space is created

**Comment by matskiv** [comment]
There seems to be a typo in a fix for this issue:
https://github.com/EnMasseProject/enmasse/blob/efc4dc020a2138857c8c9adba6428323fabfb432/olm-manifest/src/main/resources/manifests/0.30.1/enmasse.0.30.1.clusterserviceversion.yaml#L481

Correct resource name is `"configmaps/finalizers"`.

**Comment by lulf** [comment]
@matskiv Yes, it is fixed in the release-0.30 branch, and we're going to create a 0.30.2 with a fix (+ some other fixes related to fsgroups).

**Comment by matskiv** [comment]
@lulf Great! Thanks for the info.
