### ISSUE TITLE
Requirements for shared infrastructure

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#3420]
## Overview

Address spaces in EnMasse are currently isolated, i.e. they don't share infrastructure (router network, brokers). Moreover, the standard-controller and agent deployments are created per address space. Sharing infrastructure allows sharing resources and reducing the footprint when configuring multiple address spaces.

Before writing a design proposal up, some discussion about the general direction we want to take needs to take place. Once there is a quorum, I will write down a more detailed proposal.

Here is an initial set of questions that I feel we need to discuss:

1. Which address space types should shared infra apply to?
2. Do we support only 1 or multiple instances of shared infra?
3. How does the service-admin configure the shared infrastructure?
4. How does the messaging tenant use the shared infrastructure?
5. How is the shared infrastructure managed? (I.e. by which components)
6. How are plans applied in shared infra?

Changes are required to be backwards-compatible with existing APIs, but the design will consider the 'ideal' architecture to set an initial goal to work towards and propose tasks that can be carried out once a backward-incompatible change can be made.

I will provide my views on the above questions, and throw out a few ideas to trigger the discussion.

## 1. Which address space types does shared infra apply to?

I think both `standard` and `brokered` address space types are good candidates for shared infra. `standard` because it allows brokers to scale horizontally and can support many addresses only limited by the router. `brokered` because it would allow resource sharing of a broker/broker-cluster which would make for a feature-rich deployment and allow bridging for the brokered space.

For `brokered`, I think shared infrastructure means we have to deploy the dispatch router to get the 'virtual broker' feature. Deploying the router would make the `standard` and `brokered` address spaces more similar and maybe we should rethink that. I think a key difference is that for `brokered`, the broker(s) are configured as a 'broker cluster', and there is no scaling logic part of the enmasse operator. With the router features for always doing link forwarding, one would get most of the broker features as today.

<b>Should we still support todays brokered address space deploying a single broker? Or is that use case better served via a broker operator instead?</b>

An attractive option is that we leave both existing address space types as is, and introduce a new address space type for anything 'shared' that supports the features of both 'standard' and 'brokered'. In that context, the desired semantics could be specified as a property of the address instead (i.e. 'transactions'), and the operator would take care to ensure its allocated to the link-routed broker cluster. Once the shared type supports all desired address semantics, the existing standard and brokered infra can go away, and we get rid of address space types....

## 2. Do we support 1 or multiple instances of shared infra?

In the future, with the move the CRDs for all resources, I think we are in a better position to allow multiple EnMasse instances on a cluster. The question is then if multiple shared infra instances is better handled that way than needing to handle that within a single instance.

However, if we are to eventually replace 'brokered' and 'standard' with the new 'shared' infra type, then we probably need a way to create dedicated instances for some installations where installing multiple EnMasse instances is not an option.

## 3. How does the service admin configure the infrastructure?

For compatibility reasons, I think the existing StandardInfraConfig and BrokeredInfraConfig should be used to configure the existing address space types. A new address space type `shared` combined with a `SharedInfraConfig` can be used to configure the shared infrastructure(s). 

~~However, in a world without backward-compatibility and with support for multiple EnMasse instances/operators per cluster, I would like to consider the following: A new CRD `enmasse`, which would contain what is currently part of the singleton resources `ConsoleService` (under .spec.console`), `IoTConfig` (under .spec.iot) and `StandardInfraConfig/BrokeredInfraConfig` (under .spec.infra.standard?) etc. A service-admin can then decide to either deploy 1 operator + 1 CR instance as today, or deploy multiple operators managing multiple instances (each independent of eachother).~~

## 4. How does the messaging tenant use the shared infrastructure?

IMO this should work exactly the same way as before. The plans and infra from the service admin dictate if dedicated or shared infra will be used.

## 5. How is the shared infrastructure managed? (I.e. by which components)

I think the end-goal should be that that all infra is managed by enmasse-operator. However, the path to that end goal I think is:

* Phase 1: Create initial `shared` address space type purely managed by enmasse-operator. This address space type supports all features from standard address space except MQTT. Deprecate standard address space. Use router operator to deploy routers.
* Step 2: Add support for deploying broker clusters using broker operator and introduce address properties to select 'broker'-semantics like 'transactions'. These addresses will be put on the broker cluster. Deprecate brokered address space
* Step 3: Remove standard and brokered address space once 'shared' supports the desired set of semantics.

I think splitting it up like this will allow us to perform the work in pieces while maintaining a stable and functional system for existing deployments.

## 6. How are plans applied in shared infra?

With shared infra, the limits in plans will have to translate to 'something else' than infra. IMO I think they can make a good use as a quota system, i.e. a shared infra with 3 routers can support 10 address space plans with resource limit 'router: 0.1'). The credits of address space plans and address plans would have to be adjusted/lowered to take into account shared infra.

In example-plans, we can provide example plans that ends up using the shared infra.

I think once the router and broker supports a more fine-grained level of limitations, we should map the current set of credits to connection, link limits, per-address memory limits in broker etc. We should consider expanding the address space plan with settings not specific to infra, like max connections, sessions, links etc. in order to allow defining different limits for different tenants in the address space.

**Comment by grs** [comment]
For reducing footprint, in my mind there is a clear distinction between the managing infrastructure (various controllers, console servers etc) and the messaging infrastructure (i.e. the router and brokers).

For the former, consolidation and multi-tenant/multi-namespace support seems like a very sensible direction to move in.

For the latter, has horizontal scalability for throughput (which I think is always going to be a key metric for this kind of solution) actually been demonstrated? If so are there any limits? I think these would be vital questions to answer.

Is it the case that the footprint of router and broker containers cannot be reduced sufficiently to justify exclusive use? Has that been verified? If so what are the lowest operational footprints respectively?

**Comment by lulf** [comment]
> For the latter, has horizontal scalability for throughput (which I think is always going to be a key metric for this kind of solution) actually been demonstrated? If so are there any limits? I think these would be vital questions to answer.

I don't think this solution is advocating throughput scalability, but being able to pack address spaces more densely and to improve general utilization of the infrastructure. One alternative is to allow creating multiple instances of these shared environments, which should give the same benefit as exists today. 

> Is it the case that the footprint of router and broker containers cannot be reduced sufficiently to justify exclusive use? Has that been verified? If so what are the lowest operational footprints respectively?

The base footprint of an idle router is about 60 MB RSS. For a broker, its about 500 MB (gives a JVM heap of 250 MB). 

Given that we are anyway rewriting the operators, I think the additional work of supporting shared infra on address spaces is minimal and is worth the additional effort required. It does not prevent continued use of exclusive infra per address space, but instead greater flexibility to meet different use cases.

One use case of this is the IoT integration, where you might have a lot of low traffic volume address spaces (one per IoT tenant).

**Comment by grs** [comment]
> I don't think this solution is advocating throughput scalability

But what will tenants expect? Do we even know what expectations to set there? What is a realistic aggregate throughput?

> being able to pack address spaces more densely and to improve general utilization of the infrastructure

Is it not the case though that each address increases the memory footprint? Have we verified that there is no way to e.g. have two routers that divide the total number of addresses at a comparable overall footprint than one router hosting them all?

> Given that we are anyway rewriting the operators, I think the additional work of supporting shared infra on address spaces is minimal and is worth the additional effort required.

I suspect there will be more than initially meets the eye (essentially it is another layer of virtualization). Whether it is worth it depends on how much you actually save on footprint. However if it is simply an option, and it is understood that a given infrastructure may have an upper limit in capacity (which ideally we would know) and you are not relying on scaling that to host all addresspaces then the concern is mitigated to some extent.

**Comment by lulf** [comment]
> But what will tenants expect? Do we even know what expectations to set there? What is a realistic aggregate throughput?

I would expect that dedicated shared instances would perform about the same as today (- router vhost overhead, if any). If they are shared between multiple address spaces, I think a realistic aggregate throughput is that you can sort of divide the max throughput of a dedicated instance by the number of address spaces (assuming uniform distribution of addresses, clients etc). We can offer ways to tune limits for different address space plans to handle heterogeneous address spaces.

> Is it not the case though that each address increases the memory footprint? Have we verified that there is no way to e.g. have two routers that divide the total number of addresses at a comparable overall footprint than one router hosting them all?

I do think that the those two configurations can give comparable memory usage in cases where you have many addresses and/or connections, because the constant base cost of a router would be insignificant to the cost of addresses. 

So to answer your question: yes for some cases splitting addresses across separate routers makes sense, hence why we should continue to support that type of configuration.

**Comment by grs** [comment]
> I think a realistic aggregate throughput is that you can sort of divide the max throughput of a dedicated instance by the number of address spaces

Agreed. Do we know what that max throughput is? (That would determine how many address-spaces you could reasonably expect to share).

> I do think that the those two configurations can give comparable memory usage in cases where you have many addresses and/or connections, because the constant base cost of a router would be insignificant to the cost of addresses.

What would be the point at which the cost of the addresses would start to outweigh the base footprint? That would start to define the envelope within which the sharing of messaging infrastructure would have some benefit. (e.g. if you have one address per address-space, you could save the full router footprint on each extra address space up to some quite high number. For 10 addresses per address space the saving would be slightly less etc).

Is the intention for address-spaces from different 'owners' to share infrastructure? Or just for a given 'owner' to be able to define lower overhead namespaces?

**Comment by rgodfrey** [comment]
The other (potential) advantage for shared infrastructure is that in order
to create an address space (potentially for just short term use - e.g.
running a test) no new pods need to be deployed, etc... which I would hope
would reduce the amount of time for an address space to become ready.

-- Rob

**Comment by lulf** [comment]
> Agreed. Do we know what that max throughput is? (That would determine how many address-spaces you could reasonably expect to share).

It depends on many things, last i checked, it was in the ballpark of 80-100k msgs/sec for anycast and maybe 10k-20k msgs/sec for queues.

> What would be the point at which the cost of the addresses would start to outweigh the base footprint? That would start to define the envelope within which the sharing of messaging infrastructure would have some benefit. (e.g. if you have one address per address-space, you could save the full router footprint on each extra address space up to some quite high number. For 10 addresses per address space the saving would be slightly less etc).

For the sake of simplicity, I'm basing this on anycast:

* 7k memory required for each anycast address
* Message size is 128 bytes
* 18k memory required for each client link
* Assumption: 1 link per address and link capacity of 10
* Anything below 10% overhead is defined as the tipping point
* Router base memory of 60 MB RSS

Tipping point then becomes about 600MB which is:
```
600 * 1024 * 1024 / ((7 * 1024) + (18 * 1024 * 10)) = 3285.56149732620320855614
```

So at about 3200 addresses => router base memory accounts for < 10% of the router memory usage. So for 10 address spaces => 320 addresses per address space.

This is of course making a lot of assumptions, and for queues the tipping point would be lower.

> Is the intention for address-spaces from different 'owners' to share infrastructure? Or just for a given 'owner' to be able to define lower overhead namespaces?

I'm not sure what you define 'owner' to be. Assuming it is what we call a 'messaging tenant', yes then it is possible that different tenants share infrastructure. However, in most cases the tenants represent different groups within an organization, and its up to the service admin (i.e. the operations team within that organization) to what plans they want to offer to the teams.

**Comment by grs** [comment]
That is not too bad for address count (and possibly it is even higher? is the factor for link capacity really the 18k for the link base cost?). It does seem to me that the throughput is more likely to be the problem (1-2k msgs/sec for queues per address space seems more restrictive than 160+ addresses). However I guess there are many and varied cases. Though I remain somewhat sceptical I'm much less concerned if this is simply an option to allow for that variation.

**Comment by k-wall** [comment]
One feature of the Broker address spaces that would be lost by the approach advocated about is the multi-protocol support (STOMP, MQTT, Core etc).   Is that desirable?

**Comment by k-wall** [comment]
A second feature that would be lost if brokered removed is transactions spanning multiple addresses (tagging an address as requiring transaction semantics would not be sufficient to enable a multi-address txn as there would be no guarantee that the resource is on the same broker).

**Comment by lulf** [comment]
@k-wall Not saying these are good alternatives, but just throwing it out there...

> One feature of the Brokered address spaces that would be lost by the approach advocated about is the multi-protocol support (STOMP, MQTT, Core etc). Is that desirable?

One could perhaps be able to give a hint which protocols should be available when creating the address space? This would in turn create dedicated broker instances if required. Alternatively, maybe we could put some restrictions on the addresses of such address spaces, that they have to be prefixed with a address-space unique prefix?

> A second feature that would be lost if brokered removed is transactions spanning multiple addresses (tagging an address as requiring transaction semantics would not be sufficient to enable a multi-address txn as there would be no guarantee that the resource is on the same broker).

Would it not be enough to state that 'all addresses involved in a transaction must be marked with the 'transactional' property' to ensure they are part of the same broker cluster? (Cluster == artemis cluster of brokers).

**Comment by lulf** [comment]
@EnMasseProject/dev - I've raised #3455 with an initial proposal based on the feedback in this issue. Please have a look.
