### ISSUE TITLE
Restructure IoT documentation

### ISSUE THREAD

**Issue by dejanb** [EnMasseProject/enmasse#3423]
**Overview**

Provide better structure for IoT documentation.
**Design**

Here's the proposed structure we could have in the long term. We can start restructuring the current material to go into this direction and add missing material

# Overview
## IoT connectivity concepts
This we already have in basic for for now.

## Getting Started
This will also mainly remain the same, we'll just move parts to different sections and assemble them back here.

# Service admin guide

## IoT services
Explains IoT operator functionality, device registry, etc.

## Installing IoT services
This should hold current "Installing IoT services" section up until configuration.

## IoT Configuration
Explains and shows examples of IoTConfiguration CRD

### Deploy IoT Configuration
Shows current step to deploy example configuration

## Device registry
This section should contain more information about how device registry work and what we can configure.
We can start by adding more material on how it works.

## Protocol adapters
This section should contain more information about particular protocol adapters and how to configure them.

### Sigfox integration
We should move current Sigfox section here

## Monitoring
Here we should put all information about monitoring when we have it.

# Tenant guide

### Device Management API
Documents the API (Swagger)

### Managing devices
Provides examples (maybe we can do this all in previous section)

## Consumer applications
Explains how to write back-end applications
Shows current example with Hono CLI tool

## Device applications
Explains how to send and receive data from the devices using different protocols
Shows current examples

#### Commands

**Tasklist**

We should tackle this in the multiple smaller prs like

* Split the current documentation into main sections (overview, admin, tenant)
* Split admin guide into the proper sections and add more intro material about services and config
* Add more documentation about configuring device registry
* Add more documentation about configuring protocol adapters

**Comment by dejanb** [comment]
@jenmalloy @ctron @lulf Take a look at the proposed IoT doc structure and let me know if it makes sense to you. I'll start working on PRs as stated in the tasklist

**Comment by jenmalloy** [comment]
@dejanb, lgtm, based on what we discussed in the docs meeting
