### ISSUE TITLE
Allow monitoring resources to be created when using enmasse operator

### ISSUE THREAD

**Issue by david-martin** [EnMasseProject/enmasse#3437]
**Overview**

Currently in Integreatly on OpenShift 3, Enmasse is installed via ansible bundle. For Integreatly on OpenShift 4 we are using the enmasse operator to install & manage it. Integreatly depends on monitoring resources (Alerts & Dashboards) that are specific to Enmasse. In the ansible bundle, there is a ‘monitoring’ var to instruct the installer to create these monitoring resources. However, in the enmasse operator there is no equivalent. This means Integreatly is missing valuable monitoring when running on OpenShift 4.

**Design**

TBD

Ideally there is a field in a CR (e.g. ConsoleService) that can be set accordingly so the operator creates these resources.

**Tasklist**

TBD

**Comment by david-martin** [comment]
cc @lulf

**Comment by lulf** [comment]
I think we should support installing the monitoring CRs in some way via the operator. Ideally, I think we should have an "enmasse" CRD where the current ConsoleService, IoTConfig, monitoring schema/settings and more could live. 

An alternative shorter term could perhaps be to add MONITORING_ENABLE environment variable to enmasse-operator.

wdyt @k-wall @ctron @vbusch @robshelly  ?

**Comment by ctron** [comment]
I don't think having an über CRD makes sense. Different parts might evolve in different paces, having a single big CRD would make it more complex updating that.

And for IoT, we might end up at some point having multiple IoT configurations available.

Also I don't really see the benefit of having a big CRD, compared to having a modularized configuration.

**Comment by lulf** [comment]
> I don't think having an über CRD makes sense. Different parts might evolve in different paces, having a single big CRD would make it more complex updating that.

That they evolve at different pace is fine, as long as things are released and tested together. Having it in a single CRD could make it easier to coordinate changes affecting multiple parts of the schema. I.e. common configuration applied to all enmasse components, even iot, could be kept in the same place. I can understand how IoT might be a bit different to things like console though.

> Also I don't really see the benefit of having a big CRD, compared to having a modularized configuration

I see the main benefit as making EnMasse simpler to understand for a new user or a service admin. Having to wrap your head around all our CRDs might make sense to us as developers who know this very well, but I think its harder for everyone else. IMO sometimes we should focus on user experience, not what makes sense to us from a code point of view.

What would be your preferred alternative to the uber CRD for monitoring?

**Comment by ctron** [comment]
I think we should follow the concept that OpenShift 4 has, to have a single CRD for each major aspect of the system:

~~~
[jreimann@jreimann ~]$ oc get -A infrastructures.config.openshift.io
NAME      AGE
cluster   111d
[jreimann@jreimann ~]$ oc get -A dnses.config.openshift.io
NAME      AGE
cluster   111d
[jreimann@jreimann ~]$ oc get -A schedulers.config.openshift.io
NAME      AGE
cluster   111d
~~~

Having a single CRD for monitoring, console, IoT, tracing, … makes sense to me. Having a single CRD for enmasse is to big in my opinion.

I also think that e.g a monitoring CRD would be used across components. Meaning: there should only be a single monitoring CRD, not one for EnMasse, IoT and Console.

**Comment by lulf** [comment]
> I think we should follow the concept that OpenShift 4 has, to have a single CRD for each major aspect of the system

I think it remains to be seen how easy users will find it to understand the over 100 CRDs in OpenShift, but point taken :) 

> I also think that e.g a monitoring CRD would be used across components. Meaning: there should only be a single monitoring CRD, not one for EnMasse, IoT and Console.

I kind of like that, good idea.

**Comment by david-martin** [comment]
@lulf @ctron What are the touchpoints for adding a new CRD?

I'd imagine one of them is adding a new monitoring_controller to the enmasse operator, with the sole purpose of creating the various monitoring resources if a Monitoring CRD exists?

I can't think of any fields the CRD might need at this time

**Comment by lulf** [comment]
@david-martin Yes, that would be my expectation. I'd like some comments from more of the team on this before we decide the direction though. @k-wall @robshelly @rgodfrey .

**Comment by rgodfrey** [comment]
@lulf @ctron So one of the discussions I was having recently was about having an uber-CRD (sorry Jens - can't be bothered to use an umlaut - also I think in this case we English have just stolen the word) such that the EnMasse operator can be installed, but nothing is laid down until there is an instance of the EnMasse CRD. In saying that I don't say that *everything* needs to be in that single CRD, there's certainly a case to be made for separating out IoT aspects for a start.  In terms of monitoring I'm not sure I see what the conceptual distinction is in having it as a section in an uber-crd versus an "uber-enmasse-monitoring" crd

**Comment by lulf** [comment]
I think we need some more rounds on this, and its maybe a bit early for us to decide/agree on the path forward at this point.

I propose that we go for now with a simple environment variable for the enmasse-operator to turn monitoring on/off so that we can get it into the next upstream release, while allowing us to think the design through wrt. how we want to model these CRDs. Would that work for you @david-martin ?

**Comment by david-martin** [comment]
We're using olm and an 'integreatly' OperatorSource and CatalogSource rather than ones directly from operatorhub for each product. We're syncing the crds and csv at specific version so we can reference them for a detereminstic deploy.
https://github.com/integr8ly/manifests/blob/master/integreatly-amq-online/amq-online-1.2.2/
If there was an env var, we'd have to modify the operator deployment in the csv after we sync it to integreatly repo, or do a patch of the deployment via kube api.

That sounds like a way forward for now.
Is this issue the best place to track further discussion for a way to do this via crd?

**Comment by lulf** [comment]
@david-martin This probably spans more than just monitoring, so we should raise a separate issue for the general CRD discussions. Feel free to keep this for the immediate work.

**Comment by david-martin** [comment]
@lulf Just to confirm, the immediate work would be:

- including monitoring resources in the bundling of the enmasse-operator
- adding an environment variable to the enmasse-operator
- based on this env var, install the monitoring resources to the same namespace as the enmasse-operator

And an optional task (up to you if this makes sense):
- update the ClusterServiceVersion file to set this env var to something by default (ideally true, but we can live with false and replacing the value when we take the csv file for the integreatly-operator)

**Comment by lulf** [comment]
@david-martin Yes, that sounds like a reasonable scope to me.

**Comment by david-martin** [comment]
Linking (private downstream) issue for immediate work https://issues.redhat.com/browse/INTLY-4672.
PR to follow, and will link it here.

**Comment by lulf** [comment]
Main feature needed by this issue is implemented. 1.0 will provide a Monitoring CRD based on #4107
