### ISSUE TITLE
address-config allows to replace type of already created address

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#346]
steps to reproduce:
1. deploy brokered address space by "addressSpace.json" and following command: 
**curl -X POST -H "content-type: application/json" --data-binary @addressSpace.json http://$(oc get route -o jsonpath='{.spec.host}' restapi)/v1/addressspaces**
2. create mytopic by "brokered_topic.json" and following command:
**curl -X POST -H "content-type: application/json" --data-binary @brokered_topic.json http://$(oc get route -o jsonpath='{.spec.host}' restapi)/v1/addresses/myspace3**
3. check if mytopic is "type":"topic" by following command (section: data->config.json) :
**oc get configmap -o yaml address-config-mytopic**
4. create mytopic by "brokered_queue.json" and following command:
**curl -X POST -H "content-type: application/json" --data-binary @brokered_queue.json http://$(oc get route -o jsonpath='{.spec.host}' restapi)/v1/addresses/myspace3**
- here some error message should be returned instead of _{"apiVersion":"enmasse.io/v1","kind":"AddressList","items":[{"metadata":{"name":"mytopic","addressSpace":"myspace3","uuid":"7f13ef30-88ed-3312-98a3-c2e2fc468f3b"},"spec":{"type":"queue","plan":"standard","address":"mytopic"},"status":{"isReady":false}}]}_
-  check that mytopic is "type":"queue" right now: **oc get configmap -o yaml address-config-mytopic**
- in web console is mytopic still visible like a topic

addressSpace.json 
```
{
    "apiVersion": "enmasse.io/v1",
    "kind": "AddressSpace",
    "metadata": {
        "name": "myspace3", 
        "namespace": "myspace3" 
    },
    "spec": {
        "type": "brokered",
	"authenticationService": {
	    "type": "none"
	}
    }
}
```

brokered_topic.json 
```
{
  "apiVersion": "enmasse.io/v1",
  "kind": "AddressList",
  "items": [
    {
      "metadata": {
        "name": "mytopic"
      },
      "spec": {
        "type": "topic"
      }
    }
  ]
}
```

brokered_queue.json 
```
{
  "apiVersion": "enmasse.io/v1",
  "kind": "AddressList",
  "items": [
    {
      "metadata": {
        "name": "mytopic"
      },
      "spec": {
        "type": "queue"
      }
    }
  ]
}


```

**Comment by tkratky** [comment]
In what format can I expected error response from server? something like this would be fine
```
{
  "error": {
      "msg": "text",
      "code": "code"
      }
}
```

**Comment by lulf** [comment]
@tkratky We haven't really defined a payload format for error responses so far.  We're relying on HTTP status codes and logs :) 

I think we should write up a design proposal for this and implement it across all APIs. This is important even though it will eventually looking to be used internally.

**Comment by tkratky** [comment]
@lulf I agree 
btw: also reproducible with "standard" address space

**Comment by tkratky** [comment]
@lulf this should be fixed, right?
