### ISSUE TITLE
ADDRESS_SPACE_ADMIN_SA not configurable

### ISSUE THREAD

**Issue by rpahli** [EnMasseProject/enmasse#3464]
**Describe the bug**

currently it is not posible to overrride `ADDRESS_SPACE_ADMIN_SA`.
I try to create a helm chart for enmasse but it is not posible to change the name for this variable. It  always has to be `address-space-admin`.

**Expected behavior**
I can overrride the service account for the admin deployment form outside.

**Comment by lulf** [comment]
@rpahli Why do you wish to make it configurable? There are some reliance on this name several places in the templates.

**Comment by lulf** [comment]
With 1.0, this SA will be removed, so I suggest that we close this issue and the Helm chart will be fine when created for 1.0
