### ISSUE TITLE
Installation via OLM in specific namespace fails

### ISSUE THREAD

**Issue by famartinrh** [EnMasseProject/enmasse#3478]
**Describe the bug**
Following the steps https://enmasse.io/documentation/master/openshift/#assembly-installing-configuring-olm-messaging to deploy enmasse via OLM in a specific namespace leads into a failed installation of the operator and the error shown is `unable to adopt APIService` 

**To Reproduce**
Follow the steps https://enmasse.io/documentation/master/openshift/#assembly-installing-configuring-olm-messaging

**Expected behavior**
enmasse successfully installed in namespace enmasse-infra via OLM

**Comment by lulf** [comment]
@famartinrh Could you share some more of the following details:

* Which OpenShift version
* Which EnMasse version
* Where do you see the error shown?

Following the documentation, installing via the UI, the operator installs in the custom namespace as expected for me on OpenShift 4.2, EnMasse 0.30.1. 

![ocp4install](https://user-images.githubusercontent.com/19670/69147980-8d1bad80-0ad3-11ea-9552-306d029eb790.png)

**Comment by lulf** [comment]
@famartinrh on master, I was able to install doing the following:

1. oc scale deployment community-operators -n openshift-marketplace --replicas=0
2. Apply the following file (to openshift-marketplace):
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: enmasse-source
  namespace: openshift-marketplace
  labels:
    app: enmasse
spec:
  displayName: EnMasse Operator Source
  image: quay.io/enmasse/olm-manifest:latest
  publisher: enmasse
  sourceType: grpc
```
3. Create the subscription in the UI pointing to the enmasse-infra namespace. The created subscription looks like this:

```apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2019-11-20T09:50:10Z"
  generation: 1
  name: enmasse
  namespace: enmasse-infra
  resourceVersion: "540315"
  selfLink: /apis/operators.coreos.com/v1alpha1/namespaces/enmasse-infra/subscriptions/enmasse
  uid: 2411999c-0b7b-11ea-82eb-52fdfc072182
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: enmasse
  source: enmasse-source
  sourceNamespace: openshift-marketplace
  startingCSV: enmasse.999.999.999
status:
  catalogHealth:
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: certified-operators
      namespace: openshift-marketplace
      resourceVersion: "539942"
      uid: 33d5cb4b-faf1-11e9-a63f-525400d602f2
    healthy: true
    lastUpdated: "2019-11-20T09:50:10Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: community-operators
      namespace: openshift-marketplace
      resourceVersion: "540103"
      uid: caed6ec4-0b7a-11ea-82eb-52fdfc072182
    healthy: true
    lastUpdated: "2019-11-20T09:50:10Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: enmasse-source
      namespace: openshift-marketplace
      resourceVersion: "539945"
      uid: e91c6818-0b7a-11ea-82eb-52fdfc072182
    healthy: true
    lastUpdated: "2019-11-20T09:50:10Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-operators
      namespace: openshift-marketplace
      resourceVersion: "539944"
      uid: 328dd704-faf1-11e9-a63f-525400d602f2
    healthy: true
    lastUpdated: "2019-11-20T09:50:10Z"
  conditions:
  - lastTransitionTime: "2019-11-20T09:50:10Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  currentCSV: enmasse.999.999.999
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-t5h94
    namespace: enmasse-infra
    resourceVersion: "540163"
    uid: 24205771-0b7b-11ea-82eb-52fdfc072182
  installedCSV: enmasse.999.999.999
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-t5h94
    uuid: 24205771-0b7b-11ea-82eb-52fdfc072182
  lastUpdated: "2019-11-20T09:50:17Z"
  state: AtLatestKnown
```

Howerver, I did notice an issue with fsGroup being set on address-space-controller preventing it to start up, but it is unrelated to the issue you were seeing I think.

**Comment by famartinrh** [comment]
Hey @lulf sorry for the delay in response, many thanks for the hints. 
Yes I'm using master and testing on ocp 4.2 and CRC, well actually I'm using whatever is pushed in `quay.io/enmasse/olm-manifest:latest` which should be more or less master . 
The error `unable to adopt APIService` was because of my mistake, env wasn't clean from previous tests (CRDs remaining,...).
Apart from that, following your steps I'm able to install the operator too, and address-space-controler isn't deployed, it's weird because the deployment stays with 0 of 1 pods and no pods are created, the same happens with standard-authservice, happens both in ocp4 and CRC.
And regarding install into a specific namespace using only the CLI I found the missing piece to make it work, before appliying the subscription an operatorgroup resource is needed in enmasse-infra namespace:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: enmasse-infra-group
  namespace: enmasse-infra
spec:
  targetNamespaces:
  - enmasse-infra
```
with this the operator gets deployed, the error with address-space-controller not being deployed remains

**Comment by famartinrh** [comment]
Related to the error I'm having with address-space-controller deployment not spawning pods, my bad not investigating any further, the error can be seen in the associated replica set which show the error `Error creating: pods "address-space-controller-7487678b76-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group]`
This happens installing current master via OLM into a specific namespace

**Comment by lulf** [comment]
@famartinrh Yes, this is fixed in #3482

**Comment by famartinrh** [comment]
oh @lulf didn't look like it would change the fsGroup value to any other so I though that PR wasn't going to fix this

**Comment by lulf** [comment]
@famartinrh The problem is that the fsGroup was applied to the address-space-controller, which was wrong. It should only be applied to standard-authservice. Another PR is required to ensure that it is applied/not applied to brokers though.

**Comment by k-wall** [comment]
#2714

**Comment by lulf** [comment]
@famartinrh Closable?

**Comment by famartinrh** [comment]
yes
