### ISSUE TITLE
Addresses stuck in configuring after kubernetes api server restart

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#3542]
**Describe the bug**
During Kubernetes API server restarts, the admin/agent pod seems to fail reconnecting its watch. Until restarted, new addresses are not provisioned. 

The steps to reproduce should be considered a working hypothesis for reproducing the issue and have not been confirmed.

**To Reproduce**
1. Create address space and wait until ready
2. Restart openshift api server(s)
3. Look for watch failure in agent log
3. Try to create new addresses and see them not getting provisioned

**Expected behavior**
Address is provisioned

**Additional context**
[agent.log](https://github.com/EnMasseProject/enmasse/files/3922879/agent.log)

**Comment by lulf** [comment]
I was able to trigger a similar issue locally. However, this time it was the standard-controller that never got notified of address creation after the restart, until it reached the resync point where the watch is recreated.

I think we should add a similar logic to the agent, i.e. recreate any watches at a specific resync interval (every 5 or 10 minutes) to recover from this kind of scenario.

**Comment by k-wall** [comment]
I'm also wondering if we should have the `error` event in agent's `Watcher.watch`restart the watch. The coding would need to take care not to start two watches if both `end` and `closed` get fired.

**Comment by k-wall** [comment]
The underlying reason that the watch 'stuck' remains unclear, however #3544 means that a similarly stuck watch will be automatically aborted and restarted by the period resync
