### ISSUE TITLE
broker in 'brokered' address space is not able to start due to: Attempting to obtain lock for directory: (/var/run/artemis//artemis-1)

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#357]
reproducible: time to time
### artemis log: 
Attempting to obtain lock for directory: (/var/run/artemis//artemis-1)
/opt/apache-artemis-2.3.0/bin/partitionPV.sh: line 4: /var/run/artemis//artemis-1/lock: Permission denied

### prerequisites: 
- enmasse running in multitenant mode 
- configured persistent storage for openshift v1.5<= 
```
MY_DIR=/tmp/mydir
mkdir -p ${MY_DIR}
chmod -R 777 ${MY_DIR}
oc process -f templates/build/persistent-volume.json HOST_DIR=/tmp/mydir NAME=pv01 | oc create -f 
```

### steps to reproduce
1. create brokered address space 
2. check log of broker pod

**Comment by lulf** [comment]
Can this be closed? IIRC it was due to dirty volumes?

**Comment by tkratky** [comment]
@lulf yes, can be closed
-> close
