### ISSUE TITLE
Unable to create the external authservice

### ISSUE THREAD

**Issue by aaron0609** [EnMasseProject/enmasse#3609]
**Describe the bug**
I'm using the enmasse 0.30.2, according to the documentation, we successfully created the standard-authservice but cannot create the external authservice for supporting amqps connection.

Here is my external yaml file:
`[txyang@xxxx-01 example-authservices]$ kubectl get AuthenticationService my-external-1 -o yaml
apiVersion: admin.enmasse.io/v1beta1
kind: AuthenticationService
metadata:
  creationTimestamp: 2020-01-02T03:19:47Z
  generation: 1
  name: my-external-1
  namespace: enmasse
  resourceVersion: "84099957"
  selfLink: /apis/admin.enmasse.io/v1beta1/namespaces/enmasse/authenticationservices/my-external-1
  uid: bb0cd69e-2d0e-11ea-bfad-fa163e39ca4f
spec:
  external:
    caCertSecret:
      name: api-server-cert
    host: xxxx-ops.com
    port: 5671
  type: external
status:
  caCertSecret:
    name: api-server-cert
  host: xxxx-ops.com
  port: 5671

[txyang@xxxx-01 example-authservices]$ kubectl get pods
NAME                                        READY     STATUS    RESTARTS   AGE
address-space-controller-554bd4bb69-b9pph   1/1       Running   0          1h
api-server-dd548f8bf-5cgpb                  1/1       Running   1          1h
enmasse-operator-6866767977-9zd6q           1/1       Running   1          1h
standard-authservice-55b9c9f68f-68gj5       1/1       Running   0          32m
`
We can't see the pod 'my-external-1-xxx' running as expected

**Comment by lulf** [comment]
@aaron0609 Were you able to figure out the issue? The authentication service itself does not have anything to do with supporting amqps or not, its used by the enmasse components to authentication messaging clients over any supported protocol.

**Comment by aaron0609** [comment]
> @aaron0609 Were you able to figure out the issue? The authentication service itself does not have anything to do with supporting amqps or not, its used by the enmasse components to authentication messaging clients over any supported protocol.

Thanks lulf! As my English level is limited so I finally get through to these paragraph after reading few more times. Now it works.
