### ISSUE TITLE
Error occurs when trying amqps connection

### ISSUE THREAD

**Issue by aaron0609** [EnMasseProject/enmasse#3615]
**Describe the bug**
After configuring the external authentication service, we tested the connection with the command:
python send.py -a amqps://admin:xxxxxx@xxxxxxx-ops.com:5671/telemetry/aaron

> [txyang@xxxx aaron]$ kubectl logs -f qdrouterd-q7tngfm8r9-0
> 2020-01-02 08:29:51.280787 +0000 SERVER (info) enabling remote authentication service hono-messaging.bosch-ops.com:5671
> 2020-01-02 08:29:51.285683 +0000 SERVER (info) [C470] Accepted connection to 0.0.0.0:5671 from 10.0.2.33:21993
> 2020-01-02 08:29:51.289350 +0000 AUTHSERVICE (warning) Downstream disconnected: amqp:connection:framing-error SSL Failure: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> 2020-01-02 08:29:51.289488 +0000 SERVER (info) [C469] Connection from 10.0.2.33:21992 (to 0.0.0.0:5671) failed: amqp:unauthorized-access Failed to authenticate client [mech=none]
> 2020-01-02 08:29:51.291120 +0000 SERVER (info) [C470] Connection from 10.0.2.33:21993 (to 0.0.0.0:5671) failed: amqp:connection:framing-error SSL Failure: Unknown error
> 2020-01-02 08:29:51.933514 +0000 SERVER (info) enabling remote authentication service hono-messaging.bosch-ops.com:5671
> 2020-01-02 08:29:51.939628 +0000 SERVER (info) [C471] Accepted connection to 0.0.0.0:5671 from
> 2020-01-02 08:29:51.939678 +0000 SERVER (info) [C471] Connection from  (to 0.0.0.0:5671) failed: proton:io Connection reset by peer - disconnected :5672
> 

And my addressspace is configured as following:

> apiVersion: enmasse.io/v1beta1
> kind: AddressSpace
> metadata:
>   name: hono
>   namespace: enmasse
> spec:
>   type: standard
>   plan: standard-unlimited
>   authenticationService:
>     name: my-external-1
>     type: external
>     overrides:
>       host: xxxxx-ops.com
>       port: 5671
>       caCertSecret:
>         name: api-server-cert  (Configured as the CA for domain xxxxx-ops.com)

Is there anything wrong with my settings? I thought I have followed all the steps in the document.

**Comment by lulf** [comment]
@aaron0609 Were you able to resolve the issue? It might be the command require some escaping of the forward slash

**Comment by aaron0609** [comment]
> @aaron0609 Were you able to resolve the issue? It might be the command require some escaping of the forward slash

Yes, the issue was resolved as I found external has nothing to do with amqps connection, creating the addressspace with specified certs can resolve the problem
Thanks
