### ISSUE TITLE
Configure router anti-affinity by default

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#3646]
**Description**

At present, router affinity is configured manually using StandardInfraConfig. However, since router deployments are unique to each address space, it must be configured after the address space is created, which is awkward.

To make it easier to use, router affinity with 'preferred scheduling' should be be enabled by default. This provides a more reasonable default, and will also cover the HA use case without needing to make any manual configuration.

**Design**

In address-space-controller, create preffered during scheduling anti-affinity rules on hostname if they are not explicitly specified.

**Comment by davidffrench** [comment]
@lulf Quick question on this issue. I was testing enmasse from master and the latest build. I can't see any pod anti-affinity on my broker or router statefulsets. I am wondering if I am doing something wrong, would you be able to check this the next time you have an install from master?

**Comment by lulf** [comment]
@davidffrench I would need to check this on my own cluster, reopening.

**Comment by davidffrench** [comment]
Thanks @lulf

**Comment by davidffrench** [comment]
Excellent, thank you @lulf
