### ISSUE TITLE
StandardInfraConfigSpecBroker allows to set globalMaxSize but is never used

### ISSUE THREAD

**Issue by famartinrh** [EnMasseProject/enmasse#3893]
**Describe the bug**

Currently we can set globalMaxSize in StandardInfraConfigSpecBroker and BrokeredInfraConfigSpec.
For the StandardInfra case it may be wrong because that value is set into the template but the template never uses that value, so I'm not sure if this is just a mistake and it makes sense to be able to set globalMaxSize to the broker in StandardInfra.
In BrokeredInfra is already ok, the value can be set and it works...

**Expected behavior**
Not sure, if it makes sense to set that setting then it should be used in the standard infra template and applied into broker.xml , if not that option should be removed from the CRD

**Comment by famartinrh** [comment]
well, looking at broker plugin files it seems that we actually try to set the global max size, so maybe it is just that the standard infra template is missing setting that env var

**Comment by lulf** [comment]
@famartinrh It is set by standard-controller:

https://github.com/EnMasseProject/enmasse/blob/master/standard-controller/src/main/java/io/enmasse/controller/standard/TemplateBrokerSetGenerator.java#L133

**Comment by famartinrh** [comment]
yes @lulf but the template never picks that value and puts it into the env var

**Comment by lulf** [comment]
@famartinrh 
https://github.com/EnMasseProject/enmasse/blob/master/standard-controller/src/main/resources/templates/queue-persisted.yaml#L296

https://github.com/EnMasseProject/enmasse/blob/master/standard-controller/src/main/resources/templates/queue-persisted.yaml#L194

**Comment by famartinrh** [comment]
it's clear now, thanks @lulf
