### ISSUE TITLE
Support new bundle format for metadata image

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#3990]
**Description**

The operator metadata image needs  to switch to a new bundle format specified at https://github.com/operator-framework/operator-registry

**Comment by lulf** [comment]
## Design

With the new bundle format, there will no longer be a need to keep old manifests in the repository. However, the new manifest image cannot be used standalone, because the current image refers to a previous version, which makes actually testing the image a bit harder.

A way to handle that would be for every build to publish an aggregated version of the manifest that includes all the previous versions + the current version. The latest release of this image would be used during the CI build.

The new image that includes all manifests would be named 'olm-registry', and can be referred to by a catalog source to be able to install EnMasse without using the operatorhub.io catalog.

@k-wall @kornys wdyt?

**Comment by k-wall** [comment]
@lulf would the aggregated bundle be an interim solution?   once the project had republished historical images for 1..n-1, n could then be tested as the replaces chain would be complete.

**Comment by lulf** [comment]
@k-wall I was thinking of the new index image as something we would build and publish for every release, so each release would just 'append' its manifests to the bundle.

**Comment by k-wall** [comment]
@lulf I understand now from our conversation in a different channel that the aggregated image will enable the system tests.

"OLM doesn't automatically load each manifest image, an index must be built. Building that index image as part of the enmasse build will allow systemtests as well as users to consume the operator."

+1 to your idea.
