### ISSUE TITLE
Hono Configuration 

### ISSUE THREAD

**Issue by astoycos** [EnMasseProject/enmasse#4032]
**Overview**

What is the feature/change being proposed, what use case does it solve?

I recently ran into an IOT use case where I wanted to stream video from an (IoT camera through enmasse to a Knative Service)[https://github.com/astoycos/iotKnativeSource], however to do so I needed to up Hono's HTTP Adapter's  `HONO_HTTP_MAX_PAYLOAD_SIZE` parameter since it defaults to the relatively small size of 2048 bytes.  To start I had to edit the Dockerfile found [here](https://github.com/EnMasseProject/enmasse/blob/master/iot/iot-http-adapter/Dockerfile) to include `ENV HONO_HTTP_MAX_PAYLOAD_SIZE=XXXXX` and then build Enmasse from scratch to get the required `iot-http-adapter.jar`.  Finally I built the image with the provided docker file, pushed it to my image registry and then changed the [following line](https://github.com/EnMasseProject/enmasse/blob/master/templates/enmasse-operator/050-Deployment-enmasse-operator.yaml#L75) to link to my custom image before I installed Enmasse on my openshift cluster. This was kind of a pain, and beyond just this use case wouldn't it make sense that most real users will eventually require custom configurations for the Hono adapters provided with the IOT services?

**Design**

I am not 100% sure on how to make [these vars](https://www.eclipse.org/hono/docs/admin-guide/http-adapter-config/) configurable through EnMasse, but at the very least It would be great to have some Docs better explaining how to go through the manual process I followed to do so.

Another initial Idea would be to make individual deployment yaml's for the various Adapters and allow the user to edit and redeploy/configure the adapters via Environment variables before EnMasse is installed to the cluster.  This would allow the user to have fine grain control over the config vars and have the ability to only deploy the adapters required for the application rather than always spinning up every adapter available. 

I am definitely around to help out with this/ other features if need be and would enjoy hearing other opinions/thoughts on this!

**Comment by dejanb** [comment]
@astoycos, have you tried setting 'maxPayloadSize' property for the HTTP adapter in the IoTConfig resource?

**Comment by ctron** [comment]
There is an `IoTConfig` custom resource named `default`, in the infrastructure namespace (normally `enmasse-infra`):

~~~yaml
apiVersion: iot.enmasse.io/v1alpha1
kind: IoTConfig
metadata:
  name: default
  namespace: enmasse-infra
spec:
  adapters:
    http:
      enabled: true
      options:
        maxPayloadSize: 16384 # 16KiB
~~~

**Comment by jbtrystram** [comment]
@astoycos you can look at the documentation for some examples : https://enmasse.io/documentation/master/openshift/#iot_services_configuration_examples

Look at the "Tuning the IoT protocol adapters example" you should find what you need.

**Comment by astoycos** [comment]
Awesome, Thanks, I definitely missed that section in the docs :)
