### ISSUE TITLE
Provide per-address space support credentials facilitating support access to the broker(s)

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4090]
**Overview**

For support purposes, operators (human) need to be able to understand the state of brokers within EnMasse.  In order to do this, they need to be able to query the Broker state using the Artemis CLI and execute JMX queries via Jolokia.

In EnMasse today, operators can rsh into the broker pods, but cannot use Artemis CLI or make JMX interactions via Jolokia as they do not have suitable credentials.  Certificate authentication is not possible as the Artemis CLI does not accept the key material.

Currently the Broker's design restricts it to [one JAAS login module](https://issues.redhat.com/browse/ENTMQBR-3359) and this is bound to the authentication provider of the end-user.  It would be inappropriate to expect support credentials to be added to this database.   

**Design**

In order to workaround ENTMQBR-3359, we can make an extension to the EnMasse SASL delegation plugin so that it may be configured to accept a  Kubernetes secret (containing randomly generated support credentials) as an addition authentication provider source.  The plugin would be hardcode to assign the support user a role sufficient powerful to run CLI/JMX commands.

Steps need to be taken to minimise the possibility that the Broker support user id conflicts with a user id from the end-user's domain (e.g. `support`, `admin` etc would be a poor choice).  Also it is important that the userid remains recognisable as support within the logs.    Generating a user id in the form `broker_suppport_<<uuid>>` will meet both requirements.

**Tasklist**

- [ ] address space controller to generate a per address space secret
- [ ] broker deployment/stateful templates to mount the secret on the broker's filesystem
- [ ] broker plugin to use load the secrets and use it  an authentication provider source and assign suitable role.

**Comment by rgodfrey** [comment]
So I think the plugin should read a filename/location from its configuration (which it can then use to get the secret) - this isn't explicitly stated above, but may be what you were intending anyway.

Ideally it would be nice if we can verify that connections using this id are only authenticated from localhost connections - I'm not sure if that will be possible with JMX

**Comment by k-wall** [comment]
Agree, plugin will  read a filename/location from its configuration.  Plugin itself will know nothing about the secret.

I'm planning to bind the Jolokia and a CORE acceptor used for support to localhost, so a support 
user will have to `oc rsh` to be able to access the interface.   I'm also *hoping* to be able to lock the support credentials to particular acceptors, but still need to validate what Artemis makes possible.
