### ISSUE TITLE
Unable to purge addresses in console on Kubernetes

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#4165]
**Describe the bug**
When deploying EnMasse on Kubernetes, I am not able to purge messages from queues using the console. This is on the branch for #4124, but after looking into the issue, it seems that the reason is that the agent process tries to authenticate the user token using the OpenShift User API, which is not available on Kubernetes.

**Expected behavior**
User can be authenticated.

**Additional context**
See #4124 for discussion on how to fix it.

**Comment by k-wall** [comment]
You are right, this was an oversight with the rework made for 0.31.  In 0.30 a call to openshift/users exited but is absence was tolerated.  Making it obligatory was never the intent.  TokenReview sounds appropriate.

**Comment by k-wall** [comment]
@lulf this should be closable in light of your work on #4124?

**Comment by lulf** [comment]
@k-wall Yes, I can confirm it is working with fixes in #4124
