### ISSUE TITLE
 [service-catalog] dashboard redirect to wrong page of console and user cant see his addressspaces

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4300]
In the Service Catalog, the Dashboard link now redirects to wrong page, and user can't see his newly created address space.

This was working at release-0.31.

**Comment by k-wall** [comment]
This worked until #4067, where the oauth-proxy skip_provider_button was set true.

The reason this worked when `skip_provider_button` `false` is that oauth_proxy's provider form (`sign_in.html`) captures the fragment from the request URI (the [rd](https://github.com/openshift/oauth-proxy/blob/master/templates.go#L284) field).  This is then passed to the server side on form submission, preserved, and used at the end of the Oauth workflow.

When `skip_provider_button` `true`, no form is used.  oauth-proxy stores the original request uri but this is without fragment.  Fragments are exclusively a client side concern, so this is by design.  When the authentication is complete oauth proxy redirects to this uri, thus meaning the context is lost.

I wonder if the defect actually sit with OpenShift? Shouldn't OpenShift's login forms be preserving the fragment identifier? I am not sure. I can't find any resource guiding on best practice.

To fix this bug:

1.  flip skip_provider_button back to false.
1. switch the UI use a different router.  I think this would necessitate a switch to 'real' HTTP server on the server side to map all the requests to a single resource (oauth-proxy built in HTTP server isn't capable of this).

**Comment by lulf** [comment]
@k-wall Yeah, maybe we can revert this change for now (for 0.32), and re-introduce it once we create the 0.x branch?
