### ISSUE TITLE
Dashboard : messages exchanged on "anycast" address disappear

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse#453]
I have tried to exchange messages using a `queue` and an `anycast` addresses.
Clients pairs exchange messages using above addresses, the "Dashboard" in the console shows the right diagram and the "Messages" circle is divided by messages exchanged on `queue` and on `anycast`. The total exchanged messages at the bottom is right.
If I move from the "Dashboard" page to another page and then come back to the "Dashboard", all the information about messages exchanged on the `anycast` address are disappeared. The "Messages" circle and the total at the bottom show only messages related to the `queue`.

**Comment by k-wall** [comment]
The console referred to by this issue has been replaced.
