### ISSUE TITLE
Create systemtests for open service broker api

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#460]

**Comment by tkratky** [comment]
@lulf can you provide an example how should we test "open service broker api" please?

**Comment by lulf** [comment]
I think there are 2 ways we should test it:

* Use selenium and go through the openshift console dialog to create address spaces and bindings
* Use the API as specified in the spec: https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md . This API can be used against the service-broker service in enmasse (needs to be enabled in the playbook when installing enmasse). The test should not really know much more detail than that, as it can query the API for services and parameters that can be used when creating instances.

I think the latter is most important as it allows us to test some more combinations of things, but a basic UI test would also be nice.

**Comment by lulf** [comment]
@tkratky To be a bit more specific there are really 4 operations I think that are most important to have tested well:

* Provisioning and deprovisioning
* Binding and unbinding

**Comment by tkratky** [comment]
got it, thank you

**Comment by tkratky** [comment]
tests are done in /io/enmasse/systemtest/common/catalog, merged with master but some of them are disabled
