### ISSUE TITLE
MQTT LWT to AMQP Connectivity/Presence service

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse#47]
The LWT feature is not a really "MQTT related" but is having it on top of AMQP.

In the mqtt-lwt project I see :

- the Netty MQTT coded dependency is used just for the MQTT QoS enum, that could be removed (using an "ad hoc" enum or just 0,1 or 2) -> no dependencies on MQTT related projects anymore
- the only two AmqpWillMessage and AmqpPublishMessage classes involved use standard AMQP but add two annotations "x-opt-mqtt-qos" and "x-opt-retain-message". The first one could be not related to MQTT so we could remove the "-mqtt-" and in part it's decoded using the durable AMQP field (https://github.com/EnMasseProject/enmasse/blob/master/documentation/mqtt-over-amqp/docs/operations_connection.md#will-information-to-the-last-will-and-testament-service). The retain part is more MQTT specific (for the will message) even if you could not specify it having retain=false by default.

My instinct (but more thinking is needed) is to have an amqp-lwt service, so outside of the whole "mqtt" umbrella.

Wdyt ? @lulf @grs @rgodfrey

**Comment by grs** [comment]
I agree, it can be independent of mqtt. Perhaps just x-opt-qos with defined values (even if they are same absolute values as mqtt, it would be defined as an amqp extension). Likewise for retain.

**Comment by ppatierno** [comment]
I'm updating this for having a more generic AMQP connectivity/presence service (so not just LWT). It means not just detecting disconnection and sending the "will" message but even detecting connection and publishing events for that.

- The MQTT LWT → AMQP LWT service, could become a more generic “AMQP Connectivity/Presence” service
- Speaking about pure AMQP clients, if a client wants to provide such feedback on his connectivity status, it has to attach a link to such a service (today it happens from the MQTT gateway to the $lwt address of the MQTT LWT service). Having this attached link, the service can publish a message on a system address (or maybe configurable ?) like “$connection” with info about the connected client (something got from the “link name” established by the client, i.e. client-id for MQTT use case).
- On this link, as it already happens today, an AMQP “will” message can be sent to the service from the client; such message will be stored by the service and delivered on brute client disconnection to the “will topic”.
- When a client detaches this link (brute or not), the service can send a message on a system address (or maybe configurable ?) like “$disconnection” with info about the disconnected client. At same time, as already happens today, the stored "will" messages is just deleted or sent to the "will topic".

In this way, if a service is interested in clients connection/disconnection it can acts as a receiver for $connection/$disconnection addresses.

The “will testament” part continues to work as today : when a brute disconnection happens, the service publishes the related “will” message to the “will topic”. At same time, the AMQP Connectivity service is in charge to store the received “will” messages (and delete them when needed) in a corresponding LWT store (today we have only a simple “in memory” implementation for that).

**Comment by kornys** [comment]
closing
