### ISSUE TITLE
Console should support all kubernetes native endpoints

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#4729]
**Overview**

enmasse 1.0 should support:
* NodePort
* LoadBalancer
* Ingress
* ClusterIP

and we should stop creating openshift specific `routes`

**Comment by lulf** [comment]
It already does @kornys , there is also tests for it.

**Comment by kornys** [comment]
@lulf so enmasse 1.0 does not support routes? And yes it is also for console

**Comment by lulf** [comment]
@kornys as long as routes are supported in openshift and there is no way to specify pass through TLS for ingress, we must support it.
