### ISSUE TITLE
Pods created in another namespace when creating addressspace

### ISSUE THREAD

**Issue by tiexinyang** [EnMasseProject/enmasse#4786]
I'm using Enmasse 0.31.0, I deployed two enmasse instance for testing purpose in both namespace enmasse01 & enmasse02, but now I found when I try to create an addressspace in namespace enmasse01, I will see the pods started in namespace enmasse02.

[root@XXXXXX]# kubectl get addressspace -n **enmasse01**
NAME      READY     PHASE         AGE
**hono      false     Configuring   1m**
[root@XXXXXXX]# kubectl get pods -n **enmasse02**
NAME                                        READY     STATUS    RESTARTS   AGE
address-space-controller-6bc68c986b-44f8j   1/1       Running   0          6d
admin.eed0e17-596c46b97b-sktkl              2/2       Running   0          1m
enmasse-operator-5544d9b758-gt4qp           1/1       Running   0          6d
qdrouterd-eed0e17-0                         0/1       Running   0          1m
standard-authservice-5cb7fd6956-6fstw       1/1       Running   0          6d

How does it happens?

**Comment by lulf** [comment]
@tiexinyang EnMasse does not support running multiple instances of the operator on a cluster at this point. By default, all operators watch all namespaces, so by running multiple instances, you would get things created twice. For 1.0, we may support multiple instances.

**Comment by tiexinyang** [comment]
> @tiexinyang EnMasse does not support running multiple instances of the operator on a cluster at this point. By default, all operators watch all namespaces, so by running multiple instances, you would get things created twice. For 1.0, we may support multiple instances.

Thanks, then I'll try to use multi addressspace for different applications
