### ISSUE TITLE
Allow specifying forwarder priority relative to other consumers

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#4815]
**Description**

To allow balancing local consumers vs remote consumers for a queue that is forwarded, allow specifying priority of a forwarder link relative to other local consumers of a queue.

**Design**

Expose a field in the forwarder named 'priority', which will be propagated to the AMQP link.

**Comment by k-wall** [comment]
So if the use case for this so one could favour consumption locally (Paris, for instance), rather than a say a WAN hope (Tokyo).
