### ISSUE TITLE
System-tests: count of created brokered address spaces should be reduced

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#486]
With increasing count of tests and with creating and deleting brokered address space for each of them are system-tests running for a very long time. 

One brokered address space should be created per class (or one for all brokered system-tests) for tests which doesn't require more address spaces.

**Comment by lulf** [comment]
Agreed. I think that tests that doesn't test that you can create/delete and use multiple address spaces etc. could reuse the same, just like we have the implicit 'testspace' for a lot of standard address space tests.

**Comment by tkratky** [comment]
@lulf Maybe in case that test failed we should remove default brokered address space and next test should create it again, because we can't be sure if testing environment is in good condition...

**Comment by lulf** [comment]
@tkratky good idea, +1

**Comment by tkratky** [comment]
https://github.com/EnMasseProject/enmasse/pull/530
