### ISSUE TITLE
Delete of messaging project resource stuck and does not delete endpoints and addresses

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#4904]
**To Reproduce**
1. install enmasse bundle
2. create default infra
3. create namespace and messaging project
4. create for example 10 messaging endpoints (all supported types) and 10 addresses
5. delete messaging project 

**Expected behavior**
I expect that addresses and endpoits will be deleted, If it remove finalizer from messaging project then project is removed and addresses and enpoints as well.

**Comment by lulf** [comment]
@kornys I don't agree that addresses and endpoints should get deleted when a messaging project is deleted.

From a Kubernetes perspective, the address and endpoints are created independently of the project, maybe even before, so removing the project should not cause them to be deleted IMO.

I'm open to relaxing the project finalizer and having the project being deletable even if endpoints and addresses exists, which would cause addresses and endpoints to be 'unconfigured' on the infrastructure. However, I think the danger of this approach is that someone accidentally deleting the project could end up with having all addresses being removed from the configuration (and queues deleted for instance).

Having the project not being deletable until addresses and endpoints have been removed seems like the safest way to avoid accidental data removal.

**Comment by kornys** [comment]
Then I do not understand whole new enmasse, it is confusing for me, resources are stuck when I want to delete it, becasue this resource is depended on this and on another resource :(
