### ISSUE TITLE
IoT crds should contain also another record in categories

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#5085]
**Overview**

Currently all enmasse + iot crds contains only one category `enmasse` which is fine if we want to query all enmasse + iot resources across whole cluster, but I think sometimes we want only get only all iot related resources so I think we should add another record into categories like iot or something similar. 

**Design**

Update types in go for iot crds.

**Comment by kornys** [comment]
@ctron wdyt?

**Comment by ctron** [comment]
I just added that, and removed it again: I had the `IoTTenant` resource with an alias of `iot` and added the category `iot` as well … that creates a conflict so you no longer can do `oc get iot` …

I think the normal user will only use `IoTTenant`, while the admin will only do `IoTInfrastructure` … most people will not do both at the same time.

And I think it is better to have `oc get iot` for normal users …

**Comment by kornys** [comment]
@ctron ok that was just idea, if you think it does not make sense Im going to close it

**Comment by ctron** [comment]
> @ctron ok that was just idea, if you think it does not make sense Im going to close it

It was a good one!
