### ISSUE TITLE
System-tests: brokered/standard: new test for keycloak persistent storage

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#523]
The keycloak data is now persisted and should survive a crash or restart of keycloak.
Some basic test should be implemented (authentication tests should be extended about this test): 

testStandardAuthenticationServiceRestart
1. create address space
2. create new user
3. assert that user is able to send/receive
4. restart keycloak 
5. assert that user is still able to send/receive
6. remove user

**Comment by kornys** [comment]
#524
