### ISSUE TITLE
System-tests: longtime: create new test for user authentication before/after restarting keycloak

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#524]
Wrt following issue: https://github.com/EnMasseProject/enmasse/issues/523 should be some longtime running test created, for example testCreateDeleteUsersLong from: [longtime scenarios](https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/systemtests/longtime-tests/scenarios.adoc) should be extended about restarting keycloak

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/562
