### ISSUE TITLE
System-tests: framework(clients tests): add comments what value can be set for each parameter

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#548]
it's not so clear for me: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/main/java/io/enmasse/systemtest/executor/client/Argument.java

for example 
- --timeout //value: (from: 0; to: 2 147 483 647) milliseconds/seconds/minutes/...
- --log-msgs //dict/json/...

or just put link to existing documentation please

**Comment by kornys** [comment]
I't so simple, what about run client wrapper with --help? 
answers for your questions: 
 --timeout = in seconds, e.g.( --timeout 2 -> means that client waits 2 sec in iteration between send/receive, when client cannot send/receive message)
 --log-msgs has dict/json/interop, but in systemtests we have to use only json.

**Comment by tkratky** [comment]
ok, thanks for the answer
