### ISSUE TITLE
console in brokered address space seems to lose communication with broker after broker restart

### ISSUE THREAD

**Issue by rgodfrey** [EnMasseProject/enmasse#564]
Scenario:

create a brokered address space, use the console to create some queues and topics, and send and receive messages.

Cause the broker to be restarted.

Attempt to create a new queue through the console - the new queue never becomes ready
Send messages to an existing queue - the stats on the existing queue as seen through the console do not update.

Example logs from agent during such a scenario: https://pastebin.com/raw/TbU1Tu9a

**Comment by grs** [comment]
Believed to be already fixed.
