### ISSUE TITLE
Hiding "NaN" misleading information while address are propagating

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#57]
_From @ppatierno on April 26, 2017 15:22_

While the addresses are propagating, it's fair to show the icon on the left side that explain that (the circles instead the checked green circle when propagation ends) but on the right side (i.e. messages in, ...) a "NaN" is showed that sounds like an error.
I would hide this part during propagation showing something like a "deploying ...." message until the system is ready and then showing the real info.

_Copied from original issue: EnMasseProject/routilities#10_

**Comment by lulf** [comment]
@grs I think this is fixed?

**Comment by grs** [comment]
yes I think so
