### ISSUE TITLE
Your user instructions assume a linux machine

### ISSUE THREAD

**Issue by thesteve0** [EnMasseProject/enmasse#586]
http://enmasse.io/documentation/master/getting_started/#deploying_enmasse

Most developers are on windows machines and can not run a shell script. Please fix your instructions to work for windows users.

**Comment by lulf** [comment]
@thesteve0 I don't have a windows machine to verify, but you can find the manual instructions here: http://enmasse.io/documentation/0.15.2/service_admin/

We have an open ticket #366 for providing easy to use scripts for windows.

**Comment by thesteve0** [comment]
Filed bugs for the instructions not working on Windows. Who do we need to elevate this to so you can have a Windows instance to test with?
