### ISSUE TITLE
Wrong senders/receivers values for a topic receiver

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#60]
_From @ppatierno on April 6, 2017 13:18_

When a receiver attaches on a topic, the "addresses" tab reports Senders = 2, Receivers = 2 as values.

_Copied from original issue: EnMasseProject/routilities#3_

**Comment by lulf** [comment]
_From @ppatierno on April 6, 2017 13:34_

I see that with link routing, we have two endpoints in the router and each of them has a "peer". When router stats are read, these two endpoints are taken into account so sender++ and receiver++, the reason why we have Senders=1, Receivers=1 even if I attach only a receiver but considering that it's link routing we have also a sender (on the broker) ... so it's right but ... it shouldn't be the stats that the user would see right ? The user would see the only one receiver taken into account.

Then the stats are got two times in a row. It's because the same information are taken from the co-located router deployed with the broker. The function for getting counters is executed twice (one for every router). So the reason why Senders=2, Receivers=2.

So what I see is that in router_stats.js the routers list has two entries, so the count_by_address function is executed twice and there for the topic link both the in/out endpoints are counted as sender/receiver.

**Comment by lulf** [comment]
Perhaps it could filter on links that are on the public listener ports 5672/5671?

**Comment by kornys** [comment]
we have a new console, close
