### ISSUE TITLE
WebConsole: filtering by type doesn't work

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#623]
### description: 
when 2 queues and 2 topics are created and filter for type(queue/topic/anycast/multicast) is added then no addresses are visible.

### steps to reproduce:
1. execute already existing test: 
```
#install firefox
make webdriver_install #install web driver
Xvfb :10 -ac & #start display virtualization
PATH=$PATH:$(pwd)/systemtests/web_driver DISPLAY=:10 make MULTITENANT=true SYSTEMTEST_ARGS='FirefoxWebConsoleTest#testFilterAddressesByType' systemtests #execute  already existing system-test with PATH set to geckodriver and set DISPLAY=:10
```
testName: testFilterAddressesByType
test description is in following file: https://github.com/EnMasseProject/enmasse/blob/webconsole-filter-test/documentation/design_docs/systemtests/selenium-tests/scenarios.adoc

**Comment by tkratky** [comment]
![testfilteraddressesbytype io enmasse systemtest brokered web firefoxwebconsoletest _2017-12-11_13 44 11 0896](https://user-images.githubusercontent.com/17743200/33849055-bd03953c-deaf-11e7-9d97-27ed5f088eea.png)
![testfilteraddressesbytype io enmasse systemtest brokered web firefoxwebconsoletest _2017-12-11_13 44 11 0560](https://user-images.githubusercontent.com/17743200/33849056-bd24eaca-deaf-11e7-9627-3d8797eb01f4.png)
![testfilteraddressesbytype io enmasse systemtest brokered web firefoxwebconsoletest _2017-12-11_13 44 10 0988](https://user-images.githubusercontent.com/17743200/33849058-bd51d8a0-deaf-11e7-9e3a-8d90cc38e5ef.png)

**Comment by kornys** [comment]
@grs fixed this issue, good job!
