### ISSUE TITLE
System-tests: webconsole: new test for testSortConnectionsByContainerID

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#638]
create test 'testSortConnectionsByClientID' by following document: https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/systemtests/selenium-tests/scenarios.adoc

if tests steps are not on place then must be defined

**Comment by kornys** [comment]
In connection tab there is no type for sort by ClientID -> closed

**Comment by kornys** [comment]
test is blocked by  #634

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/726
