### ISSUE TITLE
Support more than "Data" section in the AMQP_PUBLISH message

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#64]
_From @ppatierno on December 9, 2016 14:31_

If a message is published from a native AMQP client it could have an AMQP value as body so using the AMQP type system (i.e. simple type but even list, map, ...). It could be delivered to an MQTT client. Do we have to consider a different encoding in this case ? (i.e. JSON as body of the MQTT message)

_Copied from original issue: EnMasseProject/mqtt-gateway#10_

**Comment by lulf** [comment]
_From @ppatierno on December 16, 2016 10:44_

@grs @lulf what do you think about that ?

**Comment by k-wall** [comment]
The current behaviour (enmasse/mqtt/messages/AmqpPublishMessage.java:124) is to fail if the application-data section of the bare message contains anything other than a Data section.   For amp-value section that contain a string, the least surprise would be to give the MQTT client the UTF-8 bytes.    For other structured types, as mentioned above we'd want something such as JSON or possible something like msgpack.   I note that the Artemis, in this situation gives the MQTT client what it calls TypedProperties which I don't think is standards based.

Separately, I notice that Proton-J does not handle bare-messages containing multiple data sections or multiple sequences.
