### ISSUE TITLE
System-tests: webconsole: new test for  testFilterConnectionsByContainer

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#642]
create test 'testFilterConnectionsByContainer' by following document: https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/systemtests/selenium-tests/scenarios.adoc

if tests steps are not on place then must be defined

**Comment by kornys** [comment]
Test is blocked by  #634

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/726
