### ISSUE TITLE
Web Console: connection item does not show count of senders correctly

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#649]
Connection item in connections tab on web-console doesn't show count of senders in one connection correctly. I attached 10 senders of one container using rhea and console shows that count of senders is 0, when all senders start sending messages, console show that count of senders is 1.

1. create brokered address space
2. create queue "testQueue"
3. use reproducer bellow

```javascript
var container = require('rhea');

container.on('sender_open', function() {
    console.log('sender attached');
});

container.on('sendable', function (context) {
    context.sender.send({body: 'test'});
});

var connection = container.connect({'host': "address of service", 'port': "port of service"})
var sender1 = connection.open_sender("testQueue");
var sender2 = connection.open_sender("testQueue");
var sender3 = connection.open_sender("testQueue");
```

**Comment by grs** [comment]
Artemis only returns one producer through the management schema when there are multiple sender links to the same address.
