### ISSUE TITLE
Brokered - Web-console: connection item does not fill columns Accepted,Rejected,Released...

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#659]
Connection item does not show Accepted, Rejected, and other information.
In this case I attached 25 senders and 25 receivers, all from one container.

```sh
$ npm install -g cli-rhea
$ cli-rhea-connector --broker user:password@[route]:443 --address test-queue --timeout 90 --conn-ssl true --sender-count 25 --receiver-count 25 --obj-ctrl CESR
```
![image](https://user-images.githubusercontent.com/11318335/34104482-e88ac374-e3f0-11e7-820a-aa9ff9fa8b2e.png)

**Comment by grs** [comment]
This is for brokered address spaces, is that right? If so can you update the title or description to make that clear. (And if not, likewise indicate that it covers both address-space types).

**Comment by kornys** [comment]
Yes it is for brokered address space, I will update it.

**Comment by grs** [comment]
The reason for this is that the necessary information is not exposed by the artemis management schema

**Comment by kornys** [comment]
Is it this same reason why there is not showed container ID ?

**Comment by grs** [comment]
Yes

**Comment by grs** [comment]
But good to collect all these defects, we can then decide if and how/when to fix them

**Comment by kornys** [comment]
#634

**Comment by kornys** [comment]
#633

**Comment by kornys** [comment]
@grs do you know if artemis 2.5.0 exposes these information?

**Comment by grs** [comment]
@kornys not as far as I am aware
