### ISSUE TITLE
Brokered/Standard: web-console: connection properties are not set properly within {} brackets

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#668]
reproducible via automated test in standard/brokered address space:
standard.web.FirefoxWebConsoleTest#testFilterConnectionsByUser' systemtests
brokered.web.FirefoxWebConsoleTest#testFilterConnectionsByUser' systemtests

For example: TODO!
```
#deploy enmasse
Xvfb :10 -ac & 
make webdriver_install
PATH=$PATH:$(pwd)/systemtests/web_driver DISPLAY=:10 make MULTITENANT=true SYSTEMTEST_ARGS='standard.web.FirefoxWebConsoleTest#testFilterConnectionsByUser' systemtests
```

![testfilterconnectionsbyuser io enmasse systemtest standard web firefoxwebconsoletest _2017-12-19_06 01 26 0103](https://user-images.githubusercontent.com/17743200/34158354-4fb1d6c6-e4c5-11e7-8ab6-a5d276b73dc8.png)

**Comment by kornys** [comment]
I will update rhea client to support setting these properties

**Comment by kornys** [comment]
I have updated cli-rhea client https://github.com/rh-messaging/cli-rhea/commit/8dd1b9f746229973b1b7e1276a71bf65b177b43b, I will update tests for set these properties.

**Comment by kornys** [comment]
#664

**Comment by kornys** [comment]
done
