### ISSUE TITLE
Brokered/Standard: web-console: encrypted/unencrypted connections 

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#669]
When the same client with the same connection properties (ssl-conn set to true) establish connection to
- standard address space then: connection is visible like encrypted (with locked lock icon)

![testfilterconnectionsbyencrypted io enmasse systemtest standard web firefoxwebconsoletest _2017-12-19_14 54 08 0763](https://user-images.githubusercontent.com/17743200/34160867-ea9a4318-e4ce-11e7-9f99-8c70e7358db8.png)

- brokered address space then: connection is visible like unencrypted (with unlocked lock icon)

reproducible via automated test in standard/brokered address space:
standard.web.FirefoxWebConsoleTest#testFilterConnectionsByEncrypted' systemtests
brokered.web.FirefoxWebConsoleTest#testFilterConnectionsByEncrypted' systemtests

```
#deploy enmasse
Xvfb :10 -ac & 
make webdriver_install
PATH=$PATH:$(pwd)/systemtests/web_driver DISPLAY=:10 make MULTITENANT=true SYSTEMTEST_ARGS='standard.web.FirefoxWebConsoleTest#testFilterConnectionsByEncrypted' systemtests
```

**Comment by grs** [comment]
At present the broker doesn't expose whether the connection uses TLS or not (the router does).

**Comment by tkratky** [comment]
Thank you for the answer. I fixed the test and disable this test in brokered address space until this issue will be fixed.
