### ISSUE TITLE
Install instructions are Broken for windows 10

### ISSUE THREAD

**Issue by thesteve0** [EnMasseProject/enmasse#674]
Tried to use enMasse with Windows 10. Used the suggested documentation

http://enmasse.io/documentation/0.15.3/#installing-openshift

In Step 1 of the Procedures the instructions fail when trying to make a cert. 

PS C:\users\Steve Pousty\Downloads\enmasse-0.15.3\none-authservice-cert> openssl req -new -x509 -batch -nodes -days 1100
0 -subj "/O=io.enmasse/CN=none-authservice.enmasse.svc.cluster.local" -out none-authservice-cert/tls.crt -keyout none-au
thservice-cert/tls.key
WARNING: can't open config file: /etc/ssl/openssl.cnf
Unable to load config info from /etc/ssl/openssl.cnf

I get the same error whether I try as a normal user or an Admin user.

**Comment by kornys** [comment]
I tried same commands on windows 10 in step 1 from http://enmasse.io/documentation/0.15.3/#installing-openshift  and openssl command works fine.

```
C:\redhat
λ mkdir -p none-authservice-cert

C:\redhat
λ openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=none-authservice.enmasse.svc.cluster.local" -out none-authservice-cert/tls.crt -keyout none-authservice-cert/tls.key
Generating a 2048 bit RSA private key
......................................+++
....................................................................................................+++
writing new private key to 'none-authservice-cert/tls.key'
-----
```

**Comment by thesteve0** [comment]
Oh I think I got it, the -out line is specifying where to write and if you don't do this command in a downloaded project directory at the top level it can't find the directory. Perhaps we can update the instructions to be more clear about where you need to run the command.

**Comment by kornys** [comment]
But it does not matter where you run the command, if you want to run this command in another folder just specify right path in out and keyout.
