### ISSUE TITLE
Add support for an external Keycloak to be managed by keycloak-controller

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#682]
The integrated Keycloak, as deployed with the "standard" authentication service option, might not meet all requirements in a production environment (e.g. concerning HA).

Therefore, there should be a feature to configure an *external* Keycloak instance to be "managed" by the keycloak-controller in the same way as the integrated, standard Keycloak would be managed. 
"Managed" meaning here that the keycloak-controller creates EnMasse-related resources in Keycloak.
This of course requires Keycloak admin credentials to be provided with the configuration.

This feature is different from the existing "external" authentication service option in that it explicitly requires a Keycloak instance with the SASL plugin behind the given address and that it requires Keycloak admin credentials.

**Comment by lulf** [comment]
So if I understand this issue correctly, we can either

* Add a .yaml for creating only the keycloak-controller and pointing it to the secret with the credentials + hostname for the keycloak service. Then you can pass the hostname to the 'external' keycloak instance as well

* Allow the standard-authservice template to be configured in the way you desire (HA etc...)

**Comment by calohmn** [comment]
I would opt for the 1st option, so that the keycloak instance can be truly external (on another cluster/machine/etc.).

**Comment by lulf** [comment]
@calohmn In terms of configuring the keycloak-controller, I suggest adding support for reading the hostname and port from a configmap that you can create. If this configmap doesn't contain the hostname and port, it will try to use the environment variables as before.

**Comment by calohmn** [comment]
Using a configMap to define hostname/port sounds ok to me.

So, the solution you envision would look like this:
- requiring the said configMap to override "STANDARD_AUTHSERVICE_SERVICE_HOST" / PORT
- when deploying enmasse, only the "keycloak-controller" part of "standard-authservice.yml" (along with the services) needs to be deployed
- in the config for the "default" addressspace, "authenticationService" with type "standard" is used
- the k8s secret with the certs for keycloak needs to be named "standard-authservice-cert"

correct?

**Comment by lulf** [comment]
@calohmn I have a prototype here: https://github.com/EnMasseProject/enmasse/blob/issue-682-self-managed-keycloak-controller/templates/install/kubernetes/addons/keycloak-controller.yaml

To use it you need to

* define a configmap keycloak-controller-config with a 'hostname' and 'port' field in the data section
* define a secret keycloak-credentials with the data fields 'admin.username' and 'admin.password' set to the admin user and password.
* define a secret keycloak-cert with a dafa field 'tls.crt' containing the CA to trust for the keycloak server.

You only need to deploy that .yaml along with the address-controller.
