### ISSUE TITLE
testBrokerReplicator(enmasse.broker.forwarder.ForwarderControllerTest) failed

### ISSUE THREAD

**Issue by grs** [EnMasseProject/enmasse#684]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.836 s <<< FAILURE! - in enmasse.broker.forwarder.ForwarderControllerTest
[ERROR] testBrokerReplicator(enmasse.broker.forwarder.ForwarderControllerTest)  Time elapsed: 5.43 s  <<< ERROR!
java.util.ConcurrentModificationException
	at enmasse.broker.forwarder.ForwarderControllerTest.testBrokerReplicator(ForwarderControllerTest.java:83)
[ERROR] Errors: 
[ERROR]   ForwarderControllerTest.testBrokerReplicator:83 » ConcurrentModification
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

**Comment by grs** [comment]
Probably only intermittent

**Comment by grs** [comment]
Seems to be intermittent (and infrequent), just recording as I hit it in testing

**Comment by kornys** [comment]
Test seems stable. I was running them in progress of refactoring to junit5 many times without fail.
