### ISSUE TITLE
Add an API and Console page to manage linked topic subscriptions

### ISSUE THREAD

**Issue by dejanb** [EnMasseProject/enmasse#696]
Currently there's no way to manage topic subscriptions, outside of the messaging clients. It'd be useful to have this feature, so that subscriptions could be statically configure together with addresses (topics). This is just a placeholder for this feature request.

**Comment by RH-sdavey** [comment]
@grs I think we can go ahead and close this issue, we have topic subscriptions fully implemented, is there any more to be done for this ?

**Comment by grs** [comment]
@RH-sdavey nothing for which there is not another issue, so I agree we can close this
