### ISSUE TITLE
Provide access to Artemis console (for easier developer debugging)

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#704]
It would be good to be able to use the Artemis console deployed within the Artemis container in order to debug brokered addresses.

Currently, this is prevented by the localhost restriction in `artemis/config_templates/bootstrap.xml` and `artemis/config_templates/jolokia-access.xml`.

Furthermore, the authentication mechanism of the console should be used (currently all credentials are accepted).

**Comment by lulf** [comment]
Agreed, this would be useful. I have a prototype of this with the correct permissions/certificates though there is some work/configuration still needed to get it to use the authentication service.

**Comment by lulf** [comment]
@calohmn A quick update on the current state. The PR #708 is ready for merge (waiting until our jenkins CI master build is green). The current state of things is:

* Hawtio in Artemis is configured to use the 'manage' role.
* Manage role is defined to allow: send, consume, createDurableQueue, deleteDurableQueue, createNonDurableQueue, deleteNonDurableQueue, manage and browse
* createAddress and deleteAddress is not allowed
* In keycloak, create a group called 'manage' within the appropriate realm, and assign to this group any users that should be allowed to use the console


Do you think this is sufficient?

**Comment by calohmn** [comment]
yes, sounds good.
