### ISSUE TITLE
standard address-space: "Error: No route to the destination node..." when any client try to connect to topic

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#706]
- **Env:** standard-address space with "topic" destination with "default" plan
- This error isn't 100% reproducible
- reproduced by following test (log in [attachment](https://github.com/EnMasseProject/enmasse/files/1618674 )): testSortConnectionsBySenders(io.enmasse.systemtest.standard.web.FirefoxWebConsoleTest)
all logs from address space attached: 
[standard-default-1.zip](https://github.com/EnMasseProject/enmasse/files/1618713/standard-default-1.zip)

**Comment by kornys** [comment]
fixed by https://github.com/EnMasseProject/enmasse/pull/1008
