### ISSUE TITLE
Dispatch Router crashes with memory corruption error

### ISSUE THREAD

**Issue by chapitos** [EnMasseProject/enmasse#711]
Testing with 1000 devices sending telemetry messages with a target throughput over all devices of 200 messages per second, we have noticed that the dispatch router crashed multiple times with the following error:

*** Error in `/sbin/qdrouterd': malloc(): memory corruption: 0x00007f135c274310 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x791eb)[0x7f1374ee61eb]
/lib64/libc.so.6(+0x8431e)[0x7f1374ef131e]
/lib64/libc.so.6(+0x84c8e)[0x7f1374ef1c8e]
/lib64/libc.so.6(posix_memalign+0x11d)[0x7f1374ef5fbd]
/usr/lib/qpid-dispatch/libqpid-dispatch.so(sys_mutex+0x21)[0x7f1375484601]
/usr/lib/qpid-dispatch/libqpid-dispatch.so(qd_message+0x116)[0x7f137547d946]

The router has restarted itself and crashed again after a while. The result was that a lot of messages being sent were lost.

Version of EnMasse in the test was 0.15.3.

Version of the router as per the log file is:

2018-01-08 12:14:58.792885 +0000 ROUTER (info) Version: 1.0.0

Complete log file attached.

**Comment by chapitos** [comment]
@lulf we do not have a single script you could use to test this. We have used Hono JMeter plugin (https://github.com/eclipse/hono/tree/master/jmeter) to implement load test where we can test with various number of publishers and receivers and tweak how many messages are coming through the system. EnMasse is deployed as Kubernets cluster. As for the configuration, we have not changed the defaults delivered with EnMasse.

**Comment by grs** [comment]
Would it be possible to test in your scenario with the following router image (you can do kubectl edit deployment to change this): docker.io/gordons/router:issue-711 (just to verify whether a fixed issue not in the current enmasse image might be responsible).

**Comment by chapitos** [comment]
@grs: we will try this as part of our load testing. The only problem is that we have seen this issue once and are not completely sure how to repeatedly reproduce this issue.
Can you clarify what issue is fixed in the image you have provided above?

**Comment by grs** [comment]
@chapitos  It includes a fix for https://issues.apache.org/jira/browse/DISPATCH-902 which is actually in proton (https://issues.apache.org/jira/browse/PROTON-1727) and is a little more general than the sepcific reproducer.

**Comment by lulf** [comment]
@chapitos This still an issue or can we close this?

**Comment by chapitos** [comment]
@lulf I have not seen this since. So I would say we can close it and open new one if it occurs again.
