### ISSUE TITLE
Make Artemis running within EnMasse configurable

### ISSUE THREAD

**Issue by chapitos** [EnMasseProject/enmasse#712]
Artemis running as part of Enmasse is not configurable from EnMasse context, using EnMasse configuration. In other words, there is no mapping between EnMasse configuration and Artemis configuration stored in broker*.xml files. 

For example, one is not able to configure the capacity of in-memory queue for brokered addresses, or the expired address. It would be handy in certain scenarios to have possibility to fine-tune Artemis.

**Comment by lulf** [comment]
@chapitos This is something we could expose (either as properties on address space for instance, but we're thinking about some alternatives as well).

If you have a list of configuration options you'd like to be able to set, that would help us a lot in trying to decide for how to expose it.

**Comment by chapitos** [comment]
@lulf : we do not have a particular list, but were looking at how can we avoid #710 by using setings described here: https://activemq.apache.org/artemis/docs/1.0.0/message-expiry.html
Looking at the configurations already available in broker*.xml files, the preliminary list would be:
* max-size-bytes
* expiry-address 
* message-expiry-scan-period to configure reaper thread

In addition, paging configuration (address-full-policy) could be also of interest (https://activemq.apache.org/artemis/docs/1.0.0/paging.html), although the default used (FAIL) is, for our use case, correct.

**Comment by lulf** [comment]
@grs @rgodfrey The expiry-address is an interesting one. To configure the expiry address of a queue, we could add a property to be set on the address upon creation, i.e.

```
{
  "kind": "Address",
  "spec": {
    "address": "myqueue",
    "type": "queue",
    "properties": {
       "expiry-address": "foo"
    }
  }
```

Then there is a question of how the expiry-address should be handled. We can either

   * Create it automatically based on the properties and make sure its present in the same brokers. This is probably the easiest
   * Require it to be created as a separate address, and have the brokers be able to send expired messages back into the router network to a particular expiry address. I think this is the nicest, but somewhat harder to do.

The max-size-bytes and message-expiry-scan-period can be added as a parameter to the plan or the address space upon creation which would configure the broker(s) with it.

**Comment by lulf** [comment]
This is covered in #4361
