### ISSUE TITLE
Consumer get no event messages after crash of qdrouterd pod

### ISSUE THREAD

**Issue by herfort** [EnMasseProject/enmasse#715]
I have EnMasse running a Kubernetes cluster. My producer sends event messages to a address which is configured as a topic and telemetry to a multicast address. The consumer is built on the basis of HonoClient and reads both message types from QPid.
If the qdrouterd pod crashed, the k8s starts a new one. I can see also that the admin pod was restarted. The consumer executes reconnect. 
After all pods are running I try to send the messages again. The telemetry messages are received from consumer. The event messages are stored in EnMasse (I can see it in the EnMasse console), but the consumer does not get any events.

Attached logs:

Result of qdstaat before QPid crashed:  
[qdstaat_before.log](https://github.com/EnMasseProject/enmasse/files/1626082/qdstaat_before.log)
qdstaat after crash:
[qdstaat_after.log](https://github.com/EnMasseProject/enmasse/files/1626087/qdstaat_after.log)
Logs from admin pod, see part after 2018-01-12T09:46:25.666:
[logs-from-ragent-in-admin.log](https://github.com/EnMasseProject/enmasse/files/1626106/logs-from-ragent-in-admin.log)
[logs-from-configserv-in-admin.log](https://github.com/EnMasseProject/enmasse/files/1626126/logs-from-configserv-in-admin.log)
Log of qdrouterd pod after start of new pod:
[logs-from-router-in-qdrouterd.log](https://github.com/EnMasseProject/enmasse/files/1626129/logs-from-router-in-qdrouterd.log)

**Comment by grs** [comment]
Is it possible to get a protocol trace from the consuming client (setting env var PN_TRACE_FRM=1 should log it)?

**Comment by lulf** [comment]
@herfort Also, if you could use kubectl logs --previous  to get the logs from the previous instance of the pod (for both admin and qdrouterd) that could help understanding the issue.

**Comment by herfort** [comment]
Here my logs again:

qdstat:
[qdstat_before.log](https://github.com/EnMasseProject/enmasse/files/1635251/qdstat_before.log)
[qdstat_after.log](https://github.com/EnMasseProject/enmasse/files/1635253/qdstat_after.log)

qdrouterd before crash and after:
[router_qdrouterd_before.log](https://github.com/EnMasseProject/enmasse/files/1635262/router_qdrouterd_before.log)
[router_qdrouterd_after.log](https://github.com/EnMasseProject/enmasse/files/1635264/router_qdrouterd_after.log)

admin:
[ragent_admin.log](https://github.com/EnMasseProject/enmasse/files/1635266/ragent_admin.log)
[configserv_admin.log](https://github.com/EnMasseProject/enmasse/files/1635267/configserv_admin.log)

Log of health check which sends telemetry and events, and consumes from QPid (PN_TRACE_FRM=1): 
[producer_consumer.log](https://github.com/EnMasseProject/enmasse/files/1635282/producer_consumer.log)

**Comment by herfort** [comment]
Maybe this is a timing and configuration issue. This problem is not reproducible sometimes, if I wait enough with sending of messages after qdrouterd crashed. The qdrouterd pod is very quickly ready in the k8s dashboard, but I cannot use it.

**Comment by lulf** [comment]
@herfort So, when the qdrouterd pod is up and running, there might be a (although small)  window between the router is up and it will accept the client connections.

**Comment by herfort** [comment]
@lulf if I connect my consumer in this time frame (can be several minutes long), this gets maybe a wrong link. So this consumer gets no more events for all time.

**Comment by herfort** [comment]
This issue can be closed. After https://github.com/eclipse/hono/pull/462/commits I can handle the detach problem on the consumer side.
For other problem above with often reconnect consumer to Qpid I created a separated issue https://github.com/EnMasseProject/enmasse/issues/807
