### ISSUE TITLE
'Learn more link', shouldn't point to a pull request, in the agent/console

### ISSUE THREAD

**Issue by vbusch** [EnMasseProject/enmasse#728]
Steps: 
1) Open the agent console.  
2) Go to '+ Create'
3) Under the Name field, there is a link 'Learn more'.  
* That link brings you to https://github.com/EnMasseProject/enmasse/pull/44

Most likely, it should just give you the tool tip, which is already there.

**Comment by jenmalloy** [comment]
@vbusch, Thank you for pointing this out. I think the intent of the Learn More link was to link out to the documentation guide. I'm working on fixing this now.

**Comment by RH-sdavey** [comment]
@vbusch @jenmalloy This is the link in console that was removed right? If so, I think we can close this issue

**Comment by vbusch** [comment]
Closing.  The link is gone.
