### ISSUE TITLE
Missing Consumer for "anycast" queue in Artemis for enmasse address of type "queue"

### ISSUE THREAD

**Issue by DanielMaier-BSI** [EnMasseProject/enmasse#736]
Hi,

we are using enmasse 0.16 Snapshot (5b32a98b). We create addresses of type "queue" with plan "pooled-persisted" via REST API. Most times this works just well and the according "anycast" queue gets created in artemis and also one consumer and one producer are connected. However from time to time there is no consumer for a queue. When this is the case, the messages get put into the queue but get never delivered to the consumer. The consumer does also NOT re-attach after some time.

See some screenshots below.

![image](https://user-images.githubusercontent.com/9269795/35099681-35eba41e-fc59-11e7-982f-8f0ac0034143.png)
![image](https://user-images.githubusercontent.com/9269795/35099688-3e065c5c-fc59-11e7-8531-ea60df4a41bc.png)
![image](https://user-images.githubusercontent.com/9269795/35099700-44f4f690-fc59-11e7-95ba-a3b40eb62cac.png)

As you can see e.g. for address "event/FREE_TENANT" we have a producer but no consumer.

I also attached logs from pooled broker and router. However, I doubt that these logs are useful with the configured log level.

[logs-from-router-in-qdrouterd-5f6b8bf6dd-g67df.txt](https://github.com/EnMasseProject/enmasse/files/1642926/logs-from-router-in-qdrouterd-5f6b8bf6dd-g67df.txt)
[logs-from-broker-in-pooled-persisted-bdf5dbc79-4tm95.txt](https://github.com/EnMasseProject/enmasse/files/1642927/logs-from-broker-in-pooled-persisted-bdf5dbc79-4tm95.txt)

Thanks
Daniel

**Comment by lulf** [comment]
@DanielMaier-BSI I've pushed a change to master that might fix this. If you can, please try https://dl.bintray.com/enmasse/snapshots/enmasse-latest.tgz

**Comment by calohmn** [comment]
@lulf I've done a test with the above snapshot and there is still an address missing in the consumer list. Here it is `SYSTEM_TEST_TENANT_2` that is missing in the list on the right:
![artemis_console_missing_t2](https://user-images.githubusercontent.com/891931/35234189-8cc2a478-ffa0-11e7-8b6b-6fa34de9c6fc.png)

Logfiles of queue-scheduler and broker (with debug log output) are here:
[logs_180122.zip](https://github.com/EnMasseProject/enmasse/files/1652935/logs_180122.zip)
Qpid log:
[qdrouter_180122.log](https://github.com/EnMasseProject/enmasse/files/1652975/qdrouter_180122.log)

When grep'ing for `SYSTEM_TEST_TENANT_1` and `SYSTEM_TEST_TENANT_2` in the artemis log and comparing the output, there are such lines appearing for tenant_1 but missing for tenant_2:
````
16:34:29,226 FINE  [proton.trace] IN: CH[0] : Attach{name='qdlink.kWNReYeRZXy+dcS', handle=0, role=RECEIVER, sndSettleMode=MIXED, rcvSettleMode=FIRST, source=Source{address='event/SYSTEM_TEST_TENANT_1', durable=NONE, expiryPolicy=LINK_DETACH, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}, target=null, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=0, maxMessageSize=0, offeredCapabilities=null, desiredCapabilities=null, properties=null}
16:34:29,227 FINE  [proton.trace] IN: CH[1] : Attach{name='qdlink.pbhKoFgtHHdbX8M', handle=0, role=SENDER, sndSettleMode=MIXED, rcvSettleMode=FIRST, source=null, target=Target{address='event/SYSTEM_TEST_TENANT_1', durable=NONE, expiryPolicy=LINK_DETACH, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=0, maxMessageSize=0, offeredCapabilities=null, desiredCapabilities=null, properties=null}
16:34:29,234 DEBUG [org.apache.activemq.artemis.core.server.impl.QueueImpl] QueueImpl[name=event/SYSTEM_TEST_TENANT_1, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=18cf8217-ff92-11e7-9089-0242ac110019], temp=false]@58bcfce9 adding consumer ServerConsumerImpl [id=0, filter=null, binding=LocalQueueBinding [address=event/SYSTEM_TEST_TENANT_1, queue=QueueImpl[name=event/SYSTEM_TEST_TENANT_1, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=18cf8217-ff92-11e7-9089-0242ac110019], temp=false]@58bcfce9, filter=null, name=event/SYSTEM_TEST_TENANT_1, clusterName=event/SYSTEM_TEST_TENANT_118cf8217-ff92-11e7-9089-0242ac110019]]
16:34:29,235 DEBUG [org.apache.activemq.artemis.core.server.impl.ServerSessionImpl] Session with user=null, connection=org.apache.activemq.artemis.protocol.amqp.broker.ActiveMQProtonRemotingConnection@8b74a40 created a consumer on queue event/SYSTEM_TEST_TENANT_1, filter = null
16:34:29,235 DEBUG [org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl] Couldn't find any bindings for address=activemq.notifications on message=CoreMessage[messageID=87,durable=true,userID=null,priority=0, timestamp=0,expiration=0, durable=true, address=activemq.notifications,properties=TypedProperties[_AMQ_RoutingName=event/SYSTEM_TEST_TENANT_1,_AMQ_Distance=0,_AMQ_ConsumerCount=1,_AMQ_User=NULL-value,_AMQ_SessionName=1e08a2d8-ff92-11e7-9089-0242ac110019,_AMQ_Address=event/SYSTEM_TEST_TENANT_1,_AMQ_RemoteAddress=10.108.105.240/10.108.105.240:56671,_AMQ_NotifType=CONSUMER_CREATED,_AMQ_NotifTimestamp=1516638869235,_AMQ_ClusterName=event/SYSTEM_TEST_TENANT_118cf8217-ff92-11e7-9089-0242ac110019]]@1183762077
16:34:29,235 DEBUG [org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl] Message CoreMessage[messageID=87,durable=true,userID=null,priority=0, timestamp=0,expiration=0, durable=true, address=activemq.notifications,properties=TypedProperties[_AMQ_RoutingName=event/SYSTEM_TEST_TENANT_1,_AMQ_Distance=0,_AMQ_ConsumerCount=1,_AMQ_User=NULL-value,_AMQ_SessionName=1e08a2d8-ff92-11e7-9089-0242ac110019,_AMQ_Address=event/SYSTEM_TEST_TENANT_1,_AMQ_RemoteAddress=10.108.105.240/10.108.105.240:56671,_AMQ_NotifType=CONSUMER_CREATED,_AMQ_NotifTimestamp=1516638869235,_AMQ_ClusterName=event/SYSTEM_TEST_TENANT_118cf8217-ff92-11e7-9089-0242ac110019]]@1183762077 is not going anywhere as it didn't have a binding on address:activemq.notifications
16:34:29,236 DEBUG [org.apache.activemq.artemis.core.server.impl.ServerConsumerImpl] ServerConsumerImpl [id=0, filter=null, binding=LocalQueueBinding [address=event/SYSTEM_TEST_TENANT_1, queue=QueueImpl[name=event/SYSTEM_TEST_TENANT_1, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=18cf8217-ff92-11e7-9089-0242ac110019], temp=false]@58bcfce9, filter=null, name=event/SYSTEM_TEST_TENANT_1, clusterName=event/SYSTEM_TEST_TENANT_118cf8217-ff92-11e7-9089-0242ac110019]]:: FlowControl::Received disable flow control message
16:34:29,236 DEBUG [org.apache.activemq.artemis.core.server.impl.QueueImpl] QueueImpl[name=event/SYSTEM_TEST_TENANT_1, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=18cf8217-ff92-11e7-9089-0242ac110019], temp=false]@58bcfce9 doing deliver. messageReferences=0
16:34:29,236 DEBUG [org.apache.activemq.artemis.core.server.impl.QueueImpl] QueueImpl[name=event/SYSTEM_TEST_TENANT_1, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=18cf8217-ff92-11e7-9089-0242ac110019], temp=false]@58bcfce9 doing deliver. messageReferences=0
````

**Comment by lulf** [comment]
@calohmn Looks like the queue-scheduler is doing the right thing. It could also be that the broker is creating the connection to the router, but the autolinks are not activated.

To check if the broker is connected to the router and the state of the autolinks, could you run something like:

```
kubectl exec qdrouterd-3668079878-lq281 -- qdmanage QUERY --type connection
kubectl exec qdrouterd-3668079878-lq281 -- qdmanage QUERY --type autoLink
```

Would also need the broker log from the same run to correlate the ip.

**Comment by lulf** [comment]
Quick update:

I was able to reproduce this locally outside of kubernetes as well.

When I create 100 connectors statically in the broker config, they all seem to be created correctly. If I use the queue scheduler to create the connectors based on config, some of the artemis netty connections are waiting indefinitely on the channel.

I've tried to modify the queue-scheduler to wait a while before creating queues + wait between creating each connector, but there are always 2-3 among 50 connections not getting established. 

I'll continue with a few more modifications and see if I can close in on the issue.

**Comment by lulf** [comment]
Another update:

I've pinpointed the issue to be within the Artemis netty connector. If I configure each connector to use a separate event loop thread pool, everything works fine. The default is to share the thread pool for multiple connectors.

A possible workaround is to do 1 thread per connector, which would limit the number of queues to the number of threads the java process would be able to created.

I'll continue debugging this issue and get some help from artemis devs.
