### ISSUE TITLE
Redesign  durable subscriptions

### ISSUE THREAD

**Issue by rgodfrey** [EnMasseProject/enmasse#767]

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/1056

**Comment by grs** [comment]
This was renamed (was Disable durable subs, which *is* now implemented) and the current name is now more general and is not yet implemented so leaving open.

**Comment by kornys** [comment]
@grs ah I'm sorry for a mistake

**Comment by k-wall** [comment]
@grs is this one now closable?
