### ISSUE TITLE
Tests for clients authorization

### ISSUE THREAD

**Issue by rgodfrey** [EnMasseProject/enmasse#775]

**Comment by kornys** [comment]
#782

**Comment by tkratky** [comment]
testing scenarios for webconsole/clients authorization tests: https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/systemtests/authorization-tests/scenarios.adoc

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/827
