### ISSUE TITLE
User is not removed using keycloak client

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#786]
scenario: 

1. Create user "pepa" and add them to group recv_*
2. Verify that user has permissions to receive messages
3. Remove user "pepa"
4. Create user "pepa" and add them to group send_*
5. verify that user "pepa" does not have permissions to receive messages --> now fails

test reproducer is currently in branch "client-authz-tests"
```sh
make MULTITENANT=true SYSTEMTEST_ARGS='standard.authz.AuthorizationTest#testUserPermissionAfterRemoveAuthz' systemtests
```

**Comment by grs** [comment]
I tried reproducing this and was not able. After deleting the user and recreating, it had no groups associated and connections authenticating as that user did not have the previous permissions.

I did this by deleting the user from keycloak directly through the console though. How are you removing the user?

**Comment by kornys** [comment]
Im using KeycloakClient in systemtest https://github.com/EnMasseProject/enmasse/blob/4010e91f1eb69c5da38e233d51f193a52968ac7e/systemtests/src/test/java/io/enmasse/systemtest/authz/AuthorizationTestBase.java#L84

**Comment by lulf** [comment]
@kornys @grs Maybe reenable test to see if this is still an issue?

From reading the comments, it looks like the test should verify that the user has been deleted in keycloak before proceeding to recreate it.

**Comment by kornys** [comment]
@lulf ok I will try this test.

**Comment by kornys** [comment]
@lulf I think I know where is an issue: looks like that user is not removed using keycloak client in  systemtests,:
```
09:22:20,091 [main] INFO io.enmasse.systemtest.KeycloakClient - User 'pepa' will be removed
09:22:20,400 [main] INFO io.enmasse.systemtest.bases.TestBase - User pepa:pepaPa55 will be created
09:22:20,406 [main] INFO io.enmasse.systemtest.KeycloakClient - Waiting for realm brokered-shared-0 to exist
09:22:20,681 [main] INFO io.enmasse.systemtest.KeycloakClient - User 'pepa:pepaPa55' already created, skipping
09:22:20,689 [main] INFO io.enmasse.systemtest.KeycloakClient - Waiting for realm brokered-shared-0 to exist
09:22:20,974 [main] INFO io.enmasse.systemtest.KeycloakClient - Waiting for realm brokered-shared-0 to exist
09:22:21,276 [main] INFO io.enmasse.systemtest.KeycloakClient - User 'pepa' successfully joined group 'pepa_group'
```

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/1375

**Comment by kornys** [comment]
fixed
