### ISSUE TITLE
DOCS: Creating an address space uses incorrect URL

### ISSUE THREAD

**Issue by garethahealy** [EnMasseProject/enmasse#790]
The docs suggest using the following cURL:
`curl -X POST -T @space.json -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -k https://$(oc get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1/addressspaces/**myspace**`

But, if you use that, you get a 405 back. If you remove the address space name off the cURL, it works as expected. i.e.:

`curl -X POST -T @space.json -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -k https://$(oc get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1/addressspaces`

This is with latest 0.16-rc1

**Comment by lulf** [comment]
This has been fixed on master in commit afcdd1d2b3dca9187a454d1969f82acc4c524cb2 but the docs build wasn't triggered.

The docs should be updated now, thanks for reporting!
