### ISSUE TITLE
Consumer loses connection to router

### ISSUE THREAD

**Issue by herfort** [EnMasseProject/enmasse#807]
I have as environment Enmasse 0.15.3 and IoT Hub running in the same namespace of k8s cluster.
My health-check consumer looses sometimes connection to Qpid for several minutes. In the log I cannot see any reasons, except DnsNameResolver problem. This occurs after HealthCheck tries to execute reconnect to Qpid, but the Qpid pod is not ready.
The attached file contains log output of several pods (router, ragent, health-check and others).
I can see several "Detected Restart of Router Node Router.qdrouterd-798fd68c97-qsk9z", but I not see a reason.
The message from weave-npc is interesting: "EVENT UpdatePod" for qdrouterd pod. But we don't execute any k8s updates on this time. And "ragent info retrieved link routes for Router.qdrouterd" several times.
[all.log](https://github.com/EnMasseProject/enmasse/files/1668032/all.log)

**Comment by lulf** [comment]
@herfort Just to understand the topology: you are using one topic for each tenant? ( while I thought you were using colocated queues instead)

The attached log is a bit hard to read, since you have so many routers deployed. It looks like the qdrouterd-798fd68c97-qsk9z is the only router restarting though. Could you attach the logs for this pod alone? Also try kubectl logs --previous qdrouterd-798fd68c97-qsk as well.

**Comment by herfort** [comment]
@lulf yes this is correct. With our 0.15.3 environment we are still using topics. Together with the 0.16.0 update, we will move towards using queues and the pooled-persisted plan.

here is the log from router
[router.log](https://github.com/EnMasseProject/enmasse/files/1673534/router.log)

**Comment by lulf** [comment]
@herfort As suspected the log doesn't give much more info :/ Do you have a way to capture core dumps in your kubernetes cluster?

**Comment by herfort** [comment]
@lulf sorry but we cannot currently capture core dumps on AWS.
Maybe you can see the answer of my question in the all.log.

There are a lot of
**ROUTER (info) Detected Restart of Router Node Router.qdrouterd-798fd68c97-qsk9z**
and 
**EVENT UpdatePod {"metadata":{"name":"qdrouterd-798fd68c97-qsk9z"**

But I see no errors on QPid pod and I don't see a reason for restarts. We have also no scheduled jobs or deployments on our cluster to this time.

**Comment by herfort** [comment]
is obsolete
