### ISSUE TITLE
Button for creating addresses is disabled in EnMasse Console (with 'none' auth service)

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#816]
Tested with 0.16.0rc3:
I've deployed EnMasse with auth service "none" in minikube and opened the EnMasse console. 
The button for creating an address is disabled there.

**Comment by lulf** [comment]
Verified that this is an issue on OpenShift too. I think the none-authservice needs to reply with the user being part of more groups.

**Comment by lulf** [comment]
This is fixed by https://github.com/EnMasseProject/enmasse/pull/813
