### ISSUE TITLE
Standard: user with view_{$address} cannot see connections under his credentials on $address

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#818]
**reproducer**:
1. create standard address space
2. create queue address test-queue
3. create user test_monitor:test_monitor withing groups view_test-queue, send_*
4. run rhea connector
```sh
npm install cli-rhea -q
cli-rhea-connector --conn-ssl true --broker test_monitor:test_monitor@<messaging-route>:443 --receiver-count 0 --obj-ctrl CESR --count 2 --sender-count 1 --timeout  120 --address test-queue --conn-property connection_property1~50 --conn-property connection_property2~testValue --log-lib TRANSPORT_FRM
```
5. open console under user test_monitor
6. see connections

automated test
```sh
cd enmasse
make client_install
make webdriver_install
Xvfb :10 -ac &
DISPLAY=:10 PATH=$PATH:$(pwd)/systemtests/web_driver make MULTITENANT=true SYSTEMTEST_ARGS='standard.web.FirefoxWebConsoleTest#testViewConnections' systemtests
```

**console under user test_monitor**
![console_view001](https://user-images.githubusercontent.com/11318335/35523740-d081ef78-051f-11e8-8901-5160aee52170.png)
![console_view002](https://user-images.githubusercontent.com/11318335/35523743-d2c8aa92-051f-11e8-81f1-c6759292780b.png)
![console_view003](https://user-images.githubusercontent.com/11318335/35523746-d4751722-051f-11e8-91b0-2e2dd6234aa9.png)

**console under user in manage group**
![console_view004](https://user-images.githubusercontent.com/11318335/35523769-e22bd3ec-051f-11e8-80df-7759a8121a6d.png)
![console_view005](https://user-images.githubusercontent.com/11318335/35523772-e3befb9e-051f-11e8-920d-cbd7c49f6336.png)
![console_view006](https://user-images.githubusercontent.com/11318335/35523773-e55880d8-051f-11e8-9efe-9f1e49fed04b.png)

**Comment by grs** [comment]
Just to confirm, the sender client is using 'test:test'. Is that the same as or different than the test_monitor user?

**Comment by kornys** [comment]
Ah sorry my bad, I copied bad line for resproducer from my command line. User is test_monitor

**Comment by k-wall** [comment]
The permission model was switched to rely on RBAC, so I believe this issue will now be invalid.
