### ISSUE TITLE
System-tests: February list of disabled tests

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#824]
1.  io.enmasse.systemtest.standard.mqtt.PublishTest#testPublishQoS2
 - bug: (QoS2 isn't implemented)
 - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/mqtt/PublishTest.java#L55

5. io.enmasse.systemtest.standard.QueueTest#testScaledown
 - bug: #851 
 - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java#L175

9. io.enmasse.systemtest.standard.TopicTest#testTopicWildcards
 - bug: #105 (probably)
 - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/TopicTest.java#L209

10. io.enmasse.systemtest.standard.TopicTest#testDurableLinkRoutedSubscription
 - bug: (if I remember correctly TopicTests were disabled due to some issue with sending mqtt messages)
 - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/TopicTest.java#L230

11. io.enmasse.systemtest.standard.TopicTest#testDurableMessageRoutedSubscription
 - bug: (if I remember correctly TopicTests were disabled due to some issue with sending mqtt messages)
 - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/TopicTest.java#L273

13. io.enmasse.systemtest.brokered.SmokeTest#testCreateAlreadyExistingAddress
 - bug: #346 
 - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/brokered/SmokeTest.java#L107

14. io.enmasse.systemtest.brokered.jms.TopicTest
 - bug: ENTMQBR-912
 - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/brokered/jms/TopicTest.java#L118
- fix for that was merged: https://github.com/apache/activemq-artemis/pull/1678

15. io.enmasse.systemtest.brokered.TopicTest.test#TopicPubSubWildcards
  - bug: https://github.com/EnMasseProject/enmasse/issues/590
  - code: https://github.com/EnMasseProject/enmasse/blob/f5e517ecd24d00f56bd3b83fead9175b379320a3/systemtests/src/test/java/io/enmasse/systemtest/brokered/TopicTest.java#L21

16. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testClientsMetrics
 -- bug: https://github.com/EnMasseProject/enmasse/issues/649

17. io.enmasse.systemtest.standard.TopicTest.testRestApi
- bug: https://github.com/EnMasseProject/enmasse/issues/693
- code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/TopicTest.java#L67

18. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testSortConnectionsByContainerId
 -- bug: https://github.com/EnMasseProject/enmasse/issues/634

19. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testFilterConnectionsByContainerId
 -- bug: https://github.com/EnMasseProject/enmasse/issues/634

20. io.enmasse.systemtest.standard.web.FirefoxWebconsoleTest#testViewConnections
 -- bug: https://github.com/EnMasseProject/enmasse/issues/818

21. io.enmasse.systemtest.standard.web.FirefoxWebconsoleTest#testViewAddressesWildcards
 -- bug: https://github.com/EnMasseProject/enmasse/issues/819

23. io.enmasse.systemtest.standard.authz.AuthorizationTest#testUserPermissionAfterRemoveAuthz
 -- bug: https://github.com/EnMasseProject/enmasse/issues/786

24. https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java#L189
-- bug #903 

25. https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/PlansTest.java#L43
-- bug #904

26. (3 tests) https://github.com/EnMasseProject/enmasse/blob/aeddee457aac636cacf540b64dd6a25444f5e0f6/systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java#L106
https://github.com/EnMasseProject/enmasse/blob/aeddee457aac636cacf540b64dd6a25444f5e0f6/systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java#L110
https://github.com/EnMasseProject/enmasse/blob/aeddee457aac636cacf540b64dd6a25444f5e0f6/systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java#L116
-- bug: #949

**Comment by tkratky** [comment]
5. fixed issue with scale because of statefulset brokers - **still disabled** due to issue: #851 
6. io.enmasse.systemtest.standard.TopicTest#testPersistedTopics - **enabled** (renamed to testShardedTopic)
7. io.enmasse.systemtest.standard.TopicTes#testMessageSelectorsAppProperty - **enabled** (seems to be stable after several runs)
8.  o.enmasse.systemtest.standard.TopicTest#testMessageSelectorsProperty - **enabled** (seems to be stable after several runs)

all enabled tests will be removed from list of disabled tests above

**Comment by tkratky** [comment]
No 26. tests are enabled as part of https://github.com/EnMasseProject/enmasse/pull/1006 PR, so could be removed from list above once PR will be merged.

**Comment by tkratky** [comment]
22. @kornys enabled all brokered.authz tests except testUserPermissionAfterRemoveAuthz which is disabled due to another issue (see description)
26. fixing bug is in progress, tests are enabled in branch issue-949
