### ISSUE TITLE
system-tests: improve assert messages in all tests

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#835]
for example: 
Instead of: "expected <6> got <3>"
should be there: "6 connections should be established into topic-via-web-0 : expected <6> got <3>"

**Comment by kornys** [comment]
Complete:
- bases.clients.MsgPatternsTestBase

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/846

**Comment by kornys** [comment]
done :) 👍
