### ISSUE TITLE
Addresses of type "queue, pooled-persisted" don't work after some time

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#862]
This is a followup of #806 (and related to #736). 
Used version is 0.16.0, with BROKER_MEMORY_LIMIT set to 2Gi.

We now have the issue, that addresses of type "queue" with plan "pooled-persisted" first work as expected, but after some time, they don't - messages don't reach the consumer.

Symptoms are that the autolinks between the qdrouter and Artemis get into state "inactive" and that the AMQP connections between qdrouter and Artemis are gone.

First questions here would be for what kind of clues to look for in the logs and whether there's some kind of workaround to re-activate the addresses.

**Comment by lulf** [comment]
If the connection is broken, the broker log should have messages like 

'connectionDestroyed for connector' or
'connectionException for connector'

Also, kubectl exec brokerpod -- jstack 1  may give a hint as to what the broker is up to.

To re-activate addresses, you can use Artemis management to destroy and recreate the connector service for a given queue. Doing that requires creating an AMQP client that connects to the broker and does that. It is however, a good idea for a useful ops tool that should be part of the broker image. Create https://github.com/EnMasseProject/enmasse/issues/865 for that.

**Comment by lulf** [comment]
@calohmn Heres an example client: https://paste.fedoraproject.org/paste/MRuyXb34t9EoPHwaz-5lAQ

You must modify the 'myqueue' to the queue the connector is missing for. The host needs to be the router service ip.

You might need to call 'destroyConnectorService' first, in which case the script must be modified.

I can provide a better out of the tool box soon.

**Comment by calohmn** [comment]
@lulf I didn't see log messages with "connectionDestroyed" or "connectionException" in the broker log.

The broker got restarted at some point and in the log there was only a `Starting connector amqp-connector` log line, no other `Starting connector` lines. So, the connectors for the brokered addresses haven't been started.

Looking at the QueueScheduler code, it seems to me, that the creation of the connectors along with the queues in `ArtemisAdapter.createQueue` might be an issue since in `SchedulerState.distributeAddressesByNumQueues()` already existing queues are skipped for the `ArtemisAdapter.createQueue()` invocation.  And the restarted broker indeed already has the queues for the brokered addresses.

**Comment by lulf** [comment]
@calohmn Ok, thats a good observation. If the connector services are not stored, we need to recreate them on restart. However, that suggests that this should be the case for all addresses. Is that the case? If so, I think I can provide a small fix in queue scheduler to make it work now.

We are reworking queue scheduling for 0.17 (part of #748) which will change this a bit and (most likely) improve the reliability.
