### ISSUE TITLE
Improve adaptibility by moving nested JSON content out of enmasse.yaml

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#863]
It would be good if adapting the EnMasse Kubernetes deployment (e.g. by changing parameters like BROKER_MEMORY_LIMIT or adding/adapting JAVA_OPTS env variables) could be made easier.

Currently such changes require adapting the nested JSON structures inside the Kubernetes enmasse.yaml and that's quite hard to do by hand or requires changing of jsonnet files and re-generation of enmasse.yaml.

It would be easier if creation of the "enmasse-template-config" ConfigMap would be done from the deployment bash scripts and contained entries ("standard-space-infra.json", "brokered-space-infra.json") would be supplied as individual files in the release zip.

Same applies to the "enmasse-storage-templates" ConfigMap.

**Comment by lulf** [comment]
@calohmn This will be configurable as part of #744 and #745 where we allow the plans to be configurable, including any parameters to the templates. Do you think that will be sufficient? (Any parameter that is exposed through the template can be configured in the plan).

**Comment by calohmn** [comment]
@lulf That's good. We define the BROKER_MEMORY_LIMIT in the "standard-plans.yaml" now.

There are however cases where the change doesn't affect a parameter. For example the JAVA_OPTS env variable for adapting memory settings.
Or we just had a case where the "admin" Pod was getting OOM-killed (maybe because of 440 addresses in our setup?). With an "unobfuscated" standard-space-infra.json the change to increase the memory settings would be simple.
Same thing applies to changes regarding liveness/readiness probe settings for a slower minikube environment.

It's just that in comparison to the straightforward Openshift enmasse.yaml, the K8s enmasse.yaml with its nested compressed JSON templates looks somewhat daunting. Maybe using YAML heredoc syntax could be an alternative as well, not having to do the quoting.

**Comment by lulf** [comment]
@calohmn I agree with the arguments you raised.

I'm wondering if a replacement for templates that could unify the OpenShift and K8s yaml files would be to defer any parameterization using configmaps like was done for the keycloak-controller, which allowed the same deployment to be used in openshift and kubernetes.

Although a bit more complexity in terms of more configmaps... and probably some work, it would get rid of the distinction between openshift and kubernetes completely. 

We would then get rid of a lot of .jsonnet code and could specify all the configuration in yaml instead, which would reduce our toolchain dependency further...

**Comment by calohmn** [comment]
@lulf That sounds very good!

One question towards understanding this: How would parameters, that aren't used in the "env" section, e.g. the parameter ADDRESS_SPACE_ADMIN_SA with this usage
````
"serviceAccount": "${ADDRESS_SPACE_ADMIN_SA}",
````
in the admin pod, be represented/replaced then? Would they be set in the "env" section and have to be applied programmatically on the K8s resource (bascially where "kubernetes.processTemplate" is used now)?

**Comment by lulf** [comment]
@calohmn Thats a valid point, and I'm not sure if I have a good solution for that. We basically have 2 types of parameters:

* Env parameters (as you point out) that can easily be replaced from configmaps
* Template parameters affecting the yaml itself. This cannot easily be changed, since there is no templating alternative for kubernetes. 

However, maybe if we can 'extract' the inner templates in enmasse.yaml into standalone files (i.e. a configmap without the obfiscated json), the new enmasse.yaml will be much smaller and only contain the address controller deployment (so should be renamed), and we can provide both a templatized and non-templatized variant of that.

The structure of the enmasse 'bundle' would be something like this:
```
enmasse-controller.yaml  // Pure k8s variant
enmasse-controller-template.yaml // OpenShift template variant
standard-space-infra.yaml // Configmap with JSON in a 'pretty' format
brokered-space-infra.yaml
...
```
I'm not totally convinced this is a good approach, since now running on OpenShift means you can't edit the templates in the same nice way (without the configmap)... 

Your observation about applying this programatically might be another approach that we could explore

**Comment by calohmn** [comment]
@lulf
> I'm not totally convinced this is a good approach, since now running on OpenShift means you can't edit the templates in the same nice way (without the configmap)...

I'm not sure I completely got what you meant, but how about sticking to the *-infra OpenShift Templates in the OpenShift deployment case.

> standard-space-infra.yaml // Configmap with JSON in a 'pretty' format

We could use a `standard-space-infra-template.yaml` with the `standard-space-infra.json` content in yml form (ie. containing a Template resource).
In the OpenShift case, this yml is deployed directly. In the K8s case, the yml is put as a file into a ConfigMap by the deployment script.
This requires the nested "standard-space-infra" and "brokered-space-infra" Templates in the current OpenShift enmasse.yml to be lifted to the top-level. Would that work?
(Having the OpenShift enmasse.yml split into several files also makes editing the parameters a bit easier since the parameters don't have to be spotted somewhere in the middle of the big file anymore and are instead located at the bottom of each template.)

The remaining address-controller deployment could be handled via the 2 variants you mentioned (K8s as normal deployment, OpenShift as template).
For the K8s address-controller deployment, I could also imagine having a client-side substitution mechanism based on a shell script like [this](https://github.com/johanhaleby/bash-templater/) or using `envsubst` (not sure how common it is though). But that would be further down the road, I guess.

**Comment by lulf** [comment]
> In the OpenShift case, this yml is deployed directly. In the K8s case, the yml is put as a file into a ConfigMap by the deployment script

This is the only thing I don't like about this idea, but I think its the best proposal so far. It shouldn't be too much work so lets test this out

**Comment by calohmn** [comment]
@lulf A further thought about this: When thinking about a future update mechanism for EnMasse, would using Templates here make things more complicated (compared to using Deployments directly)? 
Taking a quick look at the docs, I haven't found any info about how updating Openshift-Templates affects already created resources or how the Fabric8 API behaves here.

**Comment by lulf** [comment]
@calohmn Using templates sort of decouples the knowledge of what needs to be deployed so that address/standard controller and allows some level of parameterization. I think we need to decide if we want to encode more information in java about the deployments that are used instead of using templates, which would allow us to deal with upgrades on a per-component basis.

**Comment by lulf** [comment]
@calohmn This should be improved by #1162 which follows the proposals you made.

**Comment by calohmn** [comment]
@lulf Yes, thanks!
