### ISSUE TITLE
Update info about "npm" prerequisite in HACKING.md

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#879]
Since [this commit](https://github.com/EnMasseProject/enmasse/commit/010dc53d3ac2b21cfc179083131d4cd2e56d9394), `npm` is required for a full build.

The description of prerequisites in `HACKING.md` should reflect this.
Checks for the existence of `npm` in `Makefile.common` can probably be removed as well.

**Comment by grs** [comment]
That is unfortunate (and was not actually intended).
