### ISSUE TITLE
Enforce valid name for addresses

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#897]
Address resources have a mandatory 'name' field and an optional 'address' field. If the address field is not specified, its value will be taken from the 'name' field.  The reason for having the 'name' and 'address' field separate is so that 'name' should be a valid k8s identifier. This is not enforced currently. 

From the user POV, only the 'address' field is really relevant. As a fix, we can

* Make 'address' mandatory and required 'name' to be empty in the REST API. This will make the API simpler, and avoid any conflict between names and addresses.
* Enforce that if both 'name' and 'address' is specified, the 'name' must match our sanitized version of 'address'.

**Comment by grs** [comment]
Why move address from spec to metadata?

**Comment by lulf** [comment]
@grs I guess the only reason is that it is a bit strange we have 'name' and 'addressSpace' in 'metadata' but 'address' in 'spec'. Also I think it just feels a bit strange to have 'empty' metadata :)

**Comment by grs** [comment]
I see the spec as being the description of the address we want, and the address field is very much part of that.

The metadata would not be empty once the resource is created.

**Comment by lulf** [comment]
@grs should we then move uuid and addressSpace to the spec?

**Comment by grs** [comment]
For addressSpace, I could see either way. Fo uuid, I think that should *not* be in spec as it has nothing to do with how the address is realised. It is internal metadata, similar to the name (as distinct from address), so fits better in the metadata.

**Comment by lulf** [comment]
@grs ok, I guess 'addressSpace' is mostly used as 'metadata' so it should belong there then. I've updated the initial bullet point to keep 'address' in spec.

**Comment by lulf** [comment]
@grs How about also this change to the sanitizing logic in both console and restapi:  Instead of creating a qualifier based on a hash of the address, make the last part of the identifier a uuid and truncate the 'name' part to have the uuid string fit.

We would then use this identifier as the name of the configmap as well as the 'name' in the address. This would avoid the 'address-config-' prefix and would ensure that the configmap would not conflict with other addresses with a similar name. A configmap would therefore look like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myqueue-264d1392-1619-11e8-afb8-507b9def37d9
data:
  config.json: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "Address",
      "metadata": {
        "name": "myqueue-264d1392-1619-11e8-afb8-507b9def37d9",
        "uuid": "264d1392-1619-11e8-afb8-507b9def37d9"
       },
       "spec": {
         "address": "myqueue"
       }
    }
```

The payload as input to the REST API would be:
```
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "Address",
       "spec": {
         "address": "myqueue"
       }
    }
```

**Comment by grs** [comment]
Keeping the address name and configmap name the same makes a lot of sense. I think that is the only assumption that should be made with regards to deleting  etc.

I don't object to using an uuid instead of a has as a qualifier for consistency, but the specific pattern used should not affect deletion and status changes providing the address name and configmap name match.

I've made the two changes to agent here: https://github.com/EnMasseProject/enmasse/pull/911

**Comment by calohmn** [comment]
@lulf Was it intended that with this change the sanitized name now has to be used in the URLs of the address controller REST api?

E.g.: having created an address "telemetry/TEST", the URL to check on this address is now `http://[host:port]/apis/enmasse.io/v1/addresses/default/telemetrytest`.

In earlier EnMasse versions, it was `http://[host:port]/apis/enmasse.io/v1/addresses/default/telemetry%2FTEST`. That made it more straightforward to query the status of a created address.

**Comment by lulf** [comment]
@calohmn Yes, it is, after the discussions in #928. I'm not fully convinced it is the appropriate behaviour, but if an Address were a proper custom resource (defined using https://kubernetes.io/docs/concepts/api-extension/custom-resources/), this sanitization would be required which is what we've modelled the Address and AddressSpace resource after.

Maybe one alternative would be to support something like `/apis/enmasse.io/v1/addresses/default/?address=telemtry%2FTEST` ?

Alternatively you can define your own 'mapping' when you create the address by setting 'name' to some well-known sanitized form of 'address'.

**Comment by calohmn** [comment]
@lulf Ok, makes sense.

> Maybe one alternative would be to support something like /apis/enmasse.io/v1/addresses/default/?address=telemtry%2FTEST ?

Yes, that would be good.

> Alternatively you can define your own 'mapping' when you create the address by setting 'name' to some well-known sanitized form of 'address'.

Yes, I guess we'll do that for now (although it adds a dependency on the specific sanitization logic).
