### ISSUE TITLE
agent container is restarted (failed on OOM) after request for deploy 2000 addresses

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#903]
Terminated at Feb 19, 2018 1:42:52 PM with exit code 137 (OOMKilled)
During ~10 minutes is agent restarted 6times with following events:

2:01:15 PM | Warning | Back-off | Back-off restarting failed container         23 times in the last 11 minutes
-- | -- | -- | --
1:46:52 PM | Warning | Unhealthy | Liveness  probe failed: Get https://172.17.0.11:8080/probe: net/http: request  canceled while waiting for connection (Client.Timeout exceeded while  awaiting headers)         4 times in the last 19 minutes
1:42:52 PM | Normal | Pulling | pulling image "docker.io/enmasseproject/agent:latest"         2 times in the last hour
1:42:52 PM | Warning | Unhealthy | Liveness  probe failed: Get https://172.17.0.11:8080/probe: read tcp  172.17.0.1:59244->172.17.0.11:8080: read: connection reset by peer
1:42:52 PM | Warning | Unhealthy | Readiness  probe failed: Get https://172.17.0.11:8080/probe: read tcp  172.17.0.1:59246->172.17.0.11:8080: read: connection reset by peer
1:42:42 PM | Warning | Unhealthy | Readiness  probe failed: Get https://172.17.0.11:8080/probe: net/http: request  canceled while waiting for connection (Client.Timeout exceeded while  awaiting headers)

In broker log you can see that during ~6 minutes was created < 900 queues
```
12:42:34,975 WARN [org.apache.activemq.artemis.core.server] AMQ222166: No Expiry Address configured for queue weak-queue-0 in AddressSettings
...
12:48:23,210 WARN [org.apache.activemq.artemis.core.server] AMQ222166: No Expiry Address configured for queue weak-queue-848 in AddressSettings

```

reproducible via automated test: (**in systests-plan-tests branch**)
`make MULTITENANT=true SYSTEMTEST_ARGS='standard.QueueTest#testScalePooledQueueAutomatically' systemtests`

steps to reproduce are basically create standard address space and deploy bigger count of pooled address

**Comment by grs** [comment]
@tkratky did you create all addresses at once? or in batches?

**Comment by grs** [comment]
@kornys the reference in the disabled tests doesn't seem to match. I believe the issue as described is fixed (there is a separate issue regarding the responsiveness of the console itself)?

**Comment by kornys** [comment]
@grs yes it is not listed in list of disabled tests, because this test was removed. Is this creating of large number of queues covered by unit tests? So we can close issue.

**Comment by grs** [comment]
@kornys I think there is a test associated with https://github.com/EnMasseProject/enmasse/issues/1309 (disabled pending resolution of that issue).
