### ISSUE TITLE
console addresses do not get a status

### ISSUE THREAD

**Issue by grs** [EnMasseProject/enmasse#909]
The standard-controller appears to be using a different prefix for the configmap name (addressconfig instead of address-config-) which may well be the cause?

**Comment by lulf** [comment]
@grs My bad, I did some changes to make the sanitizing similar to what was done in the agent. What I didn't take into account was that the whole string address-config would then be sanitized to addressconfig. I'll fix this as part of #905

**Comment by lulf** [comment]
Fix pushed to master
