### ISSUE TITLE
rest api returns wrong address status {"isReady":true,"phase":"Pending"}

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#927]
address-space: standard
addresses: queue(sharded-queue)/topic(sharded-topic) 

_addresses_ deployed into _address-space_ are ready to use (simple send/receive) but .status.phase is set to "Pending"

reproducer
1. create _address-space_ 
```
TOKEN=$(oc whoami -t)
ADDRESS_SPACE_DEF="standardSpace.json"
curl -k -X POST -H "content-type: application/json" --data-binary @${ADDRESS_SPACE_DEF} -H "Authorization: Bearer ${TOKEN}" https://$(oc get route -n myproject -o jsonpath='{.spec.host}' restapi)/apis/enmasse.io/v1/addressspaces

```
2. deploy _addresses_
```
TOKEN=$(oc whoami -t)
ADDRESS_DEF="standard_qt.json"
ADDR_SPACE="myspace-standard2"
curl -k -X PUT -H "content-type: application/json" --data-binary @${ADDRESS_DEF} -H "Authorization: Bearer ${TOKEN}" https://$(oc get route -n myproject -o jsonpath='{.spec.host}' restapi)/apis/enmasse.io/v1/addresses/${ADDR_SPACE}/
```
3. get all addresses
```
TOKEN=$(oc whoami -t)
ADDR_SPACE="myspace-standard2"
curl -k -X GET -H "Authorization: Bearer ${TOKEN}" https://$(oc get route -n myproject -o jsonpath='{.spec.host}' restapi)/apis/enmasse.io/v1/addresses/${ADDR_SPACE}/
```
4. result:
```
{"apiVersion":"enmasse.io/v1","kind":"AddressList","items":[{"metadata":{"name":"myqueue","addressSpace":"myspace-standard2","uuid":"e47135de-28d5-336d-95ed-5a816cf61658"},"spec":{"type":"queue","plan":"sharded-queue","address":"myqueue"},"status":{"isReady":true,"phase":"Pending"}},{"metadata":{"name":"mytopic","addressSpace":"myspace-standard2","uuid":"7f13ef30-88ed-3312-98a3-c2e2fc468f3b"},"spec":{"type":"topic","plan":"sharded-topic","address":"mytopic"},"status":{"isReady":true,"phase":"Pending"}}]}
```

address_space definition: standardSpace.json
```
{
    "apiVersion": "enmasse.io/v1",
    "kind": "AddressSpace",
    "metadata": {
        "name": "myspace-standard2", 
        "namespace": "myspace-standard2" 
    },
    "spec": {
        "type": "standard",
	"plan": "unlimited-standard",
	"authenticationService": {
	    "type": "none"
	}
    }
}
```

addresses definition: standard_qt.json
```
{
  "apiVersion": "enmasse.io/v1",
  "kind": "AddressList",
  "items": [
    {
      "metadata": {
        "name": "myqueue"
      },
      "spec": {
        "address": "myqueue",
        "type": "queue",
        "plan": "sharded-queue"
      }
    },
    {
      "metadata": {
        "name": "mytopic"
      },
      "spec": {
        "type": "topic",
        "address": "mytopic",
        "plan": "sharded-topic"
      }
    }
  ]
}
```

however in standard-controller log you can see that addresses are in phase "Active:
```
2018-02-22 07:41:32 INFO  AddressController:119 - Checking cluster myqueue against address {address=myqueue,name=myqueue,uuid=e47135de-28d5-336d-95ed-5a816cf61658,annotations={},type=queue,plan=sharded-queue,status={isReady=true,phase=Active},version=8811}
2018-02-22 07:41:32 INFO  AddressController:119 - Checking cluster myqueue against address {address=mytopic,name=mytopic,uuid=7f13ef30-88ed-3312-98a3-c2e2fc468f3b,annotations={},type=topic,plan=sharded-topic,status={isReady=true,phase=Active},version=8812}
2018-02-22 07:41:32 INFO  AddressController:117 - Checking cluster with id mytopic
2018-02-22 07:41:32 INFO AddressController:119 - Checking cluster mytopic against address {address=myqueue,name=myqueue,uuid=e47135de-28d5-336d-95ed-5a816cf61658,annotations={},type=queue,plan=sharded-queue,status={isReady=true,phase=Active},version=8811}
```

ConfigMap of myqueue contains phase "Active" as well
```
{"apiVersion":"enmasse.io/v1","kind":"Address","metadata":{"name":"myqueue","addressSpace":"myspace-standard2","uuid":"e47135de-28d5-336d-95ed-5a816cf61658"},"spec":{"type":"queue","plan":"sharded-queue","address":"myqueue"},"status":{"isReady":true,"phase":"Active"}}
--
```

I'll try to reproduce with brokered...

**Comment by tkratky** [comment]
also reproducible with brokered, but there is one difference:
address ConfigMap contains phase: "Pending" !
```
{"apiVersion":"enmasse.io/v1","kind":"Address","metadata":{"name":"myqueue","addressSpace":"myspace-brokered2","uuid":"e47135de-28d5-336d-95ed-5a816cf61658"},"spec":{"type":"queue","plan":"brokered-queue","address":"myqueue"},"status":{"isReady":true,"phase":"Pending"}}
```

**Comment by kornys** [comment]
@grs Same issue is with console address statuses -> still shows pending state.
![pending](https://user-images.githubusercontent.com/11318335/36527455-19a503d0-17b2-11e8-8223-90967c207f17.png)

**Comment by grs** [comment]
On standard space, I can reproduce the issue with the rest api  - it continues to return pending as the phase even once the configmap has been updated to show active. However the console seems to me to accurately reflect the configmap phase. @kornys, when you saw the above, did you check the configmap contents?

**Comment by kornys** [comment]
@grs yes, I did. there is output 
```
{"apiVersion":"enmasse.io/v1","kind":"Address","metadata":{"name":"authz-queue-e948026e-f8a0-3822-9a56-4f070fe34e16","addressSpace":"brokered-shared-0","uuid":"e948026e-f8a0-3822-9a56-4f070fe34e16"},"spec":{"type":"queue","plan":"brokered-queue","address":"authz-queue"},"status":{"isReady":true,"phase":"Pending"}}
```

**Comment by grs** [comment]
@kornys ok, so the console is then displaying the status correctly. The question is why the phase isn't transitioning to Active. Does it change if you look again after a minute or two? Are the pods up and running for the queue and topic?

**Comment by kornys** [comment]
@grs yep I agree console works fine -> we can merge console-status to master. And yes pod is up and running, I can send/receive messages from authz-queue.

**Comment by grs** [comment]
Just as an experiment, I tried with addresses where the name was not specified via the rest api (and was therefore generated by address-controller) to see if that had any impact. It does not, the rest api still does not reflect what is in the config-map:

`$ oc get configmap myqueue-e47135de-28d5-336d-95ed-5a816cf61658 -o yaml
apiVersion: v1
data:
  config.json: '{"apiVersion":"enmasse.io/v1","kind":"Address","metadata":{"name":"myqueue-e47135de-28d5-336d-95ed-5a816cf61658","addressSpace":"myspace","uuid":"e47135de-28d5-336d-95ed-5a816cf61658"},"spec":{"type":"queue","plan":"sharded-queue","address":"myqueue"},"status":{"isReady":true,"phase":"Active"}}'
kind: ConfigMap
metadata:
  annotations:
    addressSpace: myspace
    cluster_id: myqueue-e47135de-28d5-336d-95ed-5a816cf61658
  creationTimestamp: 2018-02-22T09:14:03Z
  labels:
    type: address-config
  name: myqueue-e47135de-28d5-336d-95ed-5a816cf61658
  namespace: enmasse-myspace
  resourceVersion: "1927"
  selfLink: /api/v1/namespaces/enmasse-myspace/configmaps/myqueue-e47135de-28d5-336d-95ed-5a816cf61658
  uid: ba0058f4-17b0-11e8-a50a-54ee755a3014
$ oc get configmap mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b -o yaml
apiVersion: v1
data:
  config.json: '{"apiVersion":"enmasse.io/v1","kind":"Address","metadata":{"name":"mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b","addressSpace":"myspace","uuid":"7f13ef30-88ed-3312-98a3-c2e2fc468f3b"},"spec":{"type":"topic","plan":"sharded-topic","address":"mytopic"},"status":{"isReady":true,"phase":"Active"}}'
kind: ConfigMap
metadata:
  annotations:
    addressSpace: myspace
    cluster_id: mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b
  creationTimestamp: 2018-02-22T09:14:03Z
  labels:
    type: address-config
  name: mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b
  namespace: enmasse-myspace
  resourceVersion: "1928"
  selfLink: /api/v1/namespaces/enmasse-myspace/configmaps/mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b
  uid: ba00f284-17b0-11e8-a50a-54ee755a3014
$ curl -H "Authorization: Bearer $(oc whoami -t)" -k https://$(oc get route -n myproject restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1/addresses/myspace
{"apiVersion":"enmasse.io/v1","kind":"AddressList","items":[{"metadata":{"name":"myqueue-e47135de-28d5-336d-95ed-5a816cf61658","addressSpace":"myspace","uuid":"e47135de-28d5-336d-95ed-5a816cf61658"},"spec":{"type":"queue","plan":"sharded-queue","address":"myqueue"},"status":{"isReady":true,"phase":"Pending"}},{"metadata":{"name":"mytopic-7f13ef30-88ed-3312-98a3-c2e2fc468f3b","addressSpace":"myspace","uuid":"7f13ef30-88ed-3312-98a3-c2e2fc468f3b"},"spec":{"type":"topic","plan":"sharded-topic","address":"mytopic"},"status":{"isReady":true,"phase":"Pending"}}]}
`

**Comment by grs** [comment]
one other - somewhat tangential - observation is that the status goes to isReady:true, phase:Active even before the the sharded queue/topic pods are running.

**Comment by grs** [comment]
For the brokered space, there is a separate issue. There, until now, the phase isn't used at all. However with the change to the console it needs to be so I have pushed a simple fix to that branch.

The same issue with the rest api is visible in the brokered space though. I.e. even when configmap is updated to be Active, the phase returned by a get call to the rest api does not reflect that.
