### ISSUE TITLE
Systemtests unable to delete a single address

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#928]
@rgodfrey @grs @tkratky @kornys 

Some systemtests like the *testRestApi tests use the DELETE /apis/enmasse.io/v1/addresses/standard-shared-0/myAddress1

However with the recent change when sanitizing address names, this does not work, as the REST API expects the 'name' of the Address resource to be used, not the 'address'. If we want to conform to REST norms, I think the client should use the names of the resources when using the API. Another nice property of using the name to refer to the resource is that no URL encoding is needed. This approach is also 'compatible' with how CRDs would work.

However from a client POV it would perhaps be more practical to refer to address resources using the address, so an alternative is to change the REST API to refer to resources by its address... in which case we have to change the systemtests a bit so that they use the Address resource name instead of the address.

**Comment by tkratky** [comment]
@lulf I'm not sure if I understand correctly but if I create 3 pooled queues (queue-1, queue-2 and queue-3) then all of them are using Address resource "broker", right? So when we would like to remove queue-2 then we should send DELETE to /apis/enmasse.io/v1/addresses/standard-shared-0/broker ? How can I get Address resource name of specific address ?

**Comment by grs** [comment]
The rest api allows you to specify the name (must be valid and unique), in which case the name used to create the address can be used to delete it. However I believe you can only specify the name if it exactly matches the address which means no underscores, uppercase letters etc (as these would be invalid in the name).

**Comment by grs** [comment]
> I probably need to get all addresses from address-space via GET method and find full name of address with prefix queue-2, right?

You shouldn't need to worry about prefix, just get the element where spec.address matches the address you want, then the name is in metadata.name
