### ISSUE TITLE
system-tests: create new test for thorough testing of REST API for address/address-space

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#936]
according to following document https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/address-model/resource-definitions.adoc send requests with unset/set Optional parameters and check if values are set properly

one of test cases is: 
Create an address space with endpoints having 'certProvider' set to 'wildcard':
```json
spec:
--
type: standard
endpoints: [
{
"name": "messaging",
"service": "messaging",
"certProvider": {
"name": "wildcard"
}
}
]
```

**Comment by grs** [comment]
@tkratky I believe that document is now slightly out of date. For addresses, the name is now optional but the address is required. @lulf is that correct?

**Comment by lulf** [comment]
@tkratky @grs Yes, I will update the document.

**Comment by tkratky** [comment]
thanks both! @lulf @grs

**Comment by tkratky** [comment]
this issue should cover following scenario as well: https://github.com/EnMasseProject/enmasse/issues/947

**Comment by tkratky** [comment]
# gaps

## AddressSpace

Method | Path | Description
-- | -- | --
- [x] GET | /v1/addressspaces | to retrieve 
- [x] GET | /v1/addressspaces/myspace | to retrieve single address space
- [/] POST | /v1/addressspaces | create and append single or multiple (AddressSpace, or AddressSpaceList) or fail if exists
- [/] PUT | /v1/addressspaces | replace a single or multiple (AddressSpace, or AddressSpaceList)
- [/] PUT | /v1/addressspaces/:name | create or replace
- [x] DELETE | /v1/addressspace/:name | delete

POST | /v1/addressspaces - create multiple address-spaces in one request **(modify authentication tests to do that instead of creating new test) (new issue)**
PUT  | /v1/addressspaces **(is not supported - already known issue: https://github.com/EnMasseProject/enmasse/issues/604) (new issue)**
PUT | /v1/addressspaces/:name **(is not supported - already known issue: https://github.com/EnMasseProject/enmasse/issues/604) (new issue)**

### AddressSpace resource:

"namespace" parameter is Optional but system-tests define it everytime - what should happen when namespace is not set?? @lulf 
```
 "metadata": {
        "namespace": "mynamespace" // Optional
    },
```
Endpoints are never tested within system-tests. New Test class for AddressSpaceApiTest should be created and 
- routes should be tested (console, mqtt, messaging) for "name" and "service" (new issue)
- "host" @lulf - do you know please what do we need to setup for testing ? 
- "cert" - create new issue for that
```
"endpoints": [ // Optional. If not provided, the default generated hostnames will be provided.
            {
                "name": "endpoint1",             // Required.
                "service": "messaging",          // Required.
                "host": "messaging.example.com", // Optional. The host name for this endpoint to use for routing by the load balancer
                "cert": {                        // Optional. Self-signed certificates are generated if not specified
                    "provider": "selfSigned",    // Provider may be selfsigned or 'wildcard'
                    "secretName": "mysecret"
                }
            }
        }
```
## Address

Method | Path | Description
-- | -- | --
- [x] GET | /v1/addresses/myspace | to retrieve list
- [/] GET | /v1/addresses/myspace/:name | to retrieve single address
- [x] POST | /v1/addresses/myspace | create and append single or multiple (Address, or AddressList) or fail if exists
- [/] PUT | /v1/addresses/myspace/:name | replace a single address
- [1/2] PUT | /v1/addresses/myspace | replace multiple addresses
- [x] DELETE | /v1/addresses/myspace/:name | delete
- [/] DELETE | /v1/addresses/myspace | delete all

GET | /v1/addresses/myspace/:name - **runRestApiTest within TestBaseWithShared should be modified to get specific address (new issue)**
PUT | /v1/addresses/myspace/:name - **replace single address is never tested in system-tests (new issue), currently doesn't work, correct behavior will be explained as part of #1024  **
PUT | /v1/addresses/myspace - **replace multiple addresses is used, but is not working if address already exists - we are waiting until correct behavior will be defined (https://github.com/EnMasseProject/enmasse/issues/1024)**
DELETE | /v1/addresses/myspace - **is never tested in system-tests (new issue)**

### Address resources
- create test with unset "name" and verify generated name (new issue)
- create test with set "uuid", unset "name" and verify generated "uuid" and "name" (new issue)
- "addressSpace" is optional only for singletenant? because in multitenant it returns list of available address-spaces @lulf 
```
 "metadata": {
        "name": "myqueue", // optional, assigned by API. Default would be set to 'myqueue-4bfe49c2-60b5-11e7-a5d0-507b9def37d9'
        "uuid": "4bfe49c2-60b5-11e7-a5d0-507b9def37d9", // Optional, assigned by API
        "addressSpace": "myspace" // Optional. Defaults to 'default' address space
    }
```
create tests for correct response when required parameters are not set (new issue)
```
"spec": {
        "address": "my_queue",  // Required. Default is .metadata.name
        "type": "queue",        // Required. Valid types are defined by the AddressSpace
        "plan": "medium"        // Required. Valid plans can be found using /apis/enmasse.io/v1/schema
    }
```

### Schema

GET /v1/schema - there are no tests in system-tests (new issue)
- check if response from the server returns appropriate data

**Comment by tkratky** [comment]
all tests are tracked separately and this issue can be closed

**Comment by lulf** [comment]
@tkratky @kornys 

For address spaces, if 'namespace' is not set, 'enmasse-$name' will be used instead.

For addresses, when you use the REST API, the 'addressSpace' will be automatically set so it is optional. If it is set to something different than what is used in the  URL, then it should fail
