### ISSUE TITLE
Credit limitations does not work 

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#957]
I have followed this scenarios https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/design/resource-scheduler.adoc#testing and scenario2 does not work. It tries to create 3 queues, but only first 2 are active, the last one is still in pending phase. Anyway in broker-0 and broker-1 pod logs of broker missing any log record about creating queue.

test is **testQuotaLimits** in branch **test-credit-limitations** https://github.com/EnMasseProject/enmasse/pull/953

there is standard-controller log
[admin-2170124250-14j9k.standard-controller.txt](https://github.com/EnMasseProject/enmasse/files/1764695/admin-2170124250-14j9k.standard-controller.txt)

maybe I do something wrong.

**Comment by rgodfrey** [comment]
I think the scenario definition is wrong - it is wanting to create three
queues which each require 0.6 of a broker, with 2 brokers available... but
as far as I understand it, a single pooled queue cannot be shared across
multiple brokers, so after two queues have been created we'll have two
brokers each "60%" full, and neither with room for another 0.6 queue.

**Comment by kornys** [comment]
@rgodfrey many thanks :) I will rewrite test

**Comment by kornys** [comment]
fixed in branch **test-credit-limitations**
