### ISSUE TITLE
Login into Artemis console doesn't work anymore

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#975]
Using 0.17.0, the login to the Artemis console doesn't seem to work anymore. 

We have a user "enmasse-admin" that is in the Keycloak group "manage" (as well as in "send_*" and "recv_*"). When trying the login with that user, there is this log output in the broker:
````
14:29:24,596 DEBUG [io.hawt.system.Authenticator] doAuthenticate[realm=activemq, role=manage, rolePrincipalClasses=org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal, configuration=null, username=enmasse-admin, password=******]
14:29:24,600 DEBUG [io.hawt.system.Authenticator] Unknown callback class [org.apache.activemq.artemis.spi.core.security.jaas.CertificateCallback]
14:29:24,823 FINE  [org.apache.qpid.proton.engine.impl.SaslImpl] Handled outcome: SaslImpl [_outcome=PN_SASL_OK, state=PN_SASL_PASS, done=true, role=CLIENT]
14:29:24,839 DEBUG [io.enmasse.artemis.sasl_delegation.SaslDelegatingLogin] Adding user principal for: enmasse-admin
14:29:24,839 DEBUG [io.enmasse.artemis.sasl_delegation.SaslDelegatingLogin] Adding role principal for: all
14:29:24,839 DEBUG [io.enmasse.artemis.sasl_delegation.SaslDelegatingLogin] Adding role principal for: send_*
14:29:24,839 DEBUG [io.enmasse.artemis.sasl_delegation.SaslDelegatingLogin] Adding role principal for: recv_*
14:29:24,839 DEBUG [io.enmasse.artemis.sasl_delegation.SaslDelegatingLogin] commit, result: true
14:29:24,845 DEBUG [io.hawt.system.Authenticator] Looking for rolePrincipalClass: org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal
14:29:24,846 DEBUG [io.hawt.system.Authenticator] Checking principal, classname: org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal toString: all
14:29:24,846 DEBUG [io.hawt.system.Authenticator] role all doesn't match manage, continuing
14:29:24,846 DEBUG [io.hawt.system.Authenticator] Checking principal, classname: org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal toString: send_*
14:29:24,846 DEBUG [io.hawt.system.Authenticator] role send_* doesn't match manage, continuing
14:29:24,846 DEBUG [io.hawt.system.Authenticator] Checking principal, classname: org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal toString: recv_*
14:29:24,846 DEBUG [io.hawt.system.Authenticator] role recv_* doesn't match manage, continuing
14:29:24,846 DEBUG [io.hawt.system.Authenticator] Checking principal, classname: org.apache.activemq.artemis.spi.core.security.jaas.UserPrincipal toString: enmasse-admin
14:29:24,846 DEBUG [io.hawt.system.Authenticator] principal class org.apache.activemq.artemis.spi.core.security.jaas.UserPrincipal doesn't match org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal, continuing
14:29:24,846 DEBUG [io.hawt.system.Authenticator] User enmasse-admin does not have the required role manage
````

It seems the `SaslDelegatingLogin.getUserAndRolesFromConnection()` method doesn't add the "manage" group to the roles anymore.

**Comment by rgodfrey** [comment]
Does adding the enmasse-admin into a Keycloak group named "manage_*" make it work?

**Comment by calohmn** [comment]
No, it looks like it has to be "manage" (for the standard address space usage, `HAWTIO_ROLE` is set to "manage"; in the brokered space it is "admin").

**Comment by rgodfrey** [comment]
OK - the way the keycloak plugin communicates authz information to the broker changed recently; such that it will only look at groups named <permission>_<address>; I'm not overly familiar with how the console access has been set up in standard - I'll work with @lulf to try to sort this out

**Comment by calohmn** [comment]
@lulf When requiring the group name to be `manage_*` now, I guess it also makes sense to use that group name for admin access to the EnMasse console (?).

**Comment by lulf** [comment]
@calohmn So that commit doesn't work for me, so need to dig into this a bit more first. The enmasse console doesn't yet use the same scheme as the artemis sasl plugin, so I think that should be fixed as well for that to work.

Currently trying to use manage_artemis as the role. @rgodfrey it doesn't look like tha hawtio console is happy matching manage_artemis against manage_*:

08:42:04,171 DEBUG [io.hawt.system.Authenticator] role manage_* doesn't match manage_artemis, continuing                                                                     
08:42:04,171 DEBUG [io.hawt.system.Authenticator] User test does not have the required role manage_artemis

How about adding the 'manage' role in the same way as the 'admin' role is always added?

**Comment by lulf** [comment]
Fixed by https://github.com/EnMasseProject/enmasse/pull/977
