### ISSUE TITLE
Update qdrouterd-base image to Qpid Dispatch 1.0.1

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#979]
This ticket shall track the update of the "qdrouterd-base" docker image to include Qpid Dispatch 1.0.1.
Eclipse Hono uses the "qdrouterd-base" as well and it would be good to have the latest fixes contained in the 1.0.1 release (especially some memory leak fixes) in this image.

**Comment by grs** [comment]
For enmasse we need a later version, that includes the authorization changes to the router. I'm just building a new base image: https://github.com/EnMasseProject/router-docker-base/pull/12

**Comment by lulf** [comment]
@calohmn So even though the enmasse image is named 1.0.0, it is actually newer than 1.0.1 and includes all of those fixes. I created https://github.com/EnMasseProject/router-docker-base/pull/13 to reflect that.

**Comment by calohmn** [comment]
Closing the ticket, as there is already a newer Qpid Dispatch version used.
