### ISSUE TITLE
Providing an "issues/troubleshooting" section in the documentation

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse#98]
Hi,
this morning I tried to run EnMasse on OpenShift having the following error on address-controller startup : 

> Unable to parse arguments: Unable to find value for required environment var 'NAMESPACE'

I was working with Docker 17.05 CE but OpenShift Origin 1.5. Updating to OpenShift Origin 3.6.0 fixed the problem. Before this configuration, it worked fine with Origin 1.5 but Docker 1.13.
I know that we can't make a matrix for working configuration but maybe it could be worth having a sort of "issues/troubleshooting" section in the documentation trying to explain the problems and their fixes we encounter during EnMasse setup. It could be a good resource for the community members before they try to contact EnMasse core team on IRC or via mailing list.

**Comment by ppatierno** [comment]
@lulf I added the following page : 

https://github.com/EnMasseProject/enmasse/blob/master/documentation/issues/issues.md

not yet referenced by any other page in the documentation. 
Maybe the main README.md after the "Contributing" section or better the README.md under "documentation" could be the right place for the link ? Wdyt ?

**Comment by lulf** [comment]
How about both README.md under documentation and as part of "Getting help' in the main README.md?

**Comment by ppatierno** [comment]
@lulf Agree. I'm going to put the link in both sections ;)
