### ISSUE TITLE
Visual glitch in the console

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#990]
Having a single "queue" seems to cause a glitch in the admin console:

![image](https://user-images.githubusercontent.com/202474/36965323-9fd13500-2059-11e8-99cc-a267d3d70038.png)

I would expect the "incoming" bot be on left side and the "outgoing" box on the same row, aligned right.

**Comment by k-wall** [comment]
@ctron are you still seeing this issue?  If so, can you report the browser you are using?

**Comment by k-wall** [comment]
@ctron great, thanks for letting us know.
