### ISSUE TITLE
Cache/watch schema resources

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#999]
To avoid a lot of requests for configmaps when address spaces and addresses are created.

**Comment by pho-enix** [comment]
Hello @lulf 
Good to see that this is getting fixed.

However, please help me understand:

Kubernetes already has caches implemented for configmaps (on kubelet level). If you would retrieve the configmap via a mount you should get that for free. Of course there is no caches when directly talking to apiserver, as of now. Also not sure if openshift does the same.

**Comment by lulf** [comment]
@pho-enix 

In this specific case we don't know the name of the configmaps that would have to be mounted, its not only 1 config map. We just query configmaps with the label type=address-plan, type=address-space-plan and type=resource-definition (as those constitute the 'schema'). Not sure if it is possible to mount that at all?

Also, last time I checked, mounted configmaps are not updated on changes, only by periodic scan (which can be several minutes iirc). Do you know if this has changed in newer versions?

**Comment by pho-enix** [comment]
I understand your concern. I am not aware of an way to mount a set of configmaps based on a label selection. One could dynamically mount all configmaps that match the label, but that's complicated and we wouldn't win a lot.

Right now the kubernetes default is 60s which should be ok for an eventually consistent system. There might be an ttl annotation, but I was not able to find any proper documentation about it.

**Comment by pho-enix** [comment]
Yes. Maybe the use-case is really to special.

**Comment by lulf** [comment]
@pho-enix After thinking about this some more and studying the kubernetes controller library, I think we can do some improvements to reduce the load on the API server. See https://github.com/EnMasseProject/enmasse/issues/1011 and https://github.com/EnMasseProject/enmasse/issues/1009
